### ISSUE TITLE
Fit carbon filter to fresh water system. Will help reduce water flow

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#100]
who: CORC

**Comment by DeeTaylor87** [comment]
Whitworths have these:
https://www.whitworths.com.au/main_itemdetail.asp?cat=133&item=35915&intAbsolutePage=
or
https://www.whitworths.com.au/main_itemdetail.asp?cat=133&item=35919&intAbsolutePage=2

I'm happy to pick one up if someone decides what to get.

**Comment by DeeTaylor87** [comment]
The guy in RT Marine recommended this:
https://www.roadtechmarine.com.au/322-h-b-e-s-t-inline-water-filter/p/TCE302

**Comment by smr547** [comment]
Closing this item -- historical
