### ISSUE TITLE
Buy a new roll or pieces of anti skid/non scratch for tables and surfaces

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#103]
Throw away mouldy old stuff
who: CORC

**Comment by DeeTaylor87** [comment]
This has been done (although some of the old stuff was still on board).  It seems a duplicate of a previous issue. Not sure how to 'close' the issue.

**Comment by smr547** [comment]
Seems on the maintenance officer can close issues. Maybe this is a good thing?

**Comment by DeeTaylor87** [comment]
See duplicate Issue 164?
