### ISSUE TITLE
Fit an anchor circuit breaker rather than huge 100A fuse.

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#107]
Bill has requested one

**Comment by jphayden** [comment]
This has been done but obviously we need to write it up:
a. in the ship's manual under the anchor system
b. in the ship's manual in the Emergencies Section
I will liaise with Dave Holt and put something in the famil doc - which really is the basis for the ship's manual.

**Comment by smr547** [comment]
This needs to be labelled -- It is behind the backrest cushion directly below the switch panel

**Comment by DeeTaylor87** [comment]
Done

**Comment by DeeTaylor87** [comment]
This picture shows the anchor switch. The red button turns it off. When you push the red button, you will see (if you look very very closely) that a little black arm drops down on the starboard side of the red button. This is the switch disengaging. They used to make that little arm a yellow colour which was easy to see but now they make it a black colour which is particularly difficult to see. Anyway, the little arm can either be OFF (when the arm drops down out of alignment) or ON when you push the little arm back up so it aligns nicely horizontally next to the red button.
![anchor switch](https://user-images.githubusercontent.com/30706096/30001278-82235032-90cc-11e7-9e02-317c4fdea9ca.jpg)
See also issue 117
