### ISSUE TITLE
Get Dinghy and outboard back

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#108]
Greg Hall's Dad's garage
timing: July

**Comment by smr547** [comment]
Greg Hall has offered to assist with this. I've asked him to setup a GitHub account so we can discuss issues. 

Greg advised me today that he thinks the Dinghy should be replace. @mrmrmartin reminded me that is was a recent decision of the committee to make do with the existing Dinghy while we investigate other options.

**Comment by smr547** [comment]
see also #197  -- close #197 as soon as dinghy is back

**Comment by smr547** [comment]
QServices to quote on attachment points on N3 -- Steven to organise tomorrow

**Comment by DeeTaylor87** [comment]
Greg Hall bringing dinghy  and motor down in his trailer on Sat Morning.  He will need to visit storage shed to get pump to inflate.

**Comment by smr547** [comment]
Excellent. Please encourage him to sign up on github if you can. Maybe he's not keen to do computer stuff?

**Comment by DeeTaylor87** [comment]
The dinghy is in the storage shed at Quays. Greg still has the outboard.

**Comment by smr547** [comment]
Paddles and thwart are missing -- @DeeTaylor87 please as Greg if he has these. Please ask him if he has the storm sails too.

**Comment by DeeTaylor87** [comment]
Please read above commment!!!!! LOL

**Comment by DeeTaylor87** [comment]
I know I commmented on this one before - not sure what happened to comment. Greg definitely has the paddles.  He does not have the storm sails

**Comment by DeeTaylor87** [comment]
What is a 'thwart'?

**Comment by DeeTaylor87** [comment]
Outboard is in the store.
We will need to pick up the dinghy from Quays and take it to either the store or RPAYC.  Not sure if Greg is taking care of that when he moves the boat to RPAYC.

**Comment by smr547** [comment]
The thwat is the seat that goes between the inflatable sides. Learner that last week. 😀

**Comment by DeeTaylor87** [comment]
The story continues at #197
