### ISSUE TITLE
Emergency bypass switch for engine starter

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#109]
Switch to join main batteries to starter battery in case of starter battery failure

**Comment by smr547** [comment]
BME are quoting on this

**Comment by smr547** [comment]
Hi Dan,

I'm looking after Namadgi 3 maintenance issues while Jack Hayden and Dave
Holt are overseas.

Thank you for the quote to install the bypass switch for the starter /
house batteries. I'm consulting with our management committee at the moment
and hope to have an answer for you by COB.

Later in the day, when convenient, could you please give me a call on the
number below? I'd like to get a progress update from you and also discuss


   1. float switch for bilge pump
   2. circuit diagram
   3. timing for main engine service by Douglas Marine.





kind regards,
Steven

-- 
*Steven Ring*
Software Engineer
BSc MIT (ANU)
m: 0417 495 268

**Comment by smr547** [comment]
BME quote Q002221 for $969 accepted today. The work will be completed by tomorrow.

@DeeTaylor87 @delcosta @jphayden  please note.

**Comment by DeeTaylor87** [comment]
Chris from BME is installing the emergency bypass switch just inside the companionway stairs. It will enable us to use the house batteries to start the engine in the event of a problem with the starter batteries.    The new system that replaces the diode splitter will be helpful because it will charge our batteries in series (rather then all at once) and it will reduce the voltage drop that is characteristic of diode splitters. This will be particularly helpful  when we are charging the bow thruster batteries because the cable distance to those batteries means that it is already being affected by voltage drop. The new system will be more efficient.

**Comment by DeeTaylor87** [comment]
Discussed with Chris from BME. He explained how the Voltage sensitive relay he installed to replace the diode splitter will help us. This device will charge the batteries in series. First it charges the house batteries, then when the voltage returns to an acceptable level (13.2V) it switched to engage the engine starter. Then when that returns to 13.2V, it switches to the Bow Thruster and charges it. It then keeps all batteries at that Voltage until the engine shuts down. He is also putting in an emergency bypass to run the starter motor off the house batteries in case of emergency.

**Comment by jphayden** [comment]
Not sure about this-  it should charge the starter battery first - we will have to check with them

**Comment by DeeTaylor87** [comment]
Decision made to remain with BME's system of charging the house batteries first, then the starter battery and then the bow thruster battery.  The house batteries should not take long to charge and then it will go to the next priority. If, for some emergency reason we want the batteries to charge at the same time, we can flick the parallel switch and all batteries on board will be charged in parallel. This is the emergency parallel switch.  It is found next to the starter batteries in the engine bay.
![emergency parallel switch](https://user-images.githubusercontent.com/30706096/29953846-c6fe696a-8f16-11e7-9b4c-330d03d57d1a.jpg)

**Comment by DeeTaylor87** [comment]
Installed.
