### ISSUE TITLE
Contract Cat. 1 Improvements...checked at acceptance

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#110]
Dee's list from the Blue Book
who: Paul Mcdonald

**Comment by DeeTaylor87** [comment]
@paulmc9999 Can I close this?

**Comment by DeeTaylor87** [comment]
@jphayden @paulmc9999 I imagine this should be closed. Can you confirm?

**Comment by jphayden** [comment]
Yes  - we believe they met the contract requirements

**Comment by DeeTaylor87** [comment]
BRAVO!!!!

**Comment by paulmc9999** [comment]
Yes, I think it should be closed.

On 7 Sep. 2017 7:57 pm, Dee Taylor <notifications@github.com> wrote:

@jphayden<https://github.com/jphayden> @paulmc9999<https://github.com/paulmc9999> I imagine this should be closed. Can you confirm?
