### ISSUE TITLE
Diagram of switch matrix needs to be laminate and placed near switch panel

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#116]
who: - at least for familiarisation

**Comment by DeeTaylor87** [comment]
![image](https://user-images.githubusercontent.com/30706096/29552553-340dc870-875b-11e7-9422-9f596e28027d.png)

I think I will just cut a little off one side and laminate this if we still want it.

**Comment by smr547** [comment]
Nice. I like it. We could have used it last weekend!!  What do you think @GarthBrice?

**Comment by GarthBrice** [comment]
Seems like a good idea to me

**Comment by DeeTaylor87** [comment]
I printed it and laminated it today.

**Comment by DeeTaylor87** [comment]
Sign is up. Looks good

**Comment by DeeTaylor87** [comment]
![sign 12v](https://user-images.githubusercontent.com/30706096/30001691-6deaa99c-90d8-11e7-986f-c67a947d139e.jpg)
