### ISSUE TITLE
Label the anchor circuit breaker behind cushion below switch panel

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#117]

**Comment by DeeTaylor87** [comment]
This picture shows the anchor switch.  The red button turns it off.  When you push the red button, you will see (if you look very very closely) that a little black arm drops down on the starboard side of the red button. This is the switch disengaging. They used to make that little arm a yellow colour which was easy to see but now they make it a black colour which is particularly difficult to see.  Anyway, the little arm can either be off (when the arm drops down out of alignment) or on when you push the little arm back up so it aligns nicely horizontally next to the red button.
![anchor switch](https://user-images.githubusercontent.com/30706096/29953599-fc19d302-8f14-11e7-8720-2b3cbef88616.jpg)

**Comment by DeeTaylor87** [comment]
Label has been put above the anchor circuit breaker.
