### ISSUE TITLE
Delete GAS switch on switch panel

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#120]
— gas detector should be “on” when the 12V power is “on”

**Comment by DeeTaylor87** [comment]
Should I get a quote? Perhaps quote needed while other electrical work is being done?

**Comment by smr547** [comment]
Let's leave this one to Jack (@jphayden) and Bill -- They are dealing with BME on other matters and they could do the work . I've put a "electric" label on the issue so they will see it.

**Comment by DeeTaylor87** [comment]
Do not 'delete' the switch.  All we need to do is to label it and SOP it that we always leave the gas switch on the 12Volt panel ON all the time!   (So it automatically comes on as soon as you turn on the 12V panel.

This is NOT a professional job.

**Comment by DeeTaylor87** [comment]
As soon as the SOPs are ameneded, this item can be closed.

**Comment by smr547** [comment]
I disagree. 

I believe that the gas detector has the ability to sense gas and raise an audible alarm as well as turning off the gas supply. Given this "alarm" function, there should be no opportunity for the Gas detector to be turned off (accidentally or otherwise) . While ever the boat power is "on" the gas detector should be "on".

Happy to let the committee decide this on.

**Comment by jphayden** [comment]
Happy for committee to decide .  Whether you have a switch or not,  another  idea might be to hotwire the gas detector to the 12 V system  so it is always on (via a switch or not) - currently it is only on wihen  the 12 V power is switched on

**Comment by smr547** [comment]
That's an even better idea -- but might flatten the battery if we are on a mooring. Will discuss in committee

**Comment by smr547** [comment]
Committee decision to delete this switch on 28/7 meeting @jphayden to request BME to do work

**Comment by jphayden** [comment]
Daniel has advised that they normally have the gas detector unit on a 24 hour circuit so it will operate even when the 12v power is turned off
Comments please

**Comment by smr547** [comment]
Sounds good to me -- Does that mean the gas detector is on 24x7 or does it mean that it is on for 24 hours after leaving the boat? If 24x7 how long will the battery support the detector before it goes flat (I suspect a very long time :-)

**Comment by jphayden** [comment]
It should mean that the gas detector is on 24x7 I also think the battery should last a very long time and of course, in a berth with power, the battery is always charged

**Comment by jphayden** [comment]
I have asked Donato to disconnect the gas switch and to set it up on a 24 hour circuit as discussed above

**Comment by jphayden** [comment]
That's Daniel, BME, not Donato from Shakesphere

**Comment by jphayden** [comment]
small job - I have asked Dan to do it

**Comment by DeeTaylor87** [comment]
The label on the gas switch on the 12V control panel has been removed.  The gas detector is wired 24/7
