### ISSUE TITLE
Bungs required for all sea cocks — attached with cord

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#121]

**Comment by DeeTaylor87** [comment]
We have attached bungs to heads and galley cocks. Large cocks for wastewater and seaccock willl require rubber bungs.

**Comment by DeeTaylor87** [comment]
I picked up two more large rubber bungs today. So we will have large rubber bung for forward head, large rubber bung for starboard aft head and large rubber bung for underfloor storage just outside port aft head next to companionway. I think this is enough bungs
