### ISSUE TITLE
Update arrival/departure SOPS to leave engine cooling inlet OPEN at all times, include inspection only

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#124]

**Comment by jphayden** [comment]
Spoke to Volvo Penta technician at boat she - he recommended closing it on leaving the boat .
It would be interesting to see what Shane says .

**Comment by smr547** [comment]
I'll ask Shane tomorrow or Friday. This is an important question. See also comment on #127 regarding regular checking of saildrive oil.

**Comment by smr547** [comment]
Shane also provided advice on sail drive oil inspection -- see #127

**Comment by smr547** [comment]
@jphayden please discuss with Shane to get clarification of what we must do.

**Comment by mrmrmartin** [comment]
I will ask Dave and if he is in agreement we can update SOP 1 and 2 and finalise this one
