### ISSUE TITLE
Saildrive oil filler is cross threaded

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#126]
Replace at 40hr service

**Comment by smr547** [comment]
Shane from Douglas marine will fix this week when he does engine service.

Shane stressed that we should continue to check the saildrive oil each time the engine is checked. Look out for milky oil (water content) or a drop in oil level indicating a leaking seal. 

Routine checking may help avoid expensive damage to saildrive. He said: It's an $8k sail drive. Who cares if a few dip sticks get cross threaded!! :D

**Comment by smr547** [comment]
Will be fixed on Friday as part of engine service

**Comment by DeeTaylor87** [comment]
Fixed so closing
