### ISSUE TITLE
Engine check SOP should DISCOURAGE oil check in sail drive

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#127]
Risk of cross threading too high
who:  Check with Douglas Marine how often this should be checked

**Comment by smr547** [comment]
I spoke to Shane from Douglass marine. His advice is quite clear. "Check the sail drive each time you do an engine check. Look for low oil level or milky oil (indicating water ingress). Attend to problems immediately".

SOP should require saildrive lubricant check at each engine check.

Closing this item.

**Comment by jphayden** [comment]
Volvo penta tech at boatshow also said the same - ie check the saildrive oil each time you do an engine check. Obviously be careful in replacing plug. Perhaps a caution in the SOP
I am happy to do that  then close the issue
