### ISSUE TITLE
Mount fire blanket near stove

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#129]

**Comment by DeeTaylor87** [comment]
Note Cat One Requirement

A fire   blanket adjacent to every cooking device with an open flame which should be   used in the first instance on cooking fat fires.
--

**Comment by DeeTaylor87** [comment]
Note this is a duplicate (kind of...) of issue 65

**Comment by DeeTaylor87** [comment]
As per issue 65, it seems we already have this. Where is it? We can put it up this weekend if someone can bring it to the boat. 
I'll close 65.

**Comment by DeeTaylor87** [comment]
It has been mounted with velcro in the galley
