### ISSUE TITLE
Fire extinguisher in starboard aft cabin needs to be mounted - currently loose

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#130]

**Comment by DeeTaylor87** [comment]
Note the Cat One requirements

4.04 | Where there is any form of   auxiliary engine or naked flame, fire extinguishers readily accessible in   suitable and different parts of the yacht shall be provided as follows:
-- | --
4.04.1 | At least two, of a minimum   10B(E) rating each of dry powder or equivalent
4.04.3 | From 1 July 2021 all fire   extinguishers will be of a minimum rating of 1A:10B(E).


Notes:   1. More than two, or higher rating extinguishers may be required depending   upon the size and layout of the boat. 2. Fire extinguishers are recommended   to be inspected at least every six months. All extinguishers other than   carbon dioxide have a pressure gauge indicating their state of charge, and a   security seal on the trigger. They should be free of corrosion, and recharged   if the seal is broken or the gauge is not in the green sector of the scale.   The nozzle should be checked to ensure that it is clear. A dry chemical   extinguisher should be taken from its bracket and shaken to prevent the   powder inside from compacting. A carbon dioxide extinguisher needs to be   checked by weight and recharged if there has been a loss of more than 10 per   cent of the net weight. 3. A more thorough check by a competent person is   recommended to be carried out annually and every few years when an   extinguisher requires a discharge, refill, pressure test or replacement.
--

**Comment by DeeTaylor87** [comment]
Check cupboard in port cupboard where the other extinguisher is mounted. If we can match them approximately, it would be good.

**Comment by smr547** [comment]
Good idea. I've put this on the list for [our first working party](https://github.com/CanberraOceanRacingClub/namadgi3/projects/1) -- @Delorco is organising it.

**Comment by DeeTaylor87** [comment]
Further note - there is a fire extinguisher already mounted in each of the aft cabins. The port cabin fire extinguisher is mounted in the cupboard under the little seat. The starboard aft cabin has a fire extinguisher mounted under the bunk (there is quite a bit of space in front of the fuel tank there). So the extra extinguisher will be the second in that cabin. Is that required?

**Comment by DeeTaylor87** [comment]
Mounted the fire extinguisher on the back of the fridge cabinet so you can see it as soon as you enter the boat.
