### ISSUE TITLE
Install plastic spacer in anchor well sump to lift chain out of water

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#132]

**Comment by smr547** [comment]
Plastic spacer -- do on a work-party weekend

**Comment by DeeTaylor87** [comment]
![image](https://user-images.githubusercontent.com/30706096/29059597-b0c22152-7c59-11e7-9d6d-a43168667e0f.png)
Road Tech Marine have two sizes Width 650(W) x 250(D) x 38(L)mm for $149 
and Width 480(W) x 180(D) x 30(L)mm for $99.95

Is this what we are after?

**Comment by DeeTaylor87** [comment]
Whitworths have the small version only in their online catalogue https://www.whitworths.com.au/main_itemdetail.asp?cat=148&item=624&intAbsolutePage=1

**Comment by smr547** [comment]
Hi Dee,
I'm sorry I should have provided more detail and I think we will have to make our own. The area in the chain locker where water accumulates is right up in the forpeak just below the drain holes. The area is not vary big ... maybe 200mm x 200mm x 300mm deep (if that) -- so its about the size of a small milk carton.  I'll get a photo and some dimensions next weekend.

I suggested to Sam that we simply fill it with epoxy but he thought it was there to act as a sump to prevent the drain holes from blocking.

cheers
Steven
