### ISSUE TITLE
A purple line is fouling the anchor as it is retrieved

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#134]

**Comment by smr547** [comment]
@peterottesen will have an opinion on this

**Comment by mrmrmartin** [comment]
I will ask David if it was a problem in the latest trip and if there were any other problems with the anchoring procedures

**Comment by smr547** [comment]
Hi everyone. This was a very minor issue. I think it is associated with a code zero tack line that runs past the anchor on the starboard side. 

I suggest you close the item for now and next time I'm on N3 I'll have a look at it.

**Comment by mrmrmartin** [comment]
Hi Steven


Sorry to bombard you with these GitHub items just working my way through them.

No 128 mentions twisting the oil stick before checking the oil level.

Do we have a SOP3 for the engine maintenance or do we need to edit SOP 1 or 2 to cover this item?.

cheers

________________________________

**Comment by mrmrmartin** [comment]
Stephen or I will check next time we are on the boat - I will close this one
