### ISSUE TITLE
SOP required for furling and unfurling the Bimini

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#135]
see Dee’s email

**Comment by DeeTaylor87** [comment]
We don't really need it. It just takes a bit of practice (and luck if it is the first go...)

**Comment by smr547** [comment]
Thanks Dee. My familiarisation group was definitely challenged by the Bimini -- We all thought a video was required :D -- I'll leave this one open for futher discussion.
