### ISSUE TITLE
Install life ring, life sling, danbouy

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#139]

**Comment by DeeTaylor87** [comment]
Check under the saloon table seats on the starboard side. There were a few things that were brought back from the store room when Rob, Wayne and I visited last week. Anything we brought back from the storeroom was left in the storage cell there. I think there may have been a safety item or two amongst it.

**Comment by DeeTaylor87** [comment]
Note Cat One Requirements:

4.21.1 | The following shall be provided   within reach of the helmsman and ready for instant use:  (a) A lifebuoy with a self-igniting light   and a drogue or a lifesling with a self-igniting light and without a drogue.  (b) In addition to (a) above, one lifebuoy   within reach of the helmsman and ready for instant use, equipped with: (i) A   whistle, a drogue, a self-igniting light and (ii) A pole and flag. The pole   shall be either permanently extended or be capable of being fully   automatically extended (not extendable by hand) in less than 20 seconds. It   shall be attached to the lifebuoy with 3 m (10 ft) of floating line and is to   be of a length and so ballasted that the flag will fly at least 1.8 m (6 ft)   off the water.
-- | --
4.21.2 | When at least two lifebuoys   (and/or lifeslings) are carried, at least one of them shall depend entirely   on permanent (e.g. foam) buoyancy.
4.21.3 | Each inflatable lifebuoy and any   automatic device (e.g.     pole and flag extended by compressed gas) shall be tested and serviced at   intervals in accordance with its manufacturer's instructions.
4.21.4 | Each lifebuoy or lifesling shall   be fitted with marine grade retroreflective material.
4.21.5 | The colour of a lifebuoy or   lifesling, other than lines, fittings and retroreflective material shall be a   safety colour in the yellow - red range.

**Comment by peterottesen** [comment]
I think all these items are onboard.  Starboard locker for except maybe the heaving line which should be in the console

**Comment by smr547** [comment]
I think I saw them on the weekend -- but they need to be checked and tested if working. An audit is required

**Comment by DeeTaylor87** [comment]
They have been put up and then put away in the large central cockpit locker
