### ISSUE TITLE
Install spare gas bottle

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#140]

**Comment by DeeTaylor87** [comment]
Note Cat One Requirements
3.17.5 (a) | Disposable   gas cooking canisters used inside the boat must be no more than 225 gram   capacity.
3.17.6 | Gas   bottles, cylinders and reserve canisters shall be contained in separate   ventilated and self-draining compartments where vapour can only escape   overboard.

**Comment by smr547** [comment]
Is the aft cockpit cabinet under the floor "ventilated and self draining"?

**Comment by DeeTaylor87** [comment]
I'll check on Wednesday!

**Comment by DeeTaylor87** [comment]
I think this issue may duplicate other extend gas storage compartment? Not sure where you would put spare. I looked at it with Darren Skinner shipwright today. Getting quotes to double storage capacity of compartment

**Comment by smr547** [comment]
Hi Dee,

You are right. This duplicates issue #52 -- I'll close this one but make reference to it in #52 so we don't lose your comments. 
many thanks,
Steven
