### ISSUE TITLE
SOP for battery charging system

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#143]

**Comment by DeeTaylor87** [comment]
Decision made to remain with BME's system of charging the house batteries first, then the starter battery and then the bow thruster battery. The house batteries should not take long to charge and then it will go to the next priority. If, for some emergency reason we want the batteries to charge at the same time, we can flick the parallel switch and all batteries on board will be charged in parallel. This is the emergency parallel switch. It is found next to the starter batteries in the engine bay.
![emergency parallel switch](https://user-images.githubusercontent.com/30706096/29953930-48fdb9a2-8f17-11e7-9389-dd1bf38dfabe.jpg)
