### ISSUE TITLE
SOP for VHF radio

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#149]

**Comment by DeeTaylor87** [comment]
Correspondence from Michael 1st September 2017
Hi guys
Here is our new MMSI number 503058550 for Namadgi 3 provided by AMSA.
Not sure of the procedure but I believe this number has to be programmed into our radio before the AIS for Namadgi 3 is sent to other vessels.
Richard can you inform us how this is done?
Richard has volunteered to organise the SOP for the radio but we should try and get the radio programmed before we move Namadgi 3 to Batemans Bay.
cheers
@mrmrmartin
