### ISSUE TITLE
Lanyard on windlass remote

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#151]

**Comment by paulmc9999** [comment]
Is a lanyard necessary? Are we not going to leave the windlass remote attached in the forward locker?

**Comment by smr547** [comment]
Good question -- we will have a look this weekend and advise.

**Comment by DeeTaylor87** [comment]
We can't put a lanyard on the remote becuase it only works when it is screwed in to the connection at the top
