### ISSUE TITLE
S/Steel plate to protect bow from anchor damage

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#163]

**Comment by DeeTaylor87** [comment]
I have requested a quote from David Skinner Shipwright at Quays.

**Comment by smr547** [comment]
Perfect, thanks Dee

Soon I will make the CORC maintenance system a private repository (members only) so that we can put Quotes and other things up for discussion amongst the maintenance team. @pjwain @jphayden @peterottesen @delorco and other committee members will be interested in how that works.
