### ISSUE TITLE
SOP to include NO WHEELED BAGS ON BOAT

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#166]
(to include duffel bags with wheels)

**Comment by pjwain** [comment]
This is a only a suggestion at this stage, and should be agreed by the committee, bearing in mind that some of the older members are unable to carry their kit bags very far, and do require wheels. We should warn members and guests to be careful when carrying anything through the yacht, not just bags. Another suggestion is to place a large non-slip mat at the base of the companionway to prevent tether hooks from damaging the floor when crew are going on or off watch.

**Comment by smr547** [comment]
Good point. I'll refer to committee

**Comment by SimonRD** [comment]
I dnt think this is practical. What are our alternatives to save the damage caused by not only wheels but any luggage with hard bits (eg locks). Somehow we need to instill a sense of responsibility in skippers and crew. Mayb a big sign at the top of the companionway?
