### ISSUE TITLE
Latches on “nav station” extendible seat are a safety hazard

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#168]
sharp edges

**Comment by DeeTaylor87** [comment]
I think there must have been something forgotton on installation of these. It looks like there is a rubber cap missing or something. Is this something that can be raised with Ensign?

**Comment by DeeTaylor87** [comment]
Sam looked at it and has solution. Needs plastic protectors.  Will be bought tomorrow.
