### ISSUE TITLE
Bent stanchion — starboard side mid ships - happened during familiarisation

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#175]

**Comment by delcosta** [comment]
This should be professionally done

**Comment by DeeTaylor87** [comment]
Looking at the stanchion and I can't see how it is bent. It is a little wobblier than the other stanchions.  May just need the bolt at the base of it tightened?

**Comment by pjwain** [comment]
Maybe you're right. When I was on the yacht, viewing the stanchion from the port side of the yacht, it was leaning aft, but there was no obvious kink or bend.

**Comment by smr547** [comment]
Garth, @peterottesen and I inspected it on the weekend. It is a little loose but I could see no bend. Perhaps we could retighten at the working bee?

**Comment by smr547** [comment]
Spoke to Kate Douglass today. Asked her to supply the stanchion to us and we will keep it as a spare. The "damaged" stanchioned will be retightened at the working bee.

**Comment by DeeTaylor87** [comment]
We looked at it during Working bee.  It seemed to be tight enough.
