### ISSUE TITLE
Anchor locker hatch damaged as if it has been dropped ashore

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#176]

**Comment by pjwain** [comment]
This is a warranty item. A picture of the edge of theanchor hatch cover is attached.
![anchor hatch](https://user-images.githubusercontent.com/30762047/29008662-34c5a67e-7b5e-11e7-8f3b-984274b8d886.JPG)

**Comment by delcosta** [comment]
Can we put a restraint strap to the panel so it doesn't drop too far.

**Comment by pjwain** [comment]
It doesn't need a restraint. It was broken before we took delivery. It needs repairing or replacing.

**Comment by jphayden** [comment]
I am checking with Kate on this, It was to be repaired at the RPA or a replacement organised.

**Comment by DeeTaylor87** [comment]
Has been fixed
