### ISSUE TITLE
Rubbish Bag 

### ISSUE THREAD

**Issue by DeeTaylor87** [CanberraOceanRacingClub/namadgi3#178]
https://www.deckhardware.com.au/canvas/storage/

Saw these advertised and it made me think of the one we had on the old boat.

**Comment by peterottesen** [comment]
We have large bag fron the Elan which I assume we can still use.  It was designed to attached to the pushpit but could hung in the forward deck locker of the new boat??

**Comment by smr547** [comment]
I guess it's in the storage shed??

**Comment by delcosta** [comment]
Agreed 
We use Elan Bag for now
Item closed once bag is on board

**Comment by smr547** [comment]
Great idea -- Welcome to the maintenance management system Sam!!

**Comment by delcosta** [comment]
Well Than you very much Steve

Regards,
Sam DeLorenzo
President
Canberra Ocean Racing Club
M: +61 411 165 835
A: PO Box 646, Woden ACT 2606, Australia

IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail.

**Comment by DeeTaylor87** [comment]
Not in the store. Is it still on Namadgi 2? Who has it?

**Comment by DeeTaylor87** [comment]
Jack has rubbish bag.

**Comment by DeeTaylor87** [comment]
Rubbish bag on board in the central cockpit locker
