### ISSUE TITLE
Charts and equipment for paper navigation to Batemans Bay

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#181]
All relevant charts and navigation instruments need to be transferred from storage to the boat to support paper chart-based coastal navigation for the passage from Pittwater to Batemans Bay

**Comment by DeeTaylor87** [comment]
Peter Morris is bringing them to the last drinks this week

**Comment by DeeTaylor87** [comment]
Jack has them

**Comment by DeeTaylor87** [comment]
Charts on board now. The Bateman's Bay charts are under the mattress in the starboard aft cabin. The charts for Pittwater are in the chart table forward side.

**Comment by mrmrmartin** [comment]
I have picked up 4 new charts from Peter Morris relating to Batemans Bay, Jervis Bay, Twofold Bay and Port Kembla and Wolloongong
