### ISSUE TITLE
Fit drying rack to RHS of sink

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#184]
@peterottesen has measured this as 

40cm x 45cm maximum dimension
Allowing dishes to be laid flat so they can drain

**Comment by DeeTaylor87** [comment]
I found it easiest to wash in the small sink (you don't need much water that way and most things fit) and drain them in the large sink.

**Comment by DeeTaylor87** [comment]
There is a small plastic rack from the old boat that is under the sink.
