### ISSUE TITLE
Shelves in the quarter berths may present a problem when at sea

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#185]
The shelves are low to the bed and protrude a long way. It will be very awkward to sleep against them when on a tack.

**Comment by GarthBrice** [comment]
A simple solution may be to buy four extra pillows (two for each side of the boat) and stuff them into the space.
You will need to take this into consideration when working out the split for the lee cloths

**Comment by smr547** [comment]
That's a good point Garth. @DeeTaylor87 will be interested in your comment. She is arranging the installation of the Lee cloths and final positioning will be determined this weekend.
