### ISSUE TITLE
Lazarette locker combination locks missing -- please replace

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#186]
What happened to them? Any theories? @DeeTaylor87 @jphayden  will be interested

**Comment by DeeTaylor87** [comment]
We now have two new locks. I will take them over to the boat on Friday.

**Comment by smr547** [comment]
Thanks Dee -- You do know what the combinations needs to be set to? 
 As you are now an "Owner" of this repository, please feel free to close this issue (and others) when you feel they are finalised 
BTW: @DaveHolt is also an owner
