### ISSUE TITLE
Install float switch on electric bilge pump

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#189]
Currently the electric bilge pump only operates when it is switched on at the switch panel -- and then, it operates continuously.

Prudence would demand that

1. the bilge pump be left on at all times and 
1. operates only when there is water to be pumped from the bilge

This will required the installation of a float switch and possibly some rewiring of the swithchboard

**Comment by smr547** [comment]
Should we also have BME do this while it is in their shop this week?  In addition to the float switch we would need a new switch on the panel -- one that gives "on, off and manual override (on)". The latter bypasses the float switch and operates the motor.

What does the committee think @delcosta @pjwain @DaveHolt @mrmrmartin @simonRD ??

@jphayden might have a view ... I'll email Bill Leslie separately.

**Comment by jphayden** [comment]
Hi Steven
have to reply directly .Tim the quays marina electrician told me that he had done it - could someone check with BME  to see if it is installed That is the float switch.
Agree with the second requirement

Regards

Jack

**Comment by DeeTaylor87** [comment]
This is the bilge pump we have installed - Whale Supersub Pump 500
https://www.whalepumps.com/marine/siteFiles/resources/docs/resource-library/super_sub_jan2010.pdf

**Comment by DeeTaylor87** [comment]
I think it is probably this float switch
![image](https://user-images.githubusercontent.com/30706096/29594955-c912b7b8-87f7-11e7-8fb6-97574d387507.png)

**Comment by jphayden** [comment]
Looks  like what it is to me but I agree with Steven we still need a manual bilge switch .  Could BME have a look at it ,

**Comment by DeeTaylor87** [comment]
Who is the liaison person for this?  If it is you, Jack, would you like me to call them?

**Comment by DeeTaylor87** [comment]
I have them on the phone now

**Comment by jphayden** [comment]
Also an associated query   I am not aware that we were issued a bill for the installation of the float valve nor the anchor winch circuit breaker - both of which were installed at the Quays

**Comment by DeeTaylor87** [comment]
The alternator belt on the engine has been chewed up (belt tension probably not tight enough).

Bilge Work quote being sent to me right now. I am just about to contact Bavaria regarding belt - needs to be attended to now. 

Need to know if going ahead with other quote regarding batteries.

**Comment by smr547** [comment]
Thanks for calling Dan. As it happens we've both been talking to him.
We will go ahead with the bilge pump and the battery bypass.
I'll call him now to give him the go ahead
I'll speak to Douglass Marine about the pulley belt problem
cheers
Steven

**Comment by DeeTaylor87** [comment]
Thanks Steven - you are doing an enormous amount of ringing, typing, organising stuff on top of a full time job.  Many many thanks for such hard work (and maintaining your rosy demeanour flawlessly!)

**Comment by smr547** [comment]
BME quote Q002227 for $266 accepted -- work will be done today.

**Comment by jphayden** [comment]
I take it that BME have confirmed that there is currently no bilge pump float valve.
Dee, where did that picture come from.
Are we getting the manual override 
Dee, Steven - great work

**Comment by DeeTaylor87** [comment]
The picture was taken on Monday before the boat went to BME.  I was looking at the storage bays and noticed the pump, so thought I would take a couple of pictures so I could work out what model of pump we had.  What work had Tim been asked to complete?

**Comment by smr547** [comment]
When @GarthBrice and @peterottesen tested it last weekend, the bilge pump, when switched on, would run continuously with no water in the bilge. Inspection suggested no float valve.

Dan from BME quoted and will install the float valve tomorrow -- see comments above.

This will include a three position switch: on/off/manual-on

Dee is doing a fantastic Job. She will be a great help to @DaveHolt when he gets back. I'll be glad to hand this job back to them :D

**Comment by jphayden** [comment]
Thanks Steven
For Dee:
Tim at the Quays had been asked to install a float valve on the bilge pump

**Comment by DeeTaylor87** [comment]
Dan has been asked to check that it will operate 24/7 and install an alarm.

**Comment by DeeTaylor87** [comment]
Float switch was already there and already wired to run 24/7.  The float switch can be tested by putting your hand in to touch the side of the switch that is facing away from you when you look at it.  On that side, you will feel a little lever that is very sensitive and easy to raise and depress. When you raise the lever, the bilge pump is activated.  The new panel that is being installed by BME is being put into the cabinet where the main 240 switch is.  The panel provides an alarm that will sound whenever the bilge pump is activated by the float switch. If it is sounding when you cannot see water in the bilge where the float switch is, then it is activating unnecessarily (since it is wired to trip only when the float switch is tripped).  There needs to be a considerable amount of water in the bilge compartment where the float switch is in order for the switch to trip, so it will be clearly visible if that is the case.
