### ISSUE TITLE
Consider acquiring AIS man overboard beacons for Namadgi

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#190]
This suggestion from Garth Brice based on his experience with  a similar system used on SV Trilogy.

The AIS man overboard beacons operate on VHF (just like normal AIS)-- one is attached to each PFD. 

The beacon on the lifejacket, once activated, will send an AIS identity and position message to Namadgi 3 (and all other vessels within line of sight. This will allow the mother ship (N3 in our case), and all other AIS capable vessels in the area, to see the distress signal and assist in the Search and Rescue operation.

**Comment by DaveHolt** [comment]
There is a good comparison of AIS MOB devices at: http://www.yachtingworld.com/features/tested-ais-mob-devices-help-your-crew-to-save-your-life-69914

A factor to remember is that their range is only about 3.5 nm in good conditions. 3 mins sailing at 6 knots.

**Comment by GarthBrice** [comment]
Dave, I think you meant to say 30 minutes sailing at 6 knots which should be ample time to notice the MOB. If not than N3 could retrace her track to get back into the range of the AIS MOB device and recover the MOB in a relatively short time.
Trilogy has the Kannard Safelink R10 AIS MOB devices

**Comment by DaveHolt** [comment]
Sorry 30 you're correct. The danger of trying to reply on an iPhone screen.

**Comment by smr547** [comment]
AIS man-overboard beacons have been purchased and will be despatched to Coral Seas Marina in the near future. Michelle will advise when they have been shipped and @peterottesen will advise the Marina desk and ask our Guardian (Peter Wilson) to put them on board. 

Keeping this issue open until final delivery is made.

**Comment by smr547** [comment]
Beacons have been delivered to the N3 -- closing this issue

**Comment by smr547** [comment]
Noted battery expiry date for these units is March 2029
