### ISSUE TITLE
Get an electrical circuit diagram for the boat 

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#193]
@jphayden has been working with Ensign trying to get a detailed circuit diagram for Namadgi 3 (both 240V and 12V). Unfortunately without much luck.

It is critical that we have this diagram. I will ask BME for a price on producing a circuit diagram.

@delcosta @DaveHolt will be interested in this.

**Comment by smr547** [comment]
Today I spoke to Dan from BME and asked him to give a quote to prepare 12V and 240V circuit diagrams for the boat

**Comment by DeeTaylor87** [comment]
Communication on Whats App with Daniel from BME 28th August:
Hi Daniel, Jack Hayden CORC here. The matters we wanted to address are: Light in the engine bay, provision of fuse kit, check the battery monitor, check the electrical cable on the forward keel bolt, Isolation transformer is noisy, Provision of 12V and 240V circuit diagrams

**Comment by DeeTaylor87** [comment]
Chris the electrician from BME has made notes as he has been working on the boat. He will provide a rough sketch of the system.  A full engineered drawing can be provided, but it is not really needed because the next time someone works on the boat it will become outdated anyway. Better to go with a general outline which will be more useful for future sparkies.

**Comment by DeeTaylor87** [comment]
Electrician has provided a rough sketch.  It is rough, so I will copy it up neatly and post on here soon.

**Comment by smr547** [comment]
Hi Dee, thanks for doing that. Please scan original too -- just for reference

**Comment by DeeTaylor87** [comment]
Will do - actually I have it saved already. I will email to anyone interested. I'll send it to you and Jack for starters.  I thought when I have a few moments I could transcribe it neatly but really, if someone else is keen to take this task on, by all means let me know!
