### ISSUE TITLE
Provision supplies for engine service at sea

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#195]
Oil, fuel and air filter spares
Sail drive oil
Engine oil
Anti-freeze coolant additive
Anything else Shane can think of

**Comment by smr547** [comment]
Hi Shane and Felicity,

It occurs to me that we have no supplies on board Namadgi 3 for engine
maintenance.

Could you please supply us with:


   1. spare Oil, fuel and air filters
   2. Sail drive oil
   3. Engine oil
   4. Anti-freeze coolant additive
   5. Anything else Shane can think of


kind regards
Steven

ref issue #195

-- 
*Steven Ring*
Software Engineer
BSc MIT (ANU)
m: 0417 495 268

**Comment by smr547** [comment]
Full set of supplies left on board by Shane during the engine service today. He advises using 15/40 oil for BOTH engine and sail drive -- 5L supplied and left on board.

@DaveHolt @jphayden @DaveHolt will be interested in this.

Closing this -- opening new item for next service? Don't know when that is -- we should consult the owner's manual

**Comment by DaveHolt** [comment]
If it's the same interval as the D2-55 we used 500 hours or yearly
