### ISSUE TITLE
Retrieve RIB and outboard motor from storage

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#197]
We need these at the boat so that QServices can quote and perform work on them (refurb, attachment to N3, etc)

@delcosta and @DeeTaylor87  please note

**Comment by DeeTaylor87** [comment]
RIB is now at Quays. Greg Hall has the motor.  Need to check if he has the paddles as well.

**Comment by DeeTaylor87** [comment]
Greg Hall has the paddles.

**Comment by DeeTaylor87** [comment]
The outboard is at the store. Does Quays need to do work on this? Has it already been arranged? Can I facilitate?

**Comment by DaveHolt** [comment]
I'm not aware of any work that needs doing to the outboard.

**Comment by jphayden** [comment]
Greg has got the outboard .
We will need to get it on board for the trip

**Comment by DeeTaylor87** [comment]
The outboard is in the back of my car. Paddles and thwart are on Namadgi 3

**Comment by jphayden** [comment]
Well done again Dee - you are a one person logistics team 😉

**Comment by smr547** [comment]
Agreed .... Awesome effort Dee!

**Comment by DeeTaylor87** [comment]
The outboard, outboard cover and RIB have been delivered to Bateman's Bay on the 11th September. Check the starboard cockpit locker for the paddles and thwart. If you can't find them there, try to the central cockpit storage bay. My bet is the starboard locker.
