### ISSUE TITLE
Manual Switch for the anchor

### ISSUE THREAD

**Issue by DeeTaylor87** [CanberraOceanRacingClub/namadgi3#199]
Concerns raised regarding ability to lower and raise the anchor if the remote is either missing or broken. Can we investigate the options if we suddently have a problem?  There is a winch however suggestion has been that we should also have a fixed switch as a backup.

**Comment by DeeTaylor87** [comment]
Discussed with Chris from BME. He explained how the Voltage sensitive relay he installed to replace the diode splitter will help us. This device will charge the batteries in series. First it charges the house batteries, then when the voltage returns to an acceptable level (13.2V) it switched to engage the engine starter. Then when that returns to 13.2V, it switches to the Bow Thruster and charges it. It then keeps all batteries at that Voltage until the engine shuts down. He is also putting in an emergency bypass to run the starter motor off the house batteries in case of emergency.

**Comment by smr547** [comment]
Closing this item -- historical
