### ISSUE TITLE
Negotiate a berth in Pittwater 

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#20]
Some weeks available at Quays
who: Simon Dunlop

**Comment by DeeTaylor87** [comment]
We need to exit Quays by 13th August. Last time I spoke to Steve (the Manager at Quays) he had not heard back from us about whether we still wanted a mooring.  Has anyone spoken to Quays since?

**Comment by DeeTaylor87** [comment]
I spoke to Dee from Quays today and informed her that we would like to move to a mooring post 13th August until our exit in early September. I told her we would update with new info as it became available.

**Comment by smr547** [comment]
Simon Dunlop has some info on this

**Comment by DeeTaylor87** [comment]
Update.  The owners never arrived with the boat on the 13th so we have remained in the berth. Dee from Quays says that she has told them that the marina will need 24hrs notice so that Namadgi can be moved, so if we are lucky, we may be in a berth for the remainder of our Sydney stay.

**Comment by smr547** [comment]
Yay, that would be good.

**Comment by DeeTaylor87** [comment]
@mrmrmartin  - Simon says you have organised a berth in Bateman's Bay?

**Comment by mrmrmartin** [comment]
yes we will be on E5.
I have spoken to the manager Daimon and he is aware that we will be coming on the weekend.
Once we have confirmed the date of arrival I will let him know.

**Comment by mrmrmartin** [comment]
Yes berth confirmed

You can close this one off please

________________________________

**Comment by smr547** [comment]
Hi @mrmrmartin. When next speaking to Damon could you please ask him about the fuel wharf? Specifically what depth do we have when accessing the fuel wharf as "astronomical low tide" (i.e. the lowest it goes)?

Also, what is N3's draft according to the manual. N3 is a B46 but is she model A or model B?

Sorry to be a pain but I'd like to get this right.

regards
Steven

**Comment by mrmrmartin** [comment]
It looks very good - a few spelling errors - someone should run a spell check over it.

**Comment by DeeTaylor87** [comment]
I think the berth on the return to Pittwater needs to be sorted. Has anyone been assigned to that job?  Shall I ring around again?
