### ISSUE TITLE
Calibration of the depth sounder

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#200]
This issue was raised for the information of future skippers of N3 and for inclusion in the appropriate SOP(s)

Last weekend @GarthBrice, @peterottesen and @smr547 tested the calibration of the depth sounder while on Namadgi 3.

We found that the Garmin chartplotter aboard N3 reported she was in 4.8m of water while we measured the actual depth at 5.1 metres. At the same time the Garmin "keel offset" parameter was found to be 0.0m

We concluded that the transducer was actually about 30cm below the surface and if the "keel offset" parameter were set to -0.30m then the Garmin instrument would read depth correctly at 5.1m -- this was tried and shown to be true. The keel offset value was returned to 0.0 and N3 now under-reports depth from surface by 0.30 -- this was considered a useful safety factor for the time being.

It was noted that it is relatively easy for the "keel offset" value to be changed by anyone at the helm (or with a wifi connected device). Without getting too dramatic, this presents a grave potential hazard for the vessel. If people play with this setting N3 could easily be run aground by an unwary member or guest.

I'd like the committee to give guidance on this issue and for its decision to be recorded in SOPs and "responsibilities of skippers" documents. 

My recommendation

* N3 always reports *depth below surface* in metres (not *clearance below keel*)
* the "keel offset" be permanently set to -0.3m
* the SOPs and "responsibility of skippers" documents alert skippers to:
  * N3 draft of 2.2m and airdraft of 21m
  * club policy to have N3 instruments always report *depth below surface*
  * check the "keel offset" when entering and leaving the boat (it must be -0.3)
  * never tamper with the keel offset value unless it is to reset it correctly to -0.3m

I don't want to start a debate about *depth* vs *clearance below keel* -- I just want the committee to adopt and promulgate a firm policy and clear instructions on this important matter. 

@DaveHolt @delcosta @pjwain @peterottesen @simonRD @mrmrmartin will be interested in this

**Comment by GarthBrice** [comment]
I agree entirely with your comments

**Comment by DaveHolt** [comment]
I agree with all of Steven's recommendations.

**Comment by DeeTaylor87** [comment]
I don't want to start a debate but I am not understanding completely I think and I need to clarify.
 If the transducer setting reads from the water line, won't that waterline change according to whether the boat is  loaded or unloaded?  That seems to be a variable measure as opposed to an absolute measure of distance below the keel?  Or are they both variable according to how much weight is on board at any time????????  If they are both variable, then the reading will never be exact because we will never have exactly the same mass on board.

**Comment by DaveHolt** [comment]
I think the laden Vs unladen draft of the boat will only vary by 2-3 cms at most. Not significant enough to be a concern. A depth below the keel reading will also vary by the same 2-3 cms.

**Comment by smr547** [comment]
I agree with Dave's comment. The change is insignificant.

Another small but important point. I'd like us to use the term ``clearance below the keel`` rather than ``depth below the keel``. ``Depth`` is defined as distance from ``surface to bottom``. We can't allow that term to be stolen for another purpose (I.e. A ``clearance``) without causing confusion. Language is everything.

**Comment by DeeTaylor87** [comment]
OK. Thanks for the education guys. I see now that the transducer is located at the bottom of the hull (not bottom of keel) anyway, so the distance below and reliability of reading remains the same regardless of whether measuring is taken from the waterline or the keel. I agree, better to have an agreed setting that remains unchanged. Perhaps the manufacturers deliberately chose 0.3m as an appropriate margin of error given that the position of the transducer and the size of the boat will mean that we will already be on top of a potentially rapidly changing topography when the transducer is overhead and able to accurately read clearance.

**Comment by smr547** [comment]
At it's meeting on 28/7 the Committee accepted these recommendations. SOPS to be updated accordingly. This item to also be addressed in the "Responsibility of Skippers" document.
