### ISSUE TITLE
Retrieve electric kettle for N3

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#201]
retrieve electric kettle for N3

**Comment by DeeTaylor87** [comment]
We are no longer serving tea for interested buyers?

**Comment by DeeTaylor87** [comment]
I retrieved the electric kettle today but it is not suitable for our boat electrics. It is rated at 1850W to 2200W.  Chris the Electrician from BME advised that we could run an 1800W kettle max.
