### ISSUE TITLE
N2 engine control lever needs lubrication 

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#202]
N2 engine control lever needs lubrication

**Comment by DeeTaylor87** [comment]
@mrmrmartin  - I think I know the perfect man for this!  I think he was a King?  Could you speak to him about another working bee?

**Comment by DeeTaylor87** [comment]
@mrmrmartin  - can you comment on this?  What did you find when you visited on the 9th September?

**Comment by mrmrmartin** [comment]
it was fine on the weekend - perhaps someone, the Lubrication King, had already don the job

________________________________
