### ISSUE TITLE
N2 sweep, dust, wipe insides

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#204]
N2 sweep, dust, wipe insides. Needs a good clean

**Comment by DeeTaylor87** [comment]
OK.  This looks like a bit of a working bee thing. Are you organising the working bee so that we can attend to N2?  We could take it for a spin while we are there to shake the cobwebs out.

**Comment by DeeTaylor87** [comment]
It looked fine on the 9th September. A really thorough clean might be done by a professional cleaner at the same time as we clean the hull - unless someone can organise a working bee.  Perhaps the committee might consider this at their next meeting?  @DaveHolt @smr547 @pjwain @peterottesen @srdunlop @delcosta
