### ISSUE TITLE
N2 hose top sides, clean bird poo

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#205]
N2 hose top sides, clean bird poo

**Comment by DeeTaylor87** [comment]
This is going to be pretty tricky without water!  How do you propose that problem be solved?  CORC is all about solutions, not problems, as you well know!

**Comment by DeeTaylor87** [comment]
I cleaned topside with a bucket of seawater and a cloth on the 9th September.  I will leave this issue open until N2 has a permanent home.
