### ISSUE TITLE
N2 scrub waterline

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#206]
N2 scrub waterline It has grown a green beard. I think the long handled scrubbing brush might be on board?

**Comment by DeeTaylor87** [comment]
Where do you think it is, Dave????  Looks like you will need to make a trip to Sydney to visit and show us how it is done.  :D

**Comment by DeeTaylor87** [comment]
Further to my last comment - I can see no images in the above text box, so I have no idea what the options for images were about when I started typing before.  I'd be interested to know if someone else could see an image there that I can't see right now. Technology can be a little problematic sometimes!

**Comment by DeeTaylor87** [comment]
I didn't see any scrubbing implement on board when I visited N2.  We will probably need to arrange some professional attention for N2 to take care of this issue. @DaveHolt  - do you have some ideas about this?
