### ISSUE TITLE
N2 flush and clean toilets

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#207]
N2 flush and clean toilets. Flush with fresh water and super bowl blue lol stuff it is onboard.

**Comment by DeeTaylor87** [comment]
Gosh. Well this is just no fun anymore!

**Comment by DeeTaylor87** [comment]
@mrmrmartin took care of this and we all thank him....  @DaveHolt  - I might leave this issue open until a more permanent solution to the care of N2 is found.
