### ISSUE TITLE
N2 flush salt water tap and sinks

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#208]
N2 flush salt water tap. It gets very smelly after no use. Also flush sinks.

**Comment by DeeTaylor87** [comment]
OK  - well it looks like another trip to N2 is required.  Who is going to be there next?  Probably Jack and I .  @jphayden  are you up for this?

**Comment by DeeTaylor87** [comment]
I tried to flush the saltwater tap but it is choked up. No water emerged. Has this happened before @DaveHolt ?

**Comment by DaveHolt** [comment]
Hi Dee,
Thanks for looking. Did you open the sea cock for the salt water tap?
Dave

**Comment by DeeTaylor87** [comment]
Well, that might have been the problem!  No - didn't think that far. Hopefully it is ok in that case.

**Comment by DeeTaylor87** [comment]
We checked the salt water tap and it was fine - just needed to open the cock..... All good. Issue can be closed.
