### ISSUE TITLE
N2 check and retrieve storm sails 

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#209]
N2 check are storm sails on board and retrieve. Note the old storm jib with a Velcro luff stays with N2

**Comment by DeeTaylor87** [comment]
We figured that the storm sails are with Simon (see issue with Storm Sails already noted - do a search on issues).  The old storm jib was brought back to Namadgi 3 I think as a precaution.  Michael has been liasing with the sales rep regarding what was taken from the boat.  @mrmrmartin  - can you comment?

**Comment by DaveHolt** [comment]
Thanks Dee,
Steven asked me to add the issues listed so I did. Not easy on an iPhone in a moving boat. Good to close them tho.

David Holt
0439 470 261
