### ISSUE TITLE
Safety audit of EPIRB and PLBs

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#211]
Check off against the AMSA registration list. Also check the battery expiry date of each item and report to maintenance officer for record

**Comment by DaveHolt** [comment]
The 8 x ACR ResQLink+ PLBs were new in March 2016. Their battery expiry dates are March 2022. I registered them with AMSA in March 2016.

**Comment by DeeTaylor87** [comment]
Who shall I assign this job to?  Dave Holt? Any ideas?

**Comment by DaveHolt** [comment]
Hi,
please can someone let me know Namadgi's NSW registration number and/or radio call sign if we have one (VNCA?).
Thanks

**Comment by DaveHolt** [comment]
Has the boat EPIRB been registered with AMSA? My account only shows me the 8 PLBs that I registered in 2016.

**Comment by DeeTaylor87** [comment]
Try Sam Hughes - it was noted on Github that the task was allocated to him
- not sure if he knows about it.....

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by DeeTaylor87** [comment]
also @mrmrmartin may be able to shed light on this

**Comment by DaveHolt** [comment]
I have attached the registration confirmation for the 8 ACR PLBs. I updated the AMSA record today to associate them with Namadgi3. 
![namadgi3 plb registrations 2016](https://user-images.githubusercontent.com/31207261/30001032-e272445a-90c4-11e7-93e8-494d0c6fba7f.png)

**Comment by DeeTaylor87** [comment]
The EPIRB has been mounted in the Bavaria. Following is the product information provided on it, and the unique identifying number allocated to it.  Registration details are yet to be confirmed.

![epirb](https://user-images.githubusercontent.com/30706096/30001114-20a34aec-90c7-11e7-9fb1-73c5359bd19f.jpg)
![epirb 2](https://user-images.githubusercontent.com/30706096/30001115-2653fb4e-90c7-11e7-9cab-8652be122f18.jpg)
![epirb 3](https://user-images.githubusercontent.com/30706096/30001119-3036d668-90c7-11e7-9a62-4a1f866ffde4.jpg)

**Comment by smr547** [comment]
@mrmmartin has registered Epirb and all PLB plus has got MMSI allocated fro N3

**Comment by smr547** [comment]
@mrmrmartin 

Hi Michael, 

Could you please post the current EPIRB registration list onto this issues. Then we might close it.

**Comment by DeeTaylor87** [comment]
Michael has posted the rego with AMSa  

50305855

**Comment by DeeTaylor87** [comment]
Confirmed that the PLBs registered are the ResQ Link ones on Namadgi 3

**Comment by smr547** [comment]
Re-opening this so we can record current registration status. 

Very important given that we are about to go offshore.

@delcosta and Paul Jones will be interested.

**Comment by delcosta** [comment]
Absolutely essential
I am not sure I can get onto it before the boat goes.
Maybe Bill might help.
We also need to get Iridium going again!!!

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603

IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail.

**Comment by smr547** [comment]
AMSA registration attached. Main EPIRB details verified. Time did not permit verifying details of all PLBs at this stage. Recommend skippers set off the ships EPIRB in the event of a MOB.

[AMSA Beacon MMSI rego (1).pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/6432043/AMSA.Beacon.MMSI.rego.1.pdf)

Closing this item

**Comment by smr547** [comment]
Hi Peter,

We were unable to complete the audit of the PLBs attached to each life
jacket at the working bee. Could I please ask you to complete this audit
when issuing life jackets to the delivery crew before you sail?

I think the fastest way to do this is when you allocate a lifejacket to
each crew member, ask them to


   1. open the jacket and locate the PLB
   2. locate the UIN (also known as HEXID) -- a 16 character identifier --
   marked on the PLB
   3. ensure that the UIN is listed on the AMSA Beacon MMSI Registration
   Confirmation document attached
   4. report any discrepancies to me


Please note that it is current AMSA advice that in a distress situation
*two* beacons should be activated at the same time where possible. This
gives SAR authorities added confidence that an activation was not
accidental.

kind regards
Steven



---------- Forwarded message ---------
From: Steven Ring ***@***.***>
Date: Fri, 7 May 2021 at 08:47
Subject: EPIRB and PLB audit
To: Bill Russo ***@***.***>, Sam DeLorenzo <
***@***.***>


Hi Bill and Sam,

I was not able to complete this audit. Could you please attend to it? I've
attached

   1. AMSA registration document
   2. SOP describing the audit procedure

many thanks
Steven

**Comment by smr547** [comment]
Colleagues,
Thank you Mr Wain, the credentials you provided work fine. 
I've updated the AMSA records with:
* PLB battery expiry extended to 3/2028
* Trip plans for Namadgi 3 over the next two years (as per Sam's draft)
* Emergency contact details for 1) Simon, 2) Sam D, 3) Peter WEach PLB entry has a note referring AMSA staff to details under the main EPIRB record (3EEC8F23CEFFBFF)

The last dot point means we really only have to update current contact information for one record, instead of nine.
There remains some uncertainty regarding the battery expiry on the main EPIRB -- Paul Jones is on board at the moment and will provide an update soon.
kind regardsSteven

**Comment by smr547** [comment]
Audit completed -- AMSA database updated. Main EPIRB battery expires Jun 2028

Next review scheduled for March 2024

<img width="1687" alt="Screen Shot 2022-03-13 at 5 37 28 pm" src="https://user-images.githubusercontent.com/4327895/158048563-fcd308fd-2e07-4899-b5f2-4fb157167da0.png">
