### ISSUE TITLE
Hazards of Bateman's Bay SOP

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#213]
Many members will be unfamiliar with crossing river bars in a large vessel. The Clyde River Bar presents a special problem for CORC member. Acheron Ledge at the northern end of the Bay is unmarked and very shallow. Tidal flow in the river is strong. Power cable on western side of the bridge is low.  The entire bay is "open waters".

We need a document which warns skippers to the special hazards presented at the Bay. This document should be promulgated to all members and particular to skippers prior to each booking.

Perhaps @SimonRD would be interested in drafting this SOP

**Comment by smr547** [comment]
Steven has prepared a [draft document](https://github.com/CanberraOceanRacingClub/namadgi3/blob/master/Batemans_Bay_Hazards.md)

**Comment by smr547** [comment]
The [draft document](https://github.com/CanberraOceanRacingClub/namadgi3/blob/master/Batemans_Bay_Hazards.md) has been updated following input from Garth, Simon as well as chats with marine rescue and the marina managers. Time to put it to the committee

**Comment by DaveHolt** [comment]
Steve, this is very useful. I think it should be onboard in paper form and distributed to all users of the boat.
BTW. There is a mooring at Maloney's Beach.

**Comment by smr547** [comment]
Hi Dave,

Thanks for that. I've been updating the document today and plan to give it to all who book the boat. Bill and Mark Miller are the first in line.  I'll include your comment about the mooring at Maloney's. Would you be happy to do "operations officer" duties at some stage?

**Comment by DaveHolt** [comment]
Yeah I'll try but I'm going to be gourmet farm sitting for my brother in-law in Cygnet, Tassie. I'm not if he has reliable internet down there. I'll be away from 24/9 - 15/10.

**Comment by smr547** [comment]
Ok ... Maybe you should enjoy the gourmet delight delights of Tassie without having to think about the Clyde River Bar or Acheron Ledge :-)
