### ISSUE TITLE
Logbook and pilots

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#218]
Just wondering if we need to buy a log book before we go to Batemans Bay -- or is there already one on board? A log book is essential and must be maintained while on passage.

Also highly recommened for our Cruising grounds are:

* *Cruising the NSW Coast* by Alan Lucas -- 6th edition is the latest
* *Rob's Passage Planner for East Coast of Australia* by Rob Starkey

These publications (and many others) are available from Boat Books in Crows Nest. I think the Club has a copy of Lucas but it almost certainly out of date.

@mrmrmartin @jphayden  and @DeeTaylor87 will be interested in this.

**Comment by DeeTaylor87** [comment]
I am picking up the logbook and the books if they are available in Pittwater today.

**Comment by DeeTaylor87** [comment]
Ok. Have logbook, Robs planner, Alan Lucas book on boat.

**Comment by DeeTaylor87** [comment]
Done.
