### ISSUE TITLE
Program the VHF radio with our MMSI number

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#220]
As per issue #56 @mrmrmartin has obtained 503058550 as the MMSI for Namadgi 3. This MMSI must now be configured into the [Garmin VHF 300 transceiver](https://buy.garmin.com/en-SG/digital/p/28723).

The procedure for doing this is described on pages 14 to 15 of the [Owner's manual](http://corc.com.au/Manuals/B46%20Garmin%20VHF%20300%20Owners%20Manual.pdf)

BTW, the *distress calling* procedure on pages 15-17 of the [Owner's manual](http://corc.com.au/Manuals/B46%20Garmin%20VHF%20300%20Owners%20Manual.pdf) should be mandatory reading for all skippers.

@DeeTaylor87 @mrmrmartin and @jphayden will be interested in this item for the upcoming passage to BB.

**Comment by jphayden** [comment]
Programmed MMSI into Garmin 300

**Comment by jphayden** [comment]
Radio check completed with Sydney Radio

**Comment by smr547** [comment]
Well done Jack.  Your voice transmissions will be accompanied by you MMSI and Position -- all digitally encoded.

The DISTRESS button will also work. I am informed that ALL Maritime Rescue units along the coast   are capable of receiving DCS alert signals. Of course, we hope you don't need them.

I'd encourage you to contact the Marine Rescue Centres as you progress down the coast -- you could use the opportunity to provide the crew with a demo of good Marine Radio procedure -- and all test our VHF unit. 

I await with interest your findings. :-)

**Comment by jphayden** [comment]
Hi Steven
Will do  
Regards

Jack

**Comment by DeeTaylor87** [comment]
@mrmrmartin contacted the Marine Rescue organisations on the way down the coast. Can you comment on how it worked?  Let me know if you are happy for me to close this issue

**Comment by mrmrmartin** [comment]
The radio worked well and we picked up Sydney, Ulladulla, Batemans Bay and a few other stations.
The AIS worked well too we could see other vessels and they I believe could see us.
Steven Ring could also see us in Canberrra
Suggest close this one

**Comment by DeeTaylor87** [comment]
Thanks. Closing.
