### ISSUE TITLE
Marine VHF radio operators handbook

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#221]
A copy of [this booklet](http://www.marineradiolicence.com.au/MR/VHF%20Radio%20Handbook.pdf) should be purchased and kept on Namadgi 3 at all times

Moreover, all members should be encouraged to complete [this course](http://www.amc.edu.au/industry/omc/certificates/short-range-operator-certificate-of-proficiency-srocp) to ensure that they are proficient with our VHF/DSC marine radio. 

@DeeTaylor87 will be interest in this

**Comment by DeeTaylor87** [comment]
OK. Will add it to the list of things to find today.
