### ISSUE TITLE
Modify the panels on the head tanks

### ISSUE THREAD

**Issue by DeeTaylor87** [CanberraOceanRacingClub/namadgi3#224]
Given that the readings on boat waste tanks are notoriously difficult to trust, Bill has proposed a solution for bypassing the need for an electronic monitor. We can replace the screws on the panel with the same type of catch system that we have on the engine bay panels. This will enable us to easily remove the panel and visually check the state of the tanks. (No screwdriver required). It will be very minimal cost

**Comment by DeeTaylor87** [comment]
Just checked again. Those catches not suitable but it should not be too hard to find something that will work.

**Comment by smr547** [comment]
Closing this item -- historical
