### ISSUE TITLE
Broken tray cover in Fridge door

### ISSUE THREAD

**Issue by DeeTaylor87** [CanberraOceanRacingClub/namadgi3#225]
There is (was) a little blue tray that covered the top shelf in the fridge door. The tray can flick up and get trapped as the door closes. In a heeling boat at sea, the cover has cracked when the door closed. The suggestion has been made not to replace it because of a high risk that it will just happen again. Comments welcome.

**Comment by DeeTaylor87** [comment]
@DaveHolt can you tell me what make and model our fridge on board is?  I am trying to source the part and have written to Bavaria, but no word yet. I am wondering if you might have some details on it.

**Comment by DaveHolt** [comment]
Stab in the dark I would say Isotherm? But really just guessing.

**Comment by DeeTaylor87** [comment]
Frank just confirmed it is  a Waeco Coolmatic by Domestic Group. Model CRX 110.  I shall do some research.

**Comment by DeeTaylor87** [comment]
Waeco Coolmatic by Domestic Group. Model CRX 110

**Comment by DeeTaylor87** [comment]
Shelf part number is 40-092-06PT  $12.50 plus freight.  Complete Appliance Repairs in Valley Heights 58A Green Pde, 4751 1557.  How amazing is that?  The distributer lives in my street!

**Comment by DeeTaylor87** [comment]
I have the part. If anyone wants it in a hurry, let me know. Otherwise, I'll keep it until the boat returns to Sydney.

**Comment by DeeTaylor87** [comment]
Shelf is back on board.
