### ISSUE TITLE
Fender lost off lifeline

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#230]
A fender knot has come undone in Batemans Bay marina. The fender is missing. The manager may have found it.

**Comment by DeeTaylor87** [comment]
Wondering if this has been found?  Was it based on only seeing three fenders alongside? I think there was a fourth in the central cockpit locker.

**Comment by DaveHolt** [comment]
The fender had been tied to the life line amidships. But the knot from the line to the fender had pulled thru leaving just the line hanging off the life line and no fender. We can get another from RTM and send it down.

**Comment by DaveHolt** [comment]
Franks says there are only 3 on board. I have asked Mark Miller to buy one. Size either 620 x 210 or 700 x 240.

**Comment by DaveHolt** [comment]
Mark bought a 700mm fender from RTM for about $50 and put it on board.
