### ISSUE TITLE
BBQ piezo not working, flame blows out

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#235]
Bill said: Replaced the BBQ  control valve,( and the stay that I lost overboard ) Not able to get the Piezio working.

**Comment by DaveHolt** [comment]
Piezo still not working and flame blows in very little wind. BBQ box may be bent from when it went overboard allowing wind to enter and damage or misalignment to piezo

**Comment by smr547** [comment]
This was fixed at last service -- close and remove from working bee
