### ISSUE TITLE
Bavaria control panel - alarm flashing continuously

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#236]
Bill said: The alarm light on the Bavaria panel was flashing for no reason on two occasions, once for low water quantity, and once for low battery capacity,even though the bars were indicating around 60% cap.

**Comment by DeeTaylor87** [comment]
I wonder if it just needs to be acknowledged by pressing and holding the return button next to the up/down buttons under the display?  You have to acknowledge the alarm to say you have seen it I think before it will go off.  It might have been triggered some time ago and just never been acknowledged.

**Comment by DaveHolt** [comment]
Closing this. it is due to the sensors on the black tanks needing cleaning.
