### ISSUE TITLE
Main halyard slips in Spinlock and other jammers under any load - wrong rope type?

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#243]
Sorry if this is recorded in another issue. I can't find it.
Peter Morris reported that the main halyard was slipping through the Spinlock jammer.
Also: Dave; Bill; Jack.
Bill removed some sticker residue which improved the problem for a while.
The white halyard slips on the area where the jammers normally contacts it. Fresh sections of rope seem to hold.
Dave swapped the black main topping lift into the main halyard jammer which worked. But apparently it also started to slip after some use.
Do we have the correct type of ropes for the jammers? Rigger? Ensign?

**Comment by smr547** [comment]
Closing this item -- historical
