### ISSUE TITLE
Galley items - new spatula, wooden spoon, sharp knives in scabbards

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#252]

**Comment by DeeTaylor87** [comment]
There are a few items in storage unless someone moved them to the boat already. This material may be still there.  I can call Phil K if you can confirm that no-one has picked it up from MonaVale?

**Comment by DaveHolt** [comment]
Dee,
Thus item is just a reminder for us to buy more. Someone mentioned then in a skippers report. They aren't in the store.
Thanks,
Dave

David Holt
0439 470 261
