### ISSUE TITLE
Large cabin hatches - screw holes and friction lever holes are crazed

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#259]
The starboard forward cabin hatch was split into two by a caught line when the dinghy bow was being hoisted for ventilation.

I think the boat shouldn’t go to sea and probably should stay away from the Harbour heads if there is any swell. I don’t think there is much we can do today on New Years Day. 

A couple of options:
1. Order a Bavaria replacement tomorrow (through Ensign?) Part No.?
2. Request John’s Boat Hatches to make a replacement. John will take the broken bits away. The last hatch he did for us took about 7 days.
3. Make a temporary plywood hatch

This might affect Sam Hughes' and PeterO’s bookings so I have cc’d Sam.

![image1](https://user-images.githubusercontent.com/31207261/34465130-d22bbb16-eef3-11e7-9b01-2074ed143260.jpeg)

**Comment by DaveHolt** [comment]
The handle is also U/S

![broken fwd hatch handle](https://user-images.githubusercontent.com/31207261/34547575-3a33c1e6-f150-11e7-9e4d-3edd068f4d00.jpeg)

Hatch measurements: 54.5 x 57.5cm

**Comment by DaveHolt** [comment]
Mark obtained a temporary replacement hatch from Andy at Ensign. As it is a non-genuine slightly less good hatch he fitted it to the saloon centre hatch and swapped the saloon centre hatch to the forward stb hatch.

John's boat hatches are making a new hatch.
We need a new locking friction lever. Andy must know where to get them.

**Comment by DaveHolt** [comment]
When swapping the hatches Mark noticed crazing or cracking around the locking points on the centre hatch. See photo. Probably need to follow this up with Ensign.

![crazed hatches](https://user-images.githubusercontent.com/31207261/34633634-744b070e-f2d1-11e7-82c4-f66d5cfe1551.jpeg)

![crazed hatches2](https://user-images.githubusercontent.com/31207261/34633658-acf7b9bc-f2d1-11e7-8d1e-715032ef9991.jpeg)

**Comment by smr547** [comment]
Closing this item -- historical
