### ISSUE TITLE
Registration Complete, Need a number plate inside boat

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#26]
Nominal date
who: Sam Hughes

**Comment by smr547** [comment]
Is this a regulatory requirement -- ask @jphayden

**Comment by jphayden** [comment]
Don’t know  - I think Peter would know

 

Jack

**Comment by smr547** [comment]
I'll ask Sam Hughes
@mrmrmartin -- Can you please tell us what our registration numbers are (Australian Ship number and NSW rego number)?

**Comment by mrmrmartin** [comment]
Hi Steven


Our licence number is VR182551

Our rego number is AJG844N

________________________________

**Comment by DeeTaylor87** [comment]
@DaveHolt  see above @jphayden

**Comment by DeeTaylor87** [comment]
@DaveHolt @mrmrmartin @smr547 @jphayden 
So on the VHF Marine Radio Log on Procedure Sticker that I am putting up inside the boat, I write:
Vessel Name: Namadgi 3
Vessel Registration Number: AJG844N
??? Just checking that I have it right - there are so many numbers!!!!

**Comment by smr547** [comment]
Closing this item -- historical
