### ISSUE TITLE
Anchor Chain needs to be marked for length

### ISSUE THREAD

**Issue by delcosta** [CanberraOceanRacingClub/namadgi3#260]
Is there suitable markers we can lock into links?

**Comment by peterottesen** [comment]
I suggest we use both paint (a generous amount at each 10m) and cable ties to mark the chain. Bring the boat bow-in one day, which makes it easy to lay the chain along the dock for measurement and marking.

**Comment by smr547** [comment]
@pauljones17 reports:

```
The marking on the anchor cable needs to be refreshed – there are the remnants of two systems (paint and plastic inserts) which need validating before deployment.  
An end of chain warning would also be useful.
```

Reopening this issue and assigning to working bee

**Comment by delcosta** [comment]
I agree there should be an "End of Chain" warning

**Comment by smr547** [comment]
@mrmrmartin reports

>Repainted the anchor chain in this sequence 10m red, 20m yellow, 30m red, 40m yellow 45m red to warn user is running out of chain

Thank you Michael, closing this issue but maintaining the ``Routine Maintenance`` label

@mgrybaitis will be interested.

**Comment by smr547** [comment]
Time to remark the chain -- great job for a working bee. 

Note that we are planning to replace the chain at this working bee with the spare chain we have in the storage locker.

**Comment by smr547** [comment]
New galvanised anchor chain installed today -- 10mm, 50m long

Painted at 10m intervals and also marked with plastic tabs at 10m intervals with a "final" five plastic tabs at 45m

closing this issue 

![IMG-0029](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/8d178d12-952f-41a1-a303-75b9a2fe255d)
![IMG-0031](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/d9212997-ac83-40ab-bc03-a43ea9efa1a8)
