### ISSUE TITLE
Replace Vacuum cleaner

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#263]
Suggestion from Mark Miller: 
One more think to think about - I suggest we replace the old bulky vac with a Dyson stick - that old vacuum is bulky and marking the boat as it is pulled around - just my suggestion - leave it in your hands to discuss.

**Comment by smr547** [comment]
@mrmrmartin reports that the current vacuum cleaner has rusty fittings and is weak. We will need to replace it at this working bee. Suggest we purchase a good quality machine as originally recommended by Mark Miller: i.e. A Dyson Stick

**Comment by smr547** [comment]
There is currently a [Hoover Ultra Light](https://www.productreview.com.au/listings/hoover-ultra-light-22-2v) vacuum on board. The unit is operational  but the following issues were noted

* exit filter was clogged with dust
* very poor suction
* power plug severely corroded (22V variety -- will be difficult to replace)

Removing all filters I found the suction remained extremely poor. The unit is definitely at end of life. We will replace it with a Dyson unit of similar size unless anyone else has any recommendations.

@mrmrmartin will be interested as he first raised the issue. @delcosta and @pjwain -- are you happy to proceed with Dyson purchase?

**Comment by smr547** [comment]
New vacuum cleaner purchased at working bee
