### ISSUE TITLE
Veneer splitting and lifting under top step on campionway stairs

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#265]
This should go on warranty list. Veneer splitting and lifting under top step on campionway stairs. Both sides. PeterO

![veneer split stairs](https://user-images.githubusercontent.com/31207261/35240474-add56102-0007-11e8-846c-c6154b590dac.jpg)

**Comment by DaveHolt** [comment]
![img_3217](https://user-images.githubusercontent.com/31207261/36636898-b0b29828-1a23-11e8-8d2a-4f71e1421293.JPG)

**Comment by DaveHolt** [comment]
Andy advised that we try using a an iron to press it down and reattach it.
If that doesn't work he will look at a new piece of laminate

**Comment by smr547** [comment]
Checked today -- This is still an issue

**Comment by smr547** [comment]
Some things we have to let go. Closing this issue
