### ISSUE TITLE
Dinghy is leaking and requires patching

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#266]
Reported by PeterO.
Dinghy is leaking and requires patching

**Comment by peterottesen** [comment]
Not sure there is leak, but pressure was low.  Patching is required on some spots subject to high levels of wear.  It would also be useful to have some spare patching material at hand and an appropriate glue to do spot repairs and reinforce wear spots.

**Comment by DaveHolt** [comment]
I think the dinghy patches, glues, etc are on board in a large Tupperware box marked something like "Inflatable dinghy repair kit". It should also contain the pump adaptors. Don't know which locker it is stored in.

**Comment by peterottesen** [comment]
I checked a week or so ago and could not find the box with dinghy stuff. The adaptor is taped to the pump.

**Comment by DaveHolt** [comment]
PeterO has patched some of the high wear areas and glued up some loose bits. It isn't leaking.
