### ISSUE TITLE
Holding tank breather are blocked

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#268]
The starboard forward tank erupted sewage onto the deck during a pump out at CYCA. The tank was probably completely full and more flushing had probably pressurised it. When the pump out cap was removed...yuk poo.
Clean the tanks?
Try to clear the breather?
Repair the level gauge that reads 75% all the time.

**Comment by smr547** [comment]
It appears that this issue has developed again -- Reopening it.
The race crew in Port Stephens are working to remove and clean the breather pipe and fitting.

@PSARN @peterottesen will be interested.

**Comment by PSARN** [comment]
It is actually the AFT tank that was cleaned.

**Comment by smr547** [comment]
Then it looks like this a systemic problem with the boat. I noted that the breather has a stainless gauze cover that would trap paper and other lumpy bits. Paper would then dry out and create a nasty plug. 

I'll leave this item open and change the title. Dave Holt's colourful description of the  original problem is gold!

**Comment by peterottesen** [comment]
Starboard aft.

**Comment by smr547** [comment]
Breather tanks are blocking due  effluent drying in them following an overflow event. 

Namadgi's holding tanks breather tubes are poorly designed and cannot tolerate an overflow of the holding tanks. The smallest bit of waste in the tube can cause a blockage... see the "capsicum photo" below.  A blocked breather tube  is a disaster -- it will:

1. not allow the tank to be discharged to sea (or via vacuum pump-out)
2. stop the pumping of effluent from the toilet bowl  -- the manual pump will "go hard"
3. pressurise the system causing effluent to burst from the deck waste vent when the cap is removed 

Skippers have been asked to empty tanks regularly to prevent overflow (see notice #366). A SOP will be written on the subject of toilet procedures.

Meanwhile, at the current working bee, all breather tanks have been disconnected and flushed clear with water. They are all working. So closing this item for now. But my guess is that we have not seen the last of this issue.

![IMG_4358](https://user-images.githubusercontent.com/4327895/117092564-fc599000-ada1-11eb-8ef3-1e0ef62def27.JPG)
Very restrictive holes in the breather deck fitting -- not designed to handle overflows

![IMG_4351](https://user-images.githubusercontent.com/4327895/117092650-388cf080-ada2-11eb-8abf-8386786f8929.jpg)
A piece of partially digested capsicum is all it takes to create a very messy blockage

**Comment by smr547** [comment]
[This video](https://www.youtube.com/watch?v=ftNRhtPjqGw) describes our problem
