### ISSUE TITLE
Repair protective wiring cover at mast base. Refit dyneema protector

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#271]
The protective wiring cover at mast base is being ripped by Genoa sheets. We might need to refit the dyneema protector originally set up by Mario Ruel.

![img_3178](https://user-images.githubusercontent.com/31207261/36364799-6d61c14e-159a-11e8-951b-0f4e87592410.jpg)

**Comment by DeeTaylor87** [comment]
Peter Ottesen refitted the dyneema strop last week.
