### ISSUE TITLE
Sail bag wear holes caused by plastic hooks

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#272]
Sail bag wear holes caused by plastic hooks - PeterO

![img_3198](https://user-images.githubusercontent.com/31207261/36518920-a43090b2-17dc-11e8-802b-ab3ade2ff5a7.JPG)

**Comment by DaveHolt** [comment]
![img_3201](https://user-images.githubusercontent.com/31207261/36519953-7212417e-17e2-11e8-8050-4e9c4496b76f.JPG)

**Comment by smr547** [comment]
No longer an issue
