### ISSUE TITLE
Shopping list April 2018 working party

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#273]
Scrubbing brush on adjustable handle for decks and water line
Sugar soap
Floor mop, compact
Reading lamp bulbs ~3,4 spares try to get LEDs rather than halogen
Grub screws for door handles -3,5 spares
Toilet brush port aft head
S/Steel Gas hose - shorter than we have
Reefing dots for no.2 Head sail  10-12
C26 Sail numbers 3 or 4 sets, both sides of each sail
Rechargeable compact Vacuum cleaner
Plastic scabbards for new knives
Bread and butter plates x8
2 replacement big deep dinner bowls to replace the non-fitting china bowls
Electronic Distress Flare - Ocean Signal rescueMe EDF1 $180
Plastic Tupperware style containers for galley x6 various sizes
Plastic Tupperware style containers to organise kitchen utensils, etc 300x400
Large locking handle for broken hatch - kit of 2 left & right from BLA part no. 172196 ~$125 pick up from Whitworths Mona Vale o/n NV29/74
Vinegar for stings; vinegar for cleaning toilet pipes

**Comment by DaveHolt** [comment]
Garmin G2 Vision charts on MicroSD card - purchased

**Comment by DaveHolt** [comment]
Pick up from Paul McDonald's garage at Wonboyn:

1 Burke life-ring bag (for rail mount)
Number of spare racing main carriages - might fit trysail?
Various sheets and braces (in black Carry bag) - is this racing gear?
Aft head rail support(for wet weather gear)
Swimming pool noodles
anything else that might be useful for winter cruise - not racing gear

**Comment by smr547** [comment]
Closing this issue as no longer relevant
