### ISSUE TITLE
PLBs - renew 8 registrations with AMSA

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#275]
Dave needs to renew 8 PLB registrations with AMSA website by 30 March
Update home address
Update Emergency contacts - drop SamDL add Jack? 
Keep Michael and Dave?

For info:  @mrmrmartin @delcosta @jphayden

**Comment by jphayden** [comment]
Dave  -  I am happy with that

Cheers 
Jack

**Comment by DaveHolt** [comment]
Done
