### ISSUE TITLE
Make a ventilated fuel and gas compartment in the cockpit.

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#287]
The cockpit lockers can currently can drain fumes into the interior of the boat. Some openings could be blocked with some kind of space filler? The compartment would also need ventilation. and look at how to secure the gas bottles in the compartment so they don't move around.

**Comment by DaveHolt** [comment]
Or purchase a gas tight container for inside stowage - Alan Conway

**Comment by smr547** [comment]
Task completed some time ago -- closing
