### ISSUE TITLE
SOPs opening and closing boat, bow thruster

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#29]
Bill Russo has offered to make videos of SOPs
who: DaveH, Committee

**Comment by jphayden** [comment]
Definitely need a bowthruster SOP eg danger of using it in a berth with ropes in the water around the bow (same for moorings)
Maybe one of the Trilogy guys could do it

**Comment by DeeTaylor87** [comment]
Some editing needed on SOPs for opening and closing the boat. 

Get rid of reference to fridge drip tray - we don't have one in our new fridge.
Need to add reference to transom / swim platform

**Comment by smr547** [comment]
While we are at it, a reminder to Also add to  these SOPs: 

* Check main engine seawater inlet seacock is left OPEN

**Comment by jphayden** [comment]
Yes indeed  - hadn't forgot - I was checking with Dave for the latest version number of the SOP  I have a word version  I think we need a publications officer  😀
