### ISSUE TITLE
Swim platform limit switch is inoperative

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#295]
When raising the swim deck be aware that the auto limit switch is not working. Please release the button as soon as the swim deck is stowed in the vertical position. Continuing to hold the button will cause the lifting rope to tangle around the spindle of the lifting mechanism.

**Comment by smr547** [comment]
Bill Leslie replaced the faulting sense switch on the transom and then confirmed correct operation. 

We inspected the mechanism and found:

1. pulley on the swim deck is very noisy (but serviceable)
2. there is NO limit switch for downward operation -- it would be very difficult to fit one 
2. some noise coming from the pulley under the cover below the switch
3. motor mechanism (accessible via port stern cabin) is of high quality and is in excellent condition
4. the mounting of the drive mechanism is very sturdy
5. Dyneema support straps are worn (but still serviceable)  -- we have ordered new straps as spares

Perhaps we should carry spares for the pulleys in case the noises are indicating imminent failure. I'll document that under #363 -- 

Closing this issue. @delcosta will be interested.

**Comment by smr547** [comment]
Bill recommends buying three or four spare switches. He sourced them from a car wrecker. Apparently it is a door switch from a Toyoto Hilux.  Bill has offered to source these.

**Comment by delcosta** [comment]
Steven
This is good. I am assuming the top switch only cutting off and the lowering cut off still needs operator caution.

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603

IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail.
