### ISSUE TITLE
Aft STB heads holding tank not emptying

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#298]
Cleaned the breather and overflow. Now working. When emptied

**Comment by PSARN** [comment]
Filled the aft STB head with fresh water to test the operation, and found the the overflow connector at the top of the tank appears to be blocked from the inside of the tank  as water was barely flowing through the overflow. See picture. The overflow line was cleared from the sprightly forward. A comparative test was done with with the fwd STB head which confirmed the limited flow through the AFT head overflow.
The head still works as long as it is not filled to overflow.
![6B848DAC-CC0A-4F8C-AFD7-26923A184C2A](https://user-images.githubusercontent.com/32588100/115931981-6f742400-a4cf-11eb-9c6a-1f5965e9da22.jpeg)

**Comment by smr547** [comment]
This seems to be an onging problem with these heads (see #268). Perhaps there is dried toilet paper in the breather line acting like a ball valve as it is pressed against the wire mesh at the hull fitting.

We will rmove the pipe and see if we can dislodge the obstruction. Hopefully we can establish a routine fix for the problem Any further suggestions would be appreciated.

**Comment by smr547** [comment]
Removed from top of tank, flushed with water from topside fitting. Flow rate good. Reconnected. Closing this issue.
