### ISSUE TITLE
Sat comm antenna broken

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#299]
New antenna cover required. This antenna is mounted on the top pushpit rail, starboard side, near the outboard mounting. We are currently unsure  which system this antenna services -- does anyone know?

**Comment by smr547** [comment]
This is probably the external Iridium Go antenna

**Comment by pcbaston** [comment]
The antenna IS the external helical antenna for the Iridium GO.  I unwrapped the tape in Opua after the Cyclone and split the cover more, so I removed it completely. The internal helical coils were slightly out of alignment, so I replaced them as best I could and then reattached/resealed the cover with silicone adhesive onboard. 
![IMG_20230215_164153568](https://user-images.githubusercontent.com/120452016/221346558-b459d88c-a9cf-4c37-8933-8830bc02ee56.jpg)
