### ISSUE TITLE
Manuals - acquire print and PDF versions

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#30]
who: DaveH, Committee

**Comment by DeeTaylor87** [comment]
If you let me know before 9th August, I can collect manuals from boat, take them home, can them etc and then return them to the boat. I don't want to do that unless someone lets me know it is ok to take them off the boat first.

**Comment by pjwain** [comment]
I have a set of pdf manuals, including all the ones I could find on the internet plus the B46 manual that was kindly scanned by Paul McDonald. I have already published them all on the CORC website for anyone who wants to download them. Here is a list:

1. Bavaria 46 Cruiser Owners Manual (10 MB)
2. Autopilot Owners Manual Garmin GHC 20 (2.5 MB) 
3. Chart Plotter Manual Garmin GPS map 721 (2.3 MB)
4. Chart Plotter Quiskstart Garmin GPS map 721 (2.5 MB)
5. Engine Operators Manual Volvo Penta D2-75 (12 MB)
6. Multifunction Instrument Garmin GMI 20 (2 MB)
7. Stereo Cockpit Unit Fusion MS-NRX300 (3 MB)
8. Stereo Quickstart Manual MS-RA205 (6 MB)
9. Garmin VHF 300 Owners Manual (1.4 MB)
10. Battery Monitor Installation & Operations Guide (2.5 MB)
11. Gas Detector Installation & Operations Guide (220 kB)
12. AIS Transponder Vesper XB8000 (1.2 MB)
13. Antenna Splitter Brochure Vesper SP160 (120 kB)
14. Antenna Splitter Vesper Manual SP160 (240 kB) 
15. Battery Charger Cristec Ypower 12v40a (3.5 MB)
16. Engine Technical Data Volvo Penta D2-75 (600 kB)
17. Furler Luff Assembly Furlex 304S (300 kB)
18. Furler Manual Furlex 304S (3 MB)
19. VHF Handset Garmin Installation Guide GHS10i (500 kB)

**Comment by DeeTaylor87** [comment]
I have the following downloaded from the internet
20. Sigmar Marine Compact Boiler (3025 kB)
21. Whale Gulper IC Manual (1203 kB)
22. Jabsco Waterpump Par Max installation Guide / Technical Specs (3604 kB)

**Comment by DeeTaylor87** [comment]
Remember to scan the information provided on the inverter and isolation transformer that is in the manuals on board.  I am hoping @pjwain or @paulmc9999 will take care of this?
