### ISSUE TITLE
Mainsail maintenance and repair

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#304]
The mainsail is to be regularly inspected. Any necessary repairs are to be undertaken by a professional sailmaker. Please see the contact list in the Google account canberraoceanracingclub@gmail.com under the ``Sailmaker`` label.

**Comment by smr547** [comment]
The race crew returning from the Port Stephens regatta have reported that the mainsail is in need of repairs including

* Replace broken top batten
* wear and tear along the leech particularly towards the top
* other minor tears
* assess for installation of reefing tie points 

The race crew removed and packaged the sail for transport. 

They reported that the main looks tired and maybe nearing end of life. The sailmaker has been asked for an assessment of the remaining useable life of the sail. He mentioned that the race committee have already been provided with quotes for a new mainsail.

The sailmaker (Ben from Hoods Sails, Brookvale Ph: 9905-0800) has taken the sail to the loft and will lay it out for assessment tomorrow. He will contact @peterottesen for further instructions. 

@delcosta and @peterottesen will be interested

**Comment by delcosta** [comment]
Thanks Steve
Noted

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603

IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail.

**Comment by smr547** [comment]
Hi Pete,

Thanks for the great work keeping this all on track. I'm not sure of Sam's
ETA tomorrow so it might fall to Bill and Chris to help Ben.

Fingers crossed that the weather is kind. There is a weak East Coast Low
off Sydney and we are getting lots of rain.

kind regards
Steven





On Thu, 6 May 2021 at 12:23, Peter Ottesen ***@***.***> wrote:

> Ben (Hood Sails) has confirmed he will deliver the sail between 10 and 11
> tomorrow, Friday.
>
> He said he can hang around to assist with its rigging.  Can you please
> make sure people are ready, battens out and ready etc, to minimise his
> time.  I wish I could be there to ask questions...
>
> I gave him sam’s mobile number to ring.  Perhaps some one can be ready to
> meet him in the carpark when he arrives.
>
> Ben’s number is 0419 433  889  (9905 0800)
>
> cheers
>
>
>

-- 
*Steven Ring*
m: +61 417 495 268

**Comment by smr547** [comment]
Bill Russo reports that following the repairs to the mainsail:

"Sail is on mast and reefing lines fitted. Ben from Hood left after we put the battens in but before we put it on the mast. Hasn’t been tested due to wind. "

Given that the main has just been put back on the mast there is a danger that reefing lines or other aspects of the installation may not be quite right. The guys didn't have time to test it owing to wind. I've put a few mains on and managed to have reefing lines in the wrong place more than once.

@mrmrmartin and @peterottesen are advised to put the main up and test it before going to sea. A quiet morning in the marina or, better still, on a mooring might provide  the opportunity to check it out.

regards
Steven

**Comment by mrmrmartin** [comment]
Thanks for the info we will test before we leave the sheltered waters of Pittwater
