### ISSUE TITLE
Check Flares and purchase replacements as required

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#325]
Use Cat 1 requirements as guide

**Comment by smr547** [comment]
Opening this item as we need to record current status. @mrmrmartin has recently updated information.

**Comment by smr547** [comment]
Hi Michael and other friends,

We are checking the flares on board Namadgi. Could someone with CAT 1
knowledge please look over the list below and see if we need to buy
additional flares. This list was produced 7/2 and I don't know if there
have been any recent purchases -- perhaps Michael can advise.

We just checked the grab bag and it has many expired flags. We will collect
all expired flares for immediate disposal -- any ideas as to where we can
dispose of them?

kind regards
Steven

---------- Forwarded message ---------
From: Steven Ring ***@***.***>
Date: Sun, 7 Feb 2021 at 22:11
Subject: Namadgi 3 Flares
To: Martin, Michael ***@***.***>


Hi Michael

Inventory of flares as requested:


   - All flares are stored in a bright orange flare box with black screw top
   - Located Amidships, cockpit, aft deck/floor locker
   - Correctly indicated on stowage plan


Flare Box Contents:


   - 2 x Para Red Rocket MK8A -- 12/22
   - 4 x Shuttle Hand held rocket (RED) -- 06/22
   - 2 x Vulcan floating smoke flare -- 07/22
   - 3 x Elios red hand held -- 07/22
   - 2 x PainsWesssex Orange smoke -- 12/22
   - 2 x PainsWesssex red handheld -- 12/22
   - 1 x PainsWessex white collision warning hand held -- 9/22

Expired Flares

   - 1 x PainsWessex white collision warning hand held -- 9/20 (expired)
   - 2 x PainsWesssex Orange smoke -- 11/18 (expired)
   - 2 x PainsWesssex red handheld -- 11/18 (expired)


Note: There maybe flares in the Grab Bag but I did not check

kind regards
Steven

-- 
*Steven Ring*
m: +61 417 495 268

**Comment by smr547** [comment]
Steve
Flares were re-stocked in February. Disposal stations may be noted on the Maritime Services website.

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603

IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail.

From: Steven Ring ***@***.***>
Sent: Thursday, 6 May 2021 09:33
To: Martin, Michael ***@***.***>; Jones, Paul ***@***.***>; ***@***.*** ***@***.***>; Michelle Grybaitis ***@***.***>; Sam Delorenzo (Delorco) ***@***.***>; Peter Ottesen ***@***.***>; Peter Lucey ***@***.***>; garth.brice ***@***.***>; Simon Dunlop ***@***.***>; Peter Wain ***@***.***>
Cc: CanberraOceanRacingClub/namadgi3 ***@***.***>
Subject: Fwd: Namadgi 3 Flares

Hi Michael and other friends,

We are checking the flares on board Namadgi. Could someone with CAT 1 knowledge please look over the list below and see if we need to buy additional flares. This list was produced 7/2 and I don't know if there have been any recent purchases -- perhaps Michael can advise.

We just checked the grab bag and it has many expired flags. We will collect all expired flares for immediate disposal -- any ideas as to where we can dispose of them?

kind regards
Steven
---------- Forwarded message ---------
From: Steven Ring ***@***.******@***.***>>
Date: Sun, 7 Feb 2021 at 22:11
Subject: Namadgi 3 Flares
To: Martin, Michael ***@***.******@***.***>>

Hi Michael

Inventory of flares as requested:


  *   All flares are stored in a bright orange flare box with black screw top
  *   Located Amidships, cockpit, aft deck/floor locker
  *   Correctly indicated on stowage plan

Flare Box Contents:


  *   2 x Para Red Rocket MK8A -- 12/22
  *   4 x Shuttle Hand held rocket (RED) -- 06/22
  *   2 x Vulcan floating smoke flare -- 07/22
  *   3 x Elios red hand held -- 07/22
  *   2 x PainsWesssex Orange smoke -- 12/22
  *   2 x PainsWesssex red handheld -- 12/22
  *   1 x PainsWessex white collision warning hand held -- 9/22
Expired Flares

  *   1 x PainsWessex white collision warning hand held -- 9/20 (expired)
  *   2 x PainsWesssex Orange smoke -- 11/18 (expired)
  *   2 x PainsWesssex red handheld -- 11/18 (expired)

Note: There maybe flares in the Grab Bag but I did not check

kind regards
Steven

--
Steven Ring
m: +61 417 495 268

**Comment by smr547** [comment]
Excellent, thanks Sam. We will find a disposal station.

kind regards
Steven

On Thu, 6 May 2021 at 10:19, Sam Delorenzo (Delorco) <
***@***.***> wrote:

> Steve
>
> Flares were re-stocked in February. Disposal stations may be noted on the
> Maritime Services website.
>
>
>
> Regards,
>
> Sam DeLorenzo
>
> Mobile & WhatsApp: +61 411 165 835
>
> PO Box 3553, Manuka ACT  AUSTRALIA 2603
>
>
>
> IMPORTANT
>
> This e-mail and any accompanying attachments are intended for the sole use
> of the addressee(s) and may contain confidential information. If you are
> not the intended recipient (or authorised designee), please disregard the
> contents of this e-mail, notify the sender immediately and destroy all
> copies of this e-mail.
>
>
>
> *From:* Steven Ring ***@***.***>
> *Sent:* Thursday, 6 May 2021 09:33
> *To:* Martin, Michael ***@***.***>; Jones, Paul <
> ***@***.***>; ***@***.*** <
> ***@***.***>; Michelle Grybaitis <
> ***@***.***>; Sam Delorenzo (Delorco) <
> ***@***.***>; Peter Ottesen ***@***.***>;
> Peter Lucey ***@***.***>; garth.brice ***@***.***>;
> Simon Dunlop ***@***.***>; Peter Wain ***@***.***>
> *Cc:* CanberraOceanRacingClub/namadgi3 <
> ***@***.***>
> *Subject:* Fwd: Namadgi 3 Flares
>
>
>
> Hi Michael and other friends,
>
>
>
> We are checking the flares on board Namadgi. Could someone with CAT 1
> knowledge please look over the list below and see if we need to buy
> additional flares. This list was produced 7/2 and I don't know if there
> have been any recent purchases -- perhaps Michael can advise.
>
>
>
> We just checked the grab bag and it has many expired flags. We will
> collect all expired flares for immediate disposal -- any ideas as to where
> we can dispose of them?
>
>
>
> kind regards
>
> Steven
>
> ---------- Forwarded message ---------
> From: *Steven Ring* ***@***.***>
> Date: Sun, 7 Feb 2021 at 22:11
> Subject: Namadgi 3 Flares
> To: Martin, Michael ***@***.***>
>
>
>
> Hi Michael
>
>
>
> Inventory of flares as requested:
>
>
>
>    - All flares are stored in a bright orange flare box with black screw
>    top
>    - Located Amidships, cockpit, aft deck/floor locker
>    - Correctly indicated on stowage plan
>
>
>
> Flare Box Contents:
>
>
>
>    - 2 x Para Red Rocket MK8A -- 12/22
>    - 4 x Shuttle Hand held rocket (RED) -- 06/22
>    - 2 x Vulcan floating smoke flare -- 07/22
>    - 3 x Elios red hand held -- 07/22
>    - 2 x PainsWesssex Orange smoke -- 12/22
>    - 2 x PainsWesssex red handheld -- 12/22
>    - 1 x PainsWessex white collision warning hand held -- 9/22
>
> Expired Flares
>
>    - 1 x PainsWessex white collision warning hand held -- 9/20 (expired)
>    - 2 x PainsWesssex Orange smoke -- 11/18 (expired)
>    - 2 x PainsWesssex red handheld -- 11/18 (expired)
>
>
>
> Note: There maybe flares in the Grab Bag but I did not check
>
>
>
> kind regards
>
> Steven
>
>
>
> --
>
> *Steven Ring*
>
> m: +61 417 495 268
>


-- 
*Steven Ring*
m: +61 417 495 268

**Comment by smr547** [comment]
For Cat 1 we need to have:

 

S 4.22.1 of Special Reg

6 parachute 

4 red hand held

2 white

4 orange smoke

 

Looks like we need 1 x white hand held. Otherwise we are OK.

 

In NSW RMS hold regular expired flare collection days at various locations. We had one in the Bay a couple of weeks ago and similarly at Bayview. I don’t see any scheduled in the near future. Perhaps we store them in the container until the next collection day.

 

 

All the best

Simon

0412 262 933

 

“If you only listen to people you agree with, you will never learn anything!” 

 

 

 

 

From: Steven Ring ***@***.*** 
Sent: Thursday, May 6, 2021 9:33 AM
To: Martin, Michael ***@***.***>; Jones, Paul ***@***.***>; ***@***.*** ***@***.***>; Michelle Grybaitis ***@***.***>; Sam DeLorenzo ***@***.***>; Peter Ottesen ***@***.***>; Peter Lucey ***@***.***>; garth.brice ***@***.***>; Simon Dunlop ***@***.***>; Peter Wain ***@***.***>
Cc: CanberraOceanRacingClub/namadgi3 ***@***.***>
Subject: Fwd: Namadgi 3 Flares

 

Hi Michael and other friends,

 

We are checking the flares on board Namadgi. Could someone with CAT 1 knowledge please look over the list below and see if we need to buy additional flares. This list was produced 7/2 and I don't know if there have been any recent purchases -- perhaps Michael can advise.

 

We just checked the grab bag and it has many expired flags. We will collect all expired flares for immediate disposal -- any ideas as to where we can dispose of them?

 

kind regards 

Steven

---------- Forwarded message ---------
From: Steven Ring ***@***.*** ***@***.***> >
Date: Sun, 7 Feb 2021 at 22:11
Subject: Namadgi 3 Flares
To: Martin, Michael ***@***.*** ***@***.***> >

 

Hi Michael

 

Inventory of flares as requested:

 

*	All flares are stored in a bright orange flare box with black screw top
*	Located Amidships, cockpit, aft deck/floor locker
*	Correctly indicated on stowage plan

 

Flare Box Contents:

 

*	2 x Para Red Rocket MK8A -- 12/22
*	4 x Shuttle Hand held rocket (RED) -- 06/22
*	2 x Vulcan floating smoke flare -- 07/22
*	3 x Elios red hand held -- 07/22
*	2 x PainsWesssex Orange smoke -- 12/22
*	2 x PainsWesssex red handheld -- 12/22
*	1 x PainsWessex white collision warning hand held -- 9/22

Expired Flares

*	1 x PainsWessex white collision warning hand held -- 9/20 (expired)
*	2 x PainsWesssex Orange smoke -- 11/18 (expired)
*	2 x PainsWesssex red handheld -- 11/18 (expired)

 

Note: There maybe flares in the Grab Bag but I did not check

 

kind regards

Steven

 

-- 

Steven Ring

m: +61 417 495 268

**Comment by smr547** [comment]
Good morning all

 

I thought we’d gone through this for Cat 2.  We had two in-date white flares at that point - one in the flare container and one ready-use mounted high on the bulkhead starboard side just as you’ve come down the companionway.  Can you check again please?

 

Regards

 

Paul

 

From: Simon Dunlop ***@***.***> 
Sent: Thursday, 6 May 2021 10:51 AM
To: 'Steven Ring' ***@***.***>; 'Martin, Michael' ***@***.***>; 'Jones, Paul' ***@***.***>; ***@***.***' ***@***.***>; 'Michelle Grybaitis' ***@***.***>; 'Sam DeLorenzo' ***@***.***>; 'Peter Ottesen' ***@***.***>; 'Peter Lucey' ***@***.***>; 'garth.brice' ***@***.***>; 'Peter Wain' ***@***.***>
Cc: 'CanberraOceanRacingClub/namadgi3' ***@***.***>
Subject: RE: Namadgi 3 Flares

 

For Cat 1 we need to have:

 

S 4.22.1 of Special Reg

6 parachute 

4 red hand held

2 white

4 orange smoke

 

Looks like we need 1 x white hand held. Otherwise we are OK.

 

In NSW RMS hold regular expired flare collection days at various locations. We had one in the Bay a couple of weeks ago and similarly at Bayview. I don’t see any scheduled in the near future. Perhaps we store them in the container until the next collection day.

 

 

All the best

Simon

0412 262 933

 

“If you only listen to people you agree with, you will never learn anything!” 

 

 

 

 

From: Steven Ring ***@***.*** 
Sent: Thursday, May 6, 2021 9:33 AM
To: Martin, Michael ***@***.*** ***@***.***> >; Jones, Paul ***@***.*** ***@***.***> >; ***@***.*** ***@***.***>  ***@***.*** ***@***.***> >; Michelle Grybaitis ***@***.*** ***@***.***> >; Sam DeLorenzo ***@***.*** ***@***.***> >; Peter Ottesen ***@***.*** ***@***.***> >; Peter Lucey ***@***.*** ***@***.***> >; garth.brice ***@***.*** ***@***.***> >; Simon Dunlop ***@***.*** ***@***.***> >; Peter Wain ***@***.*** ***@***.***> >
Cc: CanberraOceanRacingClub/namadgi3 ***@***.*** ***@***.***> >
Subject: Fwd: Namadgi 3 Flares

 

Hi Michael and other friends,

 

We are checking the flares on board Namadgi. Could someone with CAT 1 knowledge please look over the list below and see if we need to buy additional flares. This list was produced 7/2 and I don't know if there have been any recent purchases -- perhaps Michael can advise.

 

We just checked the grab bag and it has many expired flags. We will collect all expired flares for immediate disposal -- any ideas as to where we can dispose of them?

 

kind regards 

Steven

---------- Forwarded message ---------
From: Steven Ring ***@***.*** ***@***.***> >
Date: Sun, 7 Feb 2021 at 22:11
Subject: Namadgi 3 Flares
To: Martin, Michael ***@***.*** ***@***.***> >

 

Hi Michael

 

Inventory of flares as requested:

 

*	All flares are stored in a bright orange flare box with black screw top
*	Located Amidships, cockpit, aft deck/floor locker
*	Correctly indicated on stowage plan

 

Flare Box Contents:

 

*	2 x Para Red Rocket MK8A -- 12/22
*	4 x Shuttle Hand held rocket (RED) -- 06/22
*	2 x Vulcan floating smoke flare -- 07/22
*	3 x Elios red hand held -- 07/22
*	2 x PainsWesssex Orange smoke -- 12/22
*	2 x PainsWesssex red handheld -- 12/22
*	1 x PainsWessex white collision warning hand held -- 9/22

Expired Flares

*	1 x PainsWessex white collision warning hand held -- 9/20 (expired)
*	2 x PainsWesssex Orange smoke -- 11/18 (expired)
*	2 x PainsWesssex red handheld -- 11/18 (expired)

 

Note: There maybe flares in the Grab Bag but I did not check

 

kind regards

Steven

 

-- 

Steven Ring

m: +61 417 495 268

**Comment by smr547** [comment]
Thank you everyone for getting back to me promptly -- wonderfer
communications!.

As Paul noted the second white hand held is mounted above the EPIRB. I'll
close this item and schedule for review in 12 months

kind regards Steven

**Comment by smr547** [comment]
Hi Steven

We have checked the expiry dates for the flares and they have been through a Cat 2 check and passed.
So in my view there is no need to purchase flares.

cheers


From: Steven Ring ***@***.***>
Sent: Thursday, 6 May 2021 9:33 AM
To: Martin, Michael ***@***.***>; Jones, Paul ***@***.***>; ***@***.*** ***@***.***>; Michelle Grybaitis ***@***.***>; Sam DeLorenzo ***@***.***>; Peter Ottesen ***@***.***>; Peter Lucey ***@***.***>; garth.brice ***@***.***>; Simon Dunlop ***@***.***>; Peter Wain ***@***.***>
Cc: CanberraOceanRacingClub/namadgi3 ***@***.***>
Subject: Fwd: Namadgi 3 Flares

Hi Michael and other friends,

We are checking the flares on board Namadgi. Could someone with CAT 1 knowledge please look over the list below and see if we need to buy additional flares. This list was produced 7/2 and I don't know if there have been any recent purchases -- perhaps Michael can advise.

We just checked the grab bag and it has many expired flags. We will collect all expired flares for immediate disposal -- any ideas as to where we can dispose of them?

kind regards
Steven
---------- Forwarded message ---------
From: Steven Ring ***@***.******@***.***>>
Date: Sun, 7 Feb 2021 at 22:11
Subject: Namadgi 3 Flares
To: Martin, Michael ***@***.******@***.***>>

Hi Michael

Inventory of flares as requested:


  *   All flares are stored in a bright orange flare box with black screw top
  *   Located Amidships, cockpit, aft deck/floor locker
  *   Correctly indicated on stowage plan

Flare Box Contents:


  *   2 x Para Red Rocket MK8A -- 12/22
  *   4 x Shuttle Hand held rocket (RED) -- 06/22
  *   2 x Vulcan floating smoke flare -- 07/22
  *   3 x Elios red hand held -- 07/22
  *   2 x PainsWesssex Orange smoke -- 12/22
  *   2 x PainsWesssex red handheld -- 12/22
  *   1 x PainsWessex white collision warning hand held -- 9/22
Expired Flares

  *   1 x PainsWessex white collision warning hand held -- 9/20 (expired)
  *   2 x PainsWesssex Orange smoke -- 11/18 (expired)
  *   2 x PainsWesssex red handheld -- 11/18 (expired)

Note: There maybe flares in the Grab Bag but I did not check

kind regards
Steven

--
Steven Ring
m: +61 417 495 268

**Comment by mrmrmartin** [comment]
I would recommend that we keep flares that have expired.
I would rather have expired flares that none at all.

**Comment by smr547** [comment]
During the CAT 1 audit, @peterottesen has found that the all flares have just expired. @DimitD has ordered a replacement set from Power and Sail.

We must cycle the recently expired flares into the Grab Bag and remove the very old flares. Batemans Bay Marine Rescue will accept the old flares and use them for training. 

Reopening this issue. @mrmrmartin @pauljones17 and @mgrybaitis will be interested

**Comment by smr547** [comment]
I've collected the replacement flares. All on board except one white collision flare.

**Comment by smr547** [comment]
White collision flare purchased by @mrmrmartin
