### ISSUE TITLE
Finalise arrangement for headsail double luff tracks

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#348]
Sam tells me:

* We have the foil installed
* We need our headsails measure (why?)
* Phil may have the fitting that is used to load the sails -- it needs to be returned to the boat

More investigation required.

@peterottesen might know more details.

**Comment by peterottesen** [comment]
We have measured the headsail. The fittings to load the sail from the old Elan foil are in a plastic bag marked with texta and in a cockpit locker or aft locker. Suggest you find and maybe bring to Canberra for storage in the container?

**Comment by smr547** [comment]
Fitting has been found. Closing this issue
