### ISSUE TITLE
Registration proof for EPIRB

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#35]
who: DaveH, Committee

**Comment by mrmrmartin** [comment]
Reg no 5030585503

**Comment by mrmrmartin** [comment]
[EPIRB registration doc for Namadgi 3.docx](https://github.com/CanberraOceanRacingClub/namadgi3/files/1273390/EPIRB.registration.doc.for.Namadgi.3.docx)

**Comment by DeeTaylor87** [comment]
Michael's got it sorted. THANKYOU!
