### ISSUE TITLE
LPG gas sensor faulty -- has been disconnected

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#357]
An LPG sensor in the bilge has failed and has been disconnected from the control unit. A second  sensor behind the stove is functioning. As always, skipper should be alert to the dangers of LPG gas and follow the usual precautions (turning gas off at bottle when not in use).

**Comment by delcosta** [comment]
Steven
The sensor behind the stove has been serviced and is OK.
The other detector might be a little further astern.
I will find it by tracking the wires.
The new detector is on board.

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603

IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail.

From: Steven Ring ***@***.***>
Sent: Sunday, 2 May 2021 21:36
To: CanberraOceanRacingClub/namadgi3 ***@***.***>
Cc: Sam Delorenzo (Delorco) ***@***.***>; Mention ***@***.***>
Subject: [CanberraOceanRacingClub/namadgi3] LPG gas sensor faulty -- has been disconnected (#357)


The faulty LPD sensor is thought to be in the bilge near the stove. It needs to be located and replaced. @delcosta<https://github.com/delcosta> has suggested tracing the wires from the head unit on the port side of the saloon.

**Comment by smr547** [comment]
Sam, Thanks for the clarification on the sensor issue. We will try and locate the faulty sensor before wrapping up the working bee tomorrow. Meanwhile I've modified the wording in the body of the issue and made it an "Alert/Notice to Skippers"

**Comment by smr547** [comment]
New gas sensor has been installed under the bunk in the port aft cabin, inboard near the hot water system. 

System tested and working fine. Two green lights.  Closing this issue and remove from notices.

**Comment by smr547** [comment]
The gas sensor next to the hot water system has failed -- presumable due to water ingress from the leak in the adjacent water hoses. Whitworths have a replacement sensor for $79 (or $69) if we want to solder in a new sensor to the existing housing.

Chris Green suggests installing a 4 wire connector socket adjacent the sensor to remove the need to pull wires through each time a sensor fails (which is one every two years on past experience). I like the idea!!

Reopening this issue for attention in Southport

**Comment by smr547** [comment]
New sensor ordered -- Whitworths Southport -- Jason -- 07 5526 3811,  should be in stock by Tues 24/5

* [Whitworths part no 39859](https://www.whitworths.com.au/gas-detect-sensor-5m)
* [Sensor only](https://www.whitworths.com.au/dvk-monitors-gas-alarm-spare-sensor-head)

**Comment by smr547** [comment]
Sam will pick this up on Saturday

Regarding the gas detectors, I think we should make them "field replaceable" by installing a 4 pin plug at the end of the wire near the detector. We could then stock spares (with plug already fitted) so a faulty sensor could be quickly swapped out by the crew.  I don't like having our gas sensor out of service.

[Here is a link](https://www.jaycar.com.au/m-8-4-way-plug/p/PP4302?pos=19&queryId=809d0d4974da98e735a0ed1236d67564&sort=relevance) to the style of plug I have in mind.

**Comment by smr547** [comment]
Walter from [Brookvale Whitorths](https://contacts.google.com/person/c2546991389271270147) is holding replacement units for us. 

* [full sensor](https://www.whitworths.com.au/gas-detect-sensor-5m) x 1
* [sensor heads](https://www.whitworths.com.au/dvk-monitors-gas-alarm-spare-sensor-head) x 2 as spares

I'll collect these when I go to Sydney see #641 and will make up plug adapters for the operational units and two spares so that they are field replaceable.

**Comment by delcosta** [comment]
Steve
We have one replacement sensor on board (in Nav table) plus a plug which I was going to suggest Damian replace.
Spares would be good

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603
______________________________________________________________________________________
IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail

**Comment by smr547** [comment]
* Two new sensors installed
* One spare sensor on board
* Control Unit re-wired to prevent shorts
* All wires labelled
* tested and working fine

Note: Sensor locations:

1. Under stove
2. Under bunk in stb aft cabin

closing this issue

**Comment by smr547** [comment]
![gas_detector_rewired](https://user-images.githubusercontent.com/4327895/210309504-f63f75e9-14ad-4061-9233-c184428c1579.jpg)
![gas_detector_under_stove](https://user-images.githubusercontent.com/4327895/210309527-4b937133-35a0-487b-978b-ca08daea4de6.jpg)
![gas_detector_working](https://user-images.githubusercontent.com/4327895/210309530-b08702b3-c22b-4c03-b42d-3c87d35c4fd3.jpg)

**Comment by smr547** [comment]
Each sensor is now fitted with a plug to allow for quick replacement. See photos below for correct orientation
![sensor_plug_female](https://user-images.githubusercontent.com/4327895/224182524-82e8493b-6bf2-4476-88b9-99d135391e07.jpg)
![sensor_plug_male](https://user-images.githubusercontent.com/4327895/224182543-5b7af760-8bbb-4ca5-9cb9-55cd53003e4a.jpg)

**Comment by smr547** [comment]
What Spaghetti Bolognese  can do to a gas sensor!!

![damaged_sensor](https://user-images.githubusercontent.com/4327895/224182854-2b08b8ca-74e2-480a-82a2-ce46d8879486.jpg)
