### ISSUE TITLE
Swim deck ladder supports are damaged

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#358]
The stainless steel supports for the ladder have been removed from the swim deck and are being repaired by Pittwater Marine.

**Comment by smr547** [comment]
@delcosta please advice if ladder can currently be used.

@smr547 will followup with Pittwater Marine who are conducting repairs

**Comment by delcosta** [comment]
Steven
It is OK to use swim platform ladder, but should be minimalised until the flanges are replaced.
They should be done by now?

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603

IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail.

**Comment by smr547** [comment]
New stainless steels ferrules have been made and installed by Pittwater Marine. This should solve the problem at least for the time being. There may still be a design issue with the latter. User find it difficult to maintain the latter in a vertical position when climbing out -- ones legs tend to under the platform. When this happens it places a strong force on the ferrules and has a tendency to tear them from their mounting. 

We will watch how this solution works out. Closing this item for now


![IMG_4346](https://user-images.githubusercontent.com/4327895/116867137-e6d45100-ac4f-11eb-8fca-68cb8fd7e327.jpg)
