### ISSUE TITLE
Protection strip for edge of companionway stair sill

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#359]
"Investigate suitable option to prevent barrel bolt damage"

@delcosta please explain

**Comment by delcosta** [comment]
Steven
This is the companionway sill. At the moment things seem to be going OK
The item was predicated on the problem we had on Namadgi 2 where the locking bolt damaged the companion sill and this was a preventative item.
Its probably a monitor item.

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603

IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail.

From: Steven Ring ***@***.***>
Sent: Sunday, 2 May 2021 21:49
To: CanberraOceanRacingClub/namadgi3 ***@***.***>
Cc: Sam Delorenzo (Delorco) ***@***.***>; Mention ***@***.***>
Subject: [CanberraOceanRacingClub/namadgi3] Protection strip for edge of companionway stair sill (#359)


"Investigate suitable option to prevent barrel bolt damage"

@delcosta<https://github.com/delcosta> please explain

**Comment by smr547** [comment]
The working bee team recommended no further action on this issue. Monitor only. Closing.
