### ISSUE TITLE
Registration transfer radio call sign VNCA

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#36]
Maybe even sooner when Namadgi 2 is sold
who: Sam Hughes

**Comment by DeeTaylor87** [comment]
@DaveHolt  see the comment above

**Comment by DeeTaylor87** [comment]
@smr547 Is this relevant any more?  Can it be closed?

**Comment by smr547** [comment]
Closing this item -- historical
