### ISSUE TITLE
Decalcification of WC Pipework

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#362]
* Check, clean or Remove and replace - SOP on prevention
* @delcosta  and @smr547 to provide details for SOP
* Suggest adding bulk vinegar to cleaning shopping list (see #334)

**Comment by delcosta** [comment]
Agree that sop and maybe a video

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603

IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail.

From: Steven Ring ***@***.***>
Sent: Sunday, 2 May 2021 22:36
To: CanberraOceanRacingClub/namadgi3 ***@***.***>
Cc: Sam Delorenzo (Delorco) ***@***.***>; Mention ***@***.***>
Subject: [CanberraOceanRacingClub/namadgi3] Decalcification of WC Pipework (#362)


  *   Check, clean or Remove and replace - SOP on prevention
  *   @delcosta<https://github.com/delcosta> and @smr547<https://github.com/smr547> to provide details for SOP
  *   Suggest adding bulk vinegar to cleaning shopping list (see #334<https://github.com/CanberraOceanRacingClub/namadgi3/issues/334>)

**Comment by smr547** [comment]
Pipework in the forward heads was removed and decalcified. The feed pipe from pan to tank was found to be clogged with hardened calcium to a thickness of about 5mm -- reducing a 40mm pipe to about 25mm effective diameter. Here are some photos

![IMG_4364](https://user-images.githubusercontent.com/4327895/116962855-93631100-acea-11eb-9063-265d6e27bccc.jpg)
![IMG_4367](https://user-images.githubusercontent.com/4327895/116962866-9d850f80-acea-11eb-8f2c-c593a5d1d5d3.jpg)
![IMG_4368](https://user-images.githubusercontent.com/4327895/116962899-b1c90c80-acea-11eb-916b-53518ef1879d.jpg)
![IMG_4370](https://user-images.githubusercontent.com/4327895/116962880-a4138700-acea-11eb-898d-9e34f756cfd9.jpg)


Leaving this issue open until we write a SOP and also clean the other heads.  @peterottesen will be interested.

**Comment by smr547** [comment]
Pipes in the forward heads have been decalcified at this working bee.  So closing this item. 

I'll created new routine maintenance issue for decalcification of each of the heads individually.
