### ISSUE TITLE
Service the windlass

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#365]
Dismantle the windlass, gypsy and clutch. Clean, lubricate and reassemble as per page 17 of the  [Quick windlass manual](https://www.technicalmarinesupplies.co.uk/res/user/3867_dp1-3-5-01b-manual.pdf).

**Comment by smr547** [comment]
Windlass was tested today and found to be ceased. Continue with servicing tomorrow.

@delcosta will be interested

**Comment by delcosta** [comment]
Steven
Ceased?

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603

IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail.

**Comment by smr547** [comment]
Freed the clutch cones from the gypsy and cleaned all components. Greased, reassembled and tested. Clutch is still a bit sticky owing to damage to the lower clutch cone (sand has worked its way between the cone and the gypsy). 

Suggest repeating this service at least annually. Photo attached

![IMG_4348](https://user-images.githubusercontent.com/4327895/117086013-ba731e80-ad8e-11eb-834f-722551d2de99.jpg)

closing this issue
