### ISSUE TITLE
Cat. 1 Safety documents from ESB. AVS, stability, etc

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#37]
who: ESB/PaulMc

**Comment by DeeTaylor87** [comment]
Note Cat One Requirements

3.03.1 | A monohull of   less than 24 m in hull length (measured in accordance with ISO 8666) with Age   or Series Date on or after 1 July 2010 shall have: • Been designed and built   in accordance with the requirements of ISO 12215 Category A. • On board a certificate of building plan review from a notified   body recognised by ISAF. • On board a declaration signed and dated by the   builder to confirm the yacht is built in accordance with the plans reviewed   by the notified body
-- | --
3.03.2 | A   monohull of less than 24 m in hull length (measured in accordance with ISO   8666), with an Age or Series Date on or after 1 July 2010, if subject to any   significant repair or modification to the hull, deck, coach roof, keel or   appendages on or after 1 July 2010, shall have: • The   repair or modification designed and built in accordance with ISO 12215   Category A. • On board a certificate of building plan review for the repair   or modification from a notified body recognised by ISAF • On board a   declaration signed and dated by the builder to confirm that the repair or   modification is in accordance with the requirements of ISO 12215 Category A.
3.03.3 | In   cases when a builder no longer exists a race organiser or class rules may   accept a signed statement by a naval architect or other person familiar with   the requirements of 3.03.1 and 3.03.2 in lieu of the builder’s declaration   required by 3.031 and 3.03.2.

**Comment by DaveHolt** [comment]
Sam DL has the letter from ESB. He will pass it on to Paul Jones.
