### ISSUE TITLE
Fit sliding locking sleeves to swim ladder

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#379]
The swim ladder currently folds under the swim platform when a swimmer attempts to climb the ladder. This is

* very uncomfortable and awkward for the swimmer
* places large stresses on mounting ferrules in the swim deck

One idea is to weld sliding sleeves onto the ladder rails. These would slip over the elbow joint when the ladder is deployed, locking the elbow in place. The sleeves can be retracted in order to fold the ladder for stowage.

Just an idea at this stage. @peterottesen, @PSARN are invited to comment

![swim ladder lock_1](https://user-images.githubusercontent.com/4327895/117711021-1833ba80-b216-11eb-933b-f2a27faa9849.jpg)

**Comment by peterottesen** [comment]
From a distant memory, I thought the ladder swings the other way?

**Comment by smr547** [comment]
LOL. Could be. My memory is distant as well. This was one of those 3AM
ideas I just had to write down. Let's leave it open until someone can have
a good look at the ladder.

**Comment by smr547** [comment]
This won't work -- ladder folds in the opposite direction. Closing this issue
