### ISSUE TITLE
Volvo and Saildrive first service

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#38]
40 hours? After Batemans Bay trip.
who: Ask Douglas Marine
timing: Sep-Oct

**Comment by smr547** [comment]
Booked in with Douglas Marine this week -- Engine is at 50hrs
Reported cross threaded saildrive oil dipstick -- he will fix
Reported black residue from pulley belt -- shane advises that this is normal for a new belt on that engine
Service will be done this week if possible
Shane will liase with BME to arrange to get N3. Shane will need it for 1 day and will return it to Quays. @jphayden and @DeeTaylor87 will be interested in this outcome

**Comment by smr547** [comment]
@DeeTaylor87 @jphayden  please note
I've confirmed that the engine will be serviced on Friday by Shane from Douglass Marine. He is liasing with BME. See note above for the brief I've given him.
IMPORTANT: Shane will deliver N3 back to Quays when the service is done.
Cheers
Steven

**Comment by smr547** [comment]
Need to ask Shane about next service and schedule it into the system

**Comment by smr547** [comment]
Service completed today by Shane of Douglass marine (mobile is 0419985814). Shane reports:

* All good no issues
* Saildrive dipstick replaced
* Residue from belt drive cleaned up. This is normal for a new engine and is not a concern
* 15/40 engine oil should be used for both engine and sail drive
* sail drive oil should be checked frequently -- whenever engine oil is checked. Be concerned if oil is low or milky.
* low coolant level found by @GarthBrice and @peterottesen (1L required) is normal for a new engine. Air pockets form in the hot water system heating loop and these are flushed out in the first few hours of operation. Coolant levels should stabilise now. 
* Full set of spares have been supplied
* ALWAYS leave the seawater cooling valve OPEN -- syndicate boats are particularly prone to inadvertent serious damage if cooling seawater is left turned off -- Never turn this seacock OFF

@jphayden @DeeTaylor87 @DaveHolt @delcosta will be interested in this report.

Closing this issue -- open new one for next service due in 12 mths or 200 hours -- whichever comes first.

**Comment by jphayden** [comment]
Boat is now back at the quays - just confirmed with Dee at Quays that it is there - but she says it will have to go on a mooring on Friday and then be off for the weekend.

Daniel just whatsapped that he can work at the Quays but we need a plan for the weekend

**Comment by jphayden** [comment]
Just Spoke to Dee at Quays again 
We can leave the boat on the mooring Saturday and Sunday , but it has to be gone by 0800 Monday morning - maybe RPA?
