### ISSUE TITLE
Service winches

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#382]
Winches should be serviced annually

**Comment by smr547** [comment]
The maintenance subcommittee discussed the matter

* winches are probably overdue for a service
* servicing would normally done by CORC members
* the committee should endorse  only selected people to work on the winches (it's a skilled job)
* we should consider having the work done in Airlie while the boat is up there (and things are otherwise quiet in the Marina)
* Steven will discuss with Quadrant Marine

**Comment by smr547** [comment]
Garth Brice (@GarthBrice) has serviced all 6 winches in the cockpit. A job well done!! 
![IMG-5374](https://user-images.githubusercontent.com/4327895/144364380-565a9427-abb9-4a62-8923-39270d487b2c.jpg)

![IMG-5375](https://user-images.githubusercontent.com/4327895/144364394-a4e853b5-21fc-4fc3-89ac-3ca136f762ec.jpg)

Closing this issue.

**Comment by smr547** [comment]
Reopening this issue -- servicing is due again (see #757)

**Comment by GarthBrice** [comment]
StevenI stripped all the winches down and serviced them in Opua earlier this year. I doubt that they need another complete service but it would be worthwhile to take the drums off and have a look at the bearings and cones. Kind RegardsGarthSent from my iPhoneOn 23 Dec 2023, at 21:47, Steven Ring ***@***.***> wrote:﻿
Reopened #382.

**Comment by smr547** [comment]
#budget=300 for service kits

**Comment by smr547** [comment]
All winches serviced today. Closing this issue.
