### ISSUE TITLE
Electric toilet pumps are not working -- losing prime

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#383]
These electrical macerating pumps were recently reinstalled - see #376 The pumps were working in Pittwater but seem to have lost prime at sea during the delivery passage North. Need to discuss this with Bill (@bullswool). @delcosta for info.

**Comment by smr547** [comment]
@peterottesen is on board with Steve Rouch and they are prepared to perform surgery on the pipes.

**Comment by smr547** [comment]
Lots of related info on the web -- search "jabsco electric toilet pump bleed tube"

[This thread](https://www.cruisersforum.com/forums/f115/jabsco-electric-head-freshwater-wont-fill-226464.html) is worth studying.

@peterottesen

**Comment by smr547** [comment]
@peterottesen here is the [definitive manual for that pump](http://www.depcopump.com/datasheets/jabsco/29200-0120_Data_Sheet_2002.pdf)

**Comment by smr547** [comment]
Steve Rouch and @peterottesen report that they have solved the problem and have developed a procedure to 

* minimise the risk of recurrence if the airlock
* re-prime the the flush pump in the event of an airlock

A procedure will be written and owners notified by "Notice to Skippers". Well done crew!!

I'm beginning to think that the root cause of this problem is the salt water feed line from the hull fitting to the flush pump is too long. The  plumbing diagram  in the [definitive manual for the pump](http://www.depcopump.com/datasheets/jabsco/29200-0120_Data_Sheet_2002.pdf) shows a very short run. An airlock in a short pipe is MUCH easier to clear compared to a long pipe airlock.   Note that (in the plumbing  diagram) the anti-syphon vents are provided by upstream loop -- not in the main feed pipe. 

We will leave this issue open pending the SOP and also a review of the plumbing.

@delcosta @PSARN and @bullswool will be interested in the progress made.

**Comment by smr547** [comment]
Hi Bill,

Thanks for letting me know. I agree with the idea of shortening the feed
line so that the installation matches the Jabsco manual. It will be
interesting to see the result.

I'd be more comfortable with installing the anti-syphon loop as recommended
in the manual. The risk of someone forgetting to close the valve is too
great. I can't help thinking that the high loop might also help maintain
the prime in the flush pump. At the moment gravity is pulling all the water
out when the boat goes on a heel.

Anyway, much of this may be moot for now. I've just heard from Peter
Ottesen and they are sick of playing with toilets. They are planning to
replace one of the electrical pumps with a manual pump. It's good to have
such a capable crew on board!

Talk soon and thanks again.

**Comment by smr547** [comment]
Aft starboard electric pump has been replaced with a manual pump and is now working reliably

**Comment by smr547** [comment]
I’ve looked closely at this problem during my time on Namadgi over the past 3 weeks. Using a manual pump installed in the aft port heads I made the following observation — While pumping seawater into the bowl with the boat was on a port tack, the pump was drawing air 60% of the time. This was  as a result of the inlet seacock being so close to the waterline — the slight heel of the boat lifted the seacock out of the water.

While this a mere inconvenience for the Jabsco manual pumps it will be a show-stopper for our electric pumps. These pumps are unable to draw seawater once air has been introduced to the feed pipe. 

My observation supports Bill Leslie’s conclusion that these pumps are unsuitable for installation on Namadgi — at least in the aft heads. 

It remains to test the electric pump in the forward heads before consigning these pumps to E-bay and closing this issue.

@bullswool @delcosta @pjwain  will be interested

**Comment by delcosta** [comment]
Thanks Steven
That makes sense.

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603

IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail.

**Comment by smr547** [comment]
Experience has shown that Namadgi 3's water intake lines are often exposed to the air and the electric pumps easily loose prime. A non-return valve is an option but unlikely to solve the problem. We should abandon the idea of having electric toilet pump on N3. Closing this issue.
