### ISSUE TITLE
Outboard Service

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#385]
The outboard is probably due for maintenance. It's starting ok but  running roughly. Crew reports a missing rubber plug on the throttle. Recommend we schedule a service upon arrival in Airlie.

@delcosta will be skipper -- could you organise the service please? @peterottesen for info

**Comment by peterottesen** [comment]
Correction. Rubber plug on main engine throttle lever.

**Comment by delcosta** [comment]
Steve
Noted about the outboard.
It also needs fresh water flush.

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603

IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail.

From: Steven Ring ***@***.***>
Sent: Thursday, 20 May 2021 12:21
To: CanberraOceanRacingClub/namadgi3 ***@***.***>
Cc: Sam Delorenzo (Delorco) ***@***.***>; Mention ***@***.***>
Subject: [CanberraOceanRacingClub/namadgi3] Outboard maintenance (#385)


The outboard is probably due for maintenance. It's starting ok but running roughly. Crew reports a missing rubber plug on the throttle. Recommend we schedule a service upon arrival in Airlie.

@delcosta<https://github.com/delcosta> will be skipper -- could you organise the service please? @peterottesen<https://github.com/peterottesen> for info

**Comment by smr547** [comment]
Outboard booked for service at Coral Seas Marina.

Pick up and delivery, same day service -- if booked early AM

Whitsunday Outboard Centre
17 William Murray Dr, Cannonvale QLD 4802, Australia
+61 7 4946 7286

Talk to Mark


https://goo.gl/maps/d9oCgq13bQSFFgbq8

**Comment by smr547** [comment]
Service booked in for Friday 9/7/21 — Mark will pick up the motor from the roundabout at the marina around 8am and return it serviced by close of business same day. The service will include a fuel refresh (old fuel recycled and new fuel provided). 

I’ll also get a measuring cylinder and spare fuel mixing/storage container (5 litres). All 2 stroke to be premixed in the 5 litre can before being brought onto Namadgi.

@PSARN @delcosta will be interested.

**Comment by smr547** [comment]
Assign this issue to Everything Marine Australia, Coomera for service November 2022
Also note we need to have a list of spares procured for the Pacific Cruise

**Comment by smr547** [comment]
@Christopher-w-green will look at having this service done at Airlie along with the Volvo service.

**Comment by smr547** [comment]
Service completed by Seatech at Boatwork 12/11/22
Next service in 12 months

**Comment by smr547** [comment]
reopening this issue -- service outboard at Boatworks this November

@pcbaston will be interested

**Comment by smr547** [comment]
Recent report: 

The Dinghy motor is stalling at low speed. A service may be required.
Spark plug cleaned but did not fix the stalling issue.

**Comment by smr547** [comment]
Serviced by Sea Tech Marine. Propellor shaft and seals needed to be replaced plus regular service.
