### ISSUE TITLE
Renew Iridium go subscription for offshore cruising

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#389]
To be used for emergency comms and weather file download

@delcosta @GarthBrice are currently organising this for the current cruising season.

**Comment by smr547** [comment]
Closing this issue -- Iridium Go to be renew at next blue delivery.

**Comment by smr547** [comment]
Reopening this issue as a capability we need to have for our Ocean Passage
Sam has offered to renew the subscription and also look at our predict wind subscription.
He will road test the system on the forthcoming Queensland curise.

**Comment by smr547** [comment]
A 12 month subscription has been purchased by @mrmrmartin -- closing this issue

**Comment by delcosta** [comment]
Steve
This must refer to PredictWind subscription as I pay the IrridiumGo monthly (through Predict Wind)
***@***.***

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603
______________________________________________________________________________________
IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail

**Comment by smr547** [comment]
Hi Sam,

I note that the Iridiium Go unit is not registering with the satellite system. Have we elected to allow the subscription to expire?

kind regards
Steven

**Comment by delcosta** [comment]
Steve
Yes, I cancelled the subscription a couple weeks ago...committee directive.



Regards,

Sam DeLorenzo

Mobile & WhatsApp: +61 411 165 835

PO Box 3553, Manuka ACT AUSTRALIA 2603

Sent from my Phone
________________________________

**Comment by smr547** [comment]
Iridium Go needs to be reactivated for the Queensland coast

**Comment by smr547** [comment]
Our Iridium Go number is +881 652 450 614

**Comment by smr547** [comment]
Committee elected not to renew this season -- closing
