### ISSUE TITLE
Liferaft - requires re-testing and installation on deck

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#39]
Vintage 2001 replace? Fit where, needs $900 service now
timing: July
estimate: $3,500

**Comment by smr547** [comment]
Greg Hall has offered to help

**Comment by smr547** [comment]
We also need to decide where to fit it

**Comment by smr547** [comment]
Hi Jack (@jphayden) 

I wonder if you could have a chat with Phil Kavanagh regarding the servicing and installation of the Life Raft? I think Quays can supply the services but it needs some coordinating and on-site assistance

regards
Steven

**Comment by jphayden** [comment]
Will do

**Comment by jphayden** [comment]
This is a reply to a GitHub email – does this help

 

Jack

**Comment by smr547** [comment]
Forwarding extensive email exchange on this topic to github for historical
record
---------- Forwarded message ----------
From: David Holt <david.holt100@gmail.com>
Date: 21 August 2017 at 10:12
Subject: Re: Liferaft
To: Steven Ring <smr@southsky.com.au>
Cc: "Sam Delorenzo (Delorco)" <sdelorenzo@delorco.com.au>, Phil and Wendy
Kavanagh <kavbal@bigpond.com>, john hayden <jphayden@telstra.com>,
"Ottesen, Peter" <Peter.Ottesen@agriculture.gov.au>, Peter Wain <
pjwain@gmail.com>, Bill Leslie <billmargleslie@bigpond.com>, "Martin,
Michael" <mrmrmartin59@outlook.com>, Simon Dunlop <simon@dunlops.id.au>,
Greg Hall <greg@lanterngroup.com.au>, Dee Taylor <87deetaylor@gmail.com>,
Simon Dunlop <srdunlop@tpg.com.au>


The mounting cradle and hydrostatic release are in the store.

David Holt
0439 470 261
Sent from my iPhone

On 21 Aug. 2017, at 09:30, Steven Ring <smr@southsky.com.au> wrote:

I'm going to ask QServices to give us a quote for the liferaft
installation. Garth, PeterO and I had a look at possible mounting points
over the weekend.

There appears to be plenty of room in front of the dodger for the liferaft
to be positioned athwartships, under the boom without fouling the
mainsheet. As Bill points out, the deck may need to be reinforced in that
area. Fortunately there appears to be good access from the saloon ceiling.

Bill has also provided details of the attachment mechanism and the fittings
to be used. I'll pass those onto the QServices shipwright.

Any other thoughts?

regards
Steven

On 18 August 2017 at 21:49, Sam Delorenzo (Delorco) <
sdelorenzo@delorco.com.au> wrote:

> Phil and all
>
> I am keeping a cost of the post hand over works against our budget.
>
> Do we know the cost of servicing and fitting the Liferaft?
>
> Jack, I have the BME quote
>
> Dee,  I am using the Option 1 Quote
>
> Any other quotes out there?
>
>
>
> Regards,
>
> Sam DeLorenzo
>
> President
>
> Canberra Ocean Racing Club
>
> M: +61 411 165 835 <0411%20165%20835>
>
> A: PO Box 646, Woden ACT 2606, Australia
>
>
>
> IMPORTANT
>
> This e-mail and any accompanying attachments are intended for the sole use
> of the addressee(s) and may contain confidential information. If you are
> not the intended recipient (or authorised designee), please disregard the
> contents of this e-mail, notify the sender immediately and destroy all
> copies of this e-mail.
>
>
>
> *From:* Simon Dunlop [mailto:srdunlop@tpg.com.au]
> *Sent:* Thursday, 17 August 2017 9:01 PM
> *To:* Steven Ring <smr@southsky.com.au>
> *Cc:* Phil and Wendy Kavanagh <kavbal@bigpond.com>; Sam Delorenzo
> (Delorco) <sdelorenzo@delorco.com.au>; john hayden <jphayden@telstra.com>;
> Ottesen, Peter <Peter.Ottesen@agriculture.gov.au>; Peter Wain <
> pjwain@gmail.com>; Bill Leslie <billmargleslie@bigpond.com>; Martin,
> Michael <mrmrmartin59@outlook.com>; David Holt <david.holt100@gmail.com>;
> Simon Dunlop <simon@dunlops.id.au>; Greg Hall <greg@lanterngroup.com.au>;
> Dee Taylor <87deetaylor@gmail.com>
> *Subject:* Re: Liferaft
>
>
>
> I agree the liferaft should not be removed. At 56kg and not having easy
> lift point there is too much risk of damage to liferaft and yacht.
>
> Regards
>
> Simon Dunlop
>
> 0412262933 <0412%20262%20933>
>
>
>
> Sent from my iPad
>
>
> On 17 Aug 2017, at 11:08 am, Steven Ring <smr@southsky.com.au> wrote:
>
> Hi Phil,
>
>
>
> Thanks for the advice. I'm with you on both the placement and permanency
> of the installation .
>
>
>
> Bill has raised concerns about the strength of the deck layup in the area
> in front of the dodger and also possible fouling of the main sheet. PeterO,
> Garth Brice and I will look into this over the weekend and report on
> Monday. We will also take advice from the shipwrights at Quays and report
> back to everyone to allow a decision to be made.
>
>
>
> Thank you again for your assistance with this.
>
>
>
> kind regards
>
> Steven
>
>
>
> On 17 August 2017 at 19:25, Phil & Wendy Kavanagh <kavbal@bigpond.com>
> wrote:
>
> Hi Steven,
>
> I think that position immediately in front of the dodger is the best
> place. The option of removing it for cruising around Pittwater is not so
> good as people will often decide to sail to Sydney Harbour at a moments
> notice. The raft weighs 56kg, so the idea of dragging it out of the store
> and fitting it to the yacht and then off again just doesn't get me too
> excited.
>
> RFD have said 2-3 weeks before they will have it ready. Maybe just in time
> for our needs. I'll keep you posted .
>
> Regards,  Phil
>
>
>
> On 17/08/2017 7:07 AM, Steven Ring wrote:
>
> Hi Phil,
>
>
>
> Thank you again for organising this work. The liferaft is a critical
> component for our plans to sail to Batemans Bay.
>
>
>
> The question now is: Where to mount the liferaft on Namadgi 3?
>
>
>
> One possibility is to mount it as it was on the Elan. Directly in front of
> the dodger under the boom. It's also been suggested that we fit the
> liferaft in a manner that would allow it to be easily removed and stored a
> shore during Pittwater cruising.
>
>
>
> Are there any other options?
>
>
>
> kind regards
>
> Steven
>
>
>
> On 16 August 2017 at 18:17, Sam Delorenzo (Delorco) <
> sdelorenzo@delorco.com.au> wrote:
>
> Thanks heaps Phil
>
>
>
> Regards,
>
> Sam DeLorenzo
>
> President
>
> Canberra Ocean Racing Club
>
> M: +61 411 165 835 <0411%20165%20835>
>
> A: PO Box 646, Woden ACT 2606, Australia
>
>
>
> IMPORTANT
>
> This e-mail and any accompanying attachments are intended for the sole use
> of the addressee(s) and may contain confidential information. If you are
> not the intended recipient (or authorised designee), please disregard the
> contents of this e-mail, notify the sender immediately and destroy all
> copies of this e-mail.
>
>
>
> *From:* Phil & Wendy Kavanagh [mailto:kavbal@bigpond.com]
> *Sent:* Tuesday, 15 August 2017 4:25 PM
> *To:* Steven Ring <smr@southsky.com.au>; Sam Delorenzo (Delorco) <
> sdelorenzo@delorco.com.au>
> *Cc:* john hayden <jphayden@telstra.com>; Ottesen, Peter <
> Peter.Ottesen@agriculture.gov.au>; Peter Wain <pjwain@gmail.com>; Bill
> Leslie <billmargleslie@bigpond.com>; Martin, Michael <
> mrmrmartin59@outlook.com>; David Holt <david.holt100@gmail.com>; Simon
> Dunlop <simon@dunlops.id.au>; Greg Hall <greg@lanterngroup.com.au>; Dee
> Taylor <87deetaylor@gmail.com>
> *Subject:* Re: Liferaft
>
>
>
> Hello Everyone,
>
> Just so you know.  Last week Jack phoned and asked me to look after having
> the raft re-certified, so I picked it up from the store on Sunday and sent
> it over to RFD yesterday. They haven't let me know when it will be
> finished, but when it is ready I'll put it back in the store at Mona Vale
> and let you know.
>
> Regards,  Phil
>
>
>
> On 9/08/2017 10:33 AM, Steven Ring wrote:
>
> Sorry Sam,
>
>
>
> I'm a little confused by your reply. I thought the committee decided to
> have the existing liferaft:
>
>    1. serviced and re-certified
>    2. mounted somewhere on deck
>    3. in a position that would allow easy deployment (probably under the
>    boom in front of the dodger)
>    4. in a manner that might allow a crew to remove it temporarily if
>    required (say for Pittwater Cruising)
>
>
>
> Is this correct?
>
>
>
> cheers
>
> Steven
>
>
>
> On 9 August 2017 at 10:19, Sam Delorenzo (Delorco) <
> sdelorenzo@delorco.com.au> wrote:
>
> Jack
>
> The committee decided to re mount the services liferaft.
>
>
>
>
>
> Regards,
>
> Sam DeLorenzo
>
> President
>
> Canberra Ocean Racing Club
>
> M: +61 411 165 835 <0411%20165%20835>
>
> A: PO Box 646, Woden ACT 2606, Australia
>
>
>
> IMPORTANT
>
> This e-mail and any accompanying attachments are intended for the sole use
> of the addressee(s) and may contain confidential information. If you are
> not the intended recipient (or authorised designee), please disregard the
> contents of this e-mail, notify the sender immediately and destroy all
> copies of this e-mail.
>
>
>
> *From:* john hayden [mailto:jphayden@telstra.com]
> *Sent:* Wednesday, 9 August 2017 10:06 AM
> *To:* 'Ottesen, Peter' <Peter.Ottesen@agriculture.gov.au>; 'Peter Wain' <
> pjwain@gmail.com>; 'Steven Ring' <smr@southsky.com.au>
> *Cc:* 'Bill Leslie' <billmargleslie@bigpond.com>; Sam Delorenzo (Delorco)
> <sdelorenzo@delorco.com.au>; 'Martin, Michael' <mrmrmartin59@outlook.com>;
> 'David Holt' <david.holt100@gmail.com>; 'Simon Dunlop' <
> simon@dunlops.id.au>; Sam Delorenzo (Delorco) <sdelorenzo@delorco.com.au>;
> 'Greg Hall' <greg@lanterngroup.com.au>; 'Phil and Wendy Kavanagh' <
> kavbal@bigpond.com>; 'Dee Taylor' <87deetaylor@gmail.com>
> *Subject:* Liferaft
>
>
>
>
>
> Hi all,
>
>
>
> Sending this email in case  anyone doesn’t see the issue on GitHub
> (Steven, have I missed some GitHub way of doing this to this group)
>
>
>
> Phil is going to organise the servicing of the liferaft but we still need
> to decide where to put it and how to mount it. Are we going to get a new
> one some time in the future in which case should we just locate it rather
> than mounting it.
>
>
>
> Regards
>
>
>
> Jack
>
>
>
>
>
>
>
> --
>
> *Steven Ring*
>
> Software Engineer
>
> BSc MIT (ANU)
>
> m: 0417 495 268
>
>
>
>
>
>
>
> --
>
> *Steven Ring*
>
> Software Engineer
>
> BSc MIT (ANU)
>
> m: 0417 495 268
>
>
>
>
>
>
>
> --
>
> *Steven Ring*
>
> Software Engineer
>
> BSc MIT (ANU)
>
> m: 0417 495 268
>
>


-- 
*Steven Ring*
Software Engineer
BSc MIT (ANU)
m: 0417 495 268




-- 
*Steven Ring*
Software Engineer
BSc MIT (ANU)
m: 0417 495 268

**Comment by smr547** [comment]
Comment from Bill:
Hi Steven,
 Sounds good to me, here is some further info., which may or may not be of use to you. The previous liferaft mounting arrangement was, that the cradle was held in place with large self tapping screws, whilst the hold down straps/ hyperbaric release was attached to  Wichard “D” fittings which were thru bolted with large backing plates to distribute the loads. Should you decide to use this arrangement, and have somebody fit the “D”rings, it may be an idea to consider where you are going to put the inflateable dinghy. If it is to be carried on the foredeck (as previously), then you will need similar “D” rings to secure it. These could be fitted at the same time.
My apologies should you already have all this in hand.   Cheers, Bill Leslie.

**Comment by smr547** [comment]
Hello Page,

As discussed, I'd like to get a quote from you to have our liferaft
attached to the deck. The liferaft is currently being serviced but it's
cradle will be brought to the boat this weekend.

We would like to mount the liferaft:


   - under the boom
   - just in front of the dodger but clear of the mainsheet and vang
   - oriented with long side athwartships


We are concerned that the deck in this area may not be strong enough to
support the 56kg liferaft and may need to be reinforced.

The previous liferaft mounting arrangement was, that the cradle was held in
place with large self tapping screws, whilst the hold down straps/
hyperbaric release was attached to Wichard “D” fittings which were thru
bolted with large backing plates to distribute the loads.

We would also have to mount the dinghy on the foredeck in front of the
mast. "D" rings will need to be installed to allow the dinghy to be tied
down.

I'd be grateful if you could give me a quote for this work and an
indication of when your shipwrights might be able to do the job.

kind regards
Steven


-- 
*Steven Ring*
Software Engineer
BSc MIT (ANU)
m: 0417 495 268

**Comment by smr547** [comment]
@DeeTaylor87 -- do you have a photo of the ELAN mounting system for the Liferaft? :D

**Comment by DeeTaylor87** [comment]
Just in front of the Dodger on the Elan there were two D brackets. They were centred on the deck about 20cm apart.  Along the midline of the deck, 62.5cm in front of those brackets there was another D bracket.  Photo soon.

**Comment by DeeTaylor87** [comment]
![life raft fix points](https://user-images.githubusercontent.com/30706096/29771137-9c697caa-8c35-11e7-8a98-5ef52ff63c5b.jpg)

**Comment by jphayden** [comment]
Steven, I have not heard from the Quays, assuming you have not either, I will contact them first thing tomorrow (Thursday)

**Comment by jphayden** [comment]
Reconfirming that I will chase up the quays this morning for their proposal and also ask Phil to check on the life raft servicing 
 Perhaps we also need to review the priority one items for the reposition to Batemans Bay

**Comment by jphayden** [comment]
Phil has just received notification that our liferaft is unserviceable (ie cannot be serviced)
Survivetec Group have quoted for a new one - which would seem to be about $5,500 - to be confirmed

Given this unexpected expenditure, we will have to review our program and financial situation

**Comment by smr547** [comment]
I note that only Dee, Jack and me are participants in this conversation. 

Given that the Liferaft has been deemed unserviceable and needs to be replaced -- 

@delcosta @pjwain @peterottesen @mrmrmartin @DaveHolt and @mrmrmartin should join the conversation.

**Comment by jphayden** [comment]
Ok - There are quite a few liferafts out there. Survivetech group have not got back to me, but as a guide, Marine Safe Australia have a Zodiac 8 person ISO  liferaft which costs $2970 plus $308 for the cradle and $143 for the Hydrostatic release Total $3421 plus delivery

**Comment by jphayden** [comment]
Is anyone an expert on liferafts?

**Comment by mrmrmartin** [comment]
Not me but I think David may have done an analysis of replacement and costs earlier this year.

________________________________

**Comment by DaveHolt** [comment]
I haven't done an analysis, just looked around a bit. An important factor to me is the height profile of the canister for forward vision.

**Comment by jphayden** [comment]
Sent by email:
Quays quote for installing liferaft and Dinghy $1019
Quote for RFD liferaft with cradle and hydrostatic release  $3023

**Comment by DaveHolt** [comment]
Hi Jack,
Do you know what model the proposed liferaft is? I looked at their quote and their website and couldn’t work it out. I’m interested in the cannister height. Sorry if you’ve already been through all this.
Dave

**Comment by DaveHolt** [comment]
Jack, I found the cannister size and other info.

**Comment by jphayden** [comment]
From Bill  - For discussion:

Hi Jack,
  Just in case you haven’t enough on your plate.
  Some thoughts before we rush off  and purchase a liferaft and mount it on the coach house roof.
 
Advantages:      1. The liferaft is out of the way.
                          2. weight is closer to centre of the boat.

Disadvantages: 1. It would require at least 2 people to go up there, in adverse conditions,to release, & deploy the     60kg. raft over the side.- With the boat sinking, the hydro static release would operate, but not  until the boat is about  3m. underwater & everybody is dogpaddling. One would then  need to get    to the raft poste haste,before the   painter breaks the attachment weak link,and the raft  goes            adrift.
                           2. Forward vision from the helm is impaired.
                           3. With the mainsheeting arrangement on the B46, lines may become fouled on the      raft                        whilst   manoevering the boat. 
                           4. UV damage exposure.
                           5. Higher CofG. 

 To my mind, a better arrangement, would be for the raft to be positioned in a purpose built mount, attached to, or being part of the pushpit frame.

      Advantages:  1. It could be deployed by a single person without leaving the cockpit.
                            2. It would be out of the way.

  Disadvantages: 1. Liable to be damaged whilst docking.
                            2. UV damage exposure.

    This may cost a little more, but to my mind, worth it in the long term. Another option might be to purchase two 
   “four man” liferafts. A lot lighter, and able to stow in cockpit floor space. What does everyone think? 

                                                                                                                                                    Cheers, Bill Leslie

**Comment by DeeTaylor87** [comment]
Fitting in the central cockpit locker would be great if that turns out to be an option. I spoke to Greg Hall earlier and he seemed keen on that idea. I think Peter Ottesen was also keen on that idea. I wonder also whether it might work to have one in the central cockpit locker and one in the bow well? Just thinking out loud.

**Comment by DaveHolt** [comment]
Located in the cockpit locker is certainly a neat option. But not a hydrostatic release float free option. For example in a dramatic rapid capsize due to the keel falling off like Cheeki Rafiki, the life rafts will stay stowed away in their lockers. Cheeki Rafiki had their raft mounted under the boom but had no hydrostatic release fitted and they all died.
 
I've seen some rail mounted systems for smaller liferafts. I don't know how well it would work for a 55 Kg 8 person unit. The RFD liferaft quoted is only about 400mm high, quite a bit lower than the old one. Visibility forward is impaired by the mast and dinghy anyway. The B46 is a lot wider than the Elan so hopefully helms persons will be able to see around the side of centre line obstructions.

**Comment by DeeTaylor87** [comment]
Message from Frank Lehmann
I’ve attached a photo taken at the Boat Show showing a very impressive liferaft mount fitted to  an Amel, which Bill and I noted on our rounds. I think something like this could be fabricated for mounting on the pushpit For your consideration.
Cheers,
Frank
![image](https://user-images.githubusercontent.com/30706096/29992472-792241c0-8fdf-11e7-8950-f25723d37a8f.png)

.

**Comment by DeeTaylor87** [comment]
Website for Survitech http://survitecgroup.com/
Here is the list of raft products available. http://survitecgroup.com/product-list-results?category=Liferafts&parentName=&isParent=True&sectorName=Marine  
I can't see which device is being quoted for - can you tell us which one has been quoted @jphayden @DaveHolt @smr547 @mrmrmartin ?

**Comment by DaveHolt** [comment]
The bracket Frank photographed looks really nice. Unfortunately I think at our current berth it would be damaged by the berth piles very quickly. It seems we've already damaged a stanchion. I think the sooner we leave the Quays and its exposed pile berths the less damage we will do to the boat and then we could use a bracket like that.

**Comment by DeeTaylor87** [comment]
I think decision has been made to purchase a 10 man life raft and keep it in the cockpit locker. We checked the size. It should fit. Someone can pick it up on their way up from Canberra later this week. 
[Life Raft Specs.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/1273954/Life.Raft.Specs.pdf)
Specs in the PDF above. Look at the table on the right hand side of the page that says liferaft for 10 people >24hours (which means food supplies packed on it)  I think we have committee agreement on this one!  @smr547 @jphayden @mrmrmartin @peterottesen @DaveHolt @delcosta @pjwain

**Comment by jphayden** [comment]
Just an amendment to this - we discussed a 10 person life raft but it's really up for discussion as to whether we go eight or 10

Please comment - preferably tonight

Driving home
Regards Jack

**Comment by jphayden** [comment]
A bit more info it's the same brochure but the 10 man life raft coss 200 more and from memory is about 12 kg heavier
Regards Jack

**Comment by jphayden** [comment]
Resulting from discussions and feedback from committee members,  I will be ordering the 10 man life raft this morning Wednesday at 9 o'clock-  we will then arrange for it to be picked up somehow.

**Comment by smr547** [comment]
Great news Jack !

**Comment by DeeTaylor87** [comment]
I can pick it up on my way home today. Just arrange the account to be sent through to PW, SD and possibly DH?

**Comment by DeeTaylor87** [comment]
Peter Hicks and Darren from Survitec gave me a tour of the work area today (high visibility vest inclusive). Darren explained the service process and showed me how to secure and deploy the raft. He also showed me the contents of our raft. I will post pictures shortly. The contents are the same as the display except ours does not include epirb and osmosis salt water to drinking water device. Peter Hicks is keen to arrange a visit to Canberra to show club members how to deploy raft etc. We can toss it into Lake BG and make a big bang. Sounds like genuine fun! I am keen to organise. Any takers?

**Comment by DeeTaylor87** [comment]
The following is a display showing the contents of survitec life rafts.  These packs are general packages, so there are some items that are not included in our particular pack. The first picture shows a drinking water osmosis machine which is not included ![life raft pack a](https://user-images.githubusercontent.com/30706096/30098048-ad4941be-9323-11e7-9c53-b363c2127c6c.jpg) The second picture is the same as our pack except that ours doesn't have the epirb inside.
![life raft pack b](https://user-images.githubusercontent.com/30706096/30098049-ae55ea80-9323-11e7-8d11-b1b10a225e87.jpg)

**Comment by jphayden** [comment]
well done Dee - I feel a lot more comfortable about our trip to BB

**Comment by DeeTaylor87** [comment]
Liferaft on board.  Just need to fit in cockpit/secure.

**Comment by DeeTaylor87** [comment]
The liferaft has been temporarily installed in the central cockpit storage bay. It will need a more permanent home as it currently obstructs access to some equipment in that position and does not easily fit into the starboard locker. It looks like we are back to the concept of an on-deck or pushpit storage solution. The committee will need to make a decision on this. @smr547 @DaveHolt @mrmrmartin @peterottesen @pjwain @srdunlop

**Comment by smr547** [comment]
Closing -- replaced by #237
