### ISSUE TITLE
Broken cable protector at base of mast

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#400]
The cable protection at the mast is broken. ![image](https://user-images.githubusercontent.com/32588100/125540651-44fbd037-bb56-44fb-9664-355ac62994f0.jpeg)

**Comment by smr547** [comment]
I think this repair was completed by Pittwater Marine as it was on their list
![IMG-5400](https://user-images.githubusercontent.com/4327895/144689829-abab07fe-527e-49a9-add7-8164d7056b66.jpg)

**Comment by PSARN** [comment]
> The cable protection at the mast is broken. ![image](https://user-images.githubusercontent.com/32588100/125540651-44fbd037-bb56-44fb-9664-355ac62994f0.jpeg)

Sreven,
Looks like is broke in the same place as the repair done by paul jones. I would have thought stainless steel welding would have laster longer than this. Must have been subjected to a significant load, like someone stood on it. @smr547
Peter
