### ISSUE TITLE
Desalination unit air lock

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#401]
Due to an airlock in the desalination unit water was not flowing when the boat pump turned on. The boost pump outlet line was removed bleed and reattached. There appears to be a leak when the system is making water as a small amount of water was found in the Bilge under the boost pump.![image](https://user-images.githubusercontent.com/32588100/125541139-636986cd-5d58-4464-b33f-314874012c67.jpeg)

**Comment by smr547** [comment]
Will be checked as part of #452 -- closing this issue
