### ISSUE TITLE
Battery meter, Blue Seas 

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#41]
Tim Dempsey at Quays will fit it
who: Tim, Jack
timing: July
estimate: $500

**Comment by smr547** [comment]
BlueSeas monitor has been installed. Some issues have been noted -- the unit may need to be recalibrated

**Comment by smr547** [comment]
---------- Forwarded message ----------
From: Steven Ring <smr@southsky.com.au>
Date: 24 July 2017 at 06:52
Subject: Blue Sea battery monitor
To: Jack and Shena Hayden <jphayden@telstra.com>, Bill Leslie <
billmargleslie@bigpond.com>
Cc: "Martin, Michael" <mrmrmartin59@outlook.com>, Dee Taylor <
87deetaylor@gmail.com>, David Holt <david.holt100@gmail.com>


Hi Bill and Jack,

After motoring for a half an hour on Sunday we found the BlueSea monitor
reported the house batteries at 20% state of charge (SOC). This seemed
 unusually low given that the early morning reading that day was 70% SOC.
At the time we noticed this value (see photo) Namadgi was alongside at
Quays and connected to shore power.

A bit of manual reading suggests that the BlueSea computes SOC on the basis
of terminal voltage both during the charging and discharging process. I'm
wondering if the main motor alternator develops a different charge voltage
to the main charging unit (which works from 240V) and this may be confusing
the BlueSea unit. Alternatively, the charge voltage thresholds may simply
be configured to the wrong values in the BlueSea unit.

All skippers need to keep an close watch on the BlueSea unit. I don't think
we are getting a reliable SOC reading.

Another issue is one cannot seem to get a reliable instantaneous charge
rate value (In AMPs) while the batter is charging. The BlueSea unit
initially shows a positive charge current up to about 20A and then switches
to an what seems to be an aggregate value* (in our case about -600A). It is
very difficult to confirm that the battery is charging. Again see photo.

regards
Steven

* on reflection, an aggregate value would be expressed in Amp-hours (Ah)
*not*  Amps (A) -- is -600A a real discharge rate -- if so, things would be
getting pretty warm!! :D

-- 
*Steven Ring*
Software Engineer
BSc MIT (ANU)
m: 0417 495 268



-- 
*Steven Ring*
Software Engineer
BSc MIT (ANU)
m: 0417 495 268

**Comment by smr547** [comment]
---------- Forwarded message ----------
From: Bill & Margot <billmargleslie@bigpond.com>
Date: 31 July 2017 at 10:29
Subject: RE: Blue Sea battery monitor
To: Steven Ring <smr@southsky.com.au>


HI Steven, Sorry about time taken to reply, but have been out of town. You
have probably sorted the problem out by now, but I would have referred this
back to the installer, Was the monitor properly installed i.a.w. the
instructions, and  were the set up procedures followed?  If so the monitor
may need to be returned to Aquavolt for replacement.



Cheers, Bill Leslie.


------------------------------

*From:* Steven Ring [mailto:smr@southsky.com.au]
*Sent:* Monday, 24 July 2017 6:52 AM
*To:* Jack and Shena Hayden; Bill Leslie
*Cc:* Martin, Michael; Dee Taylor; David Holt
*Subject:* Blue Sea battery monitor



Hi Bill and Jack,



After motoring for a half an hour on Sunday we found the BlueSea monitor
reported the house batteries at 20% state of charge (SOC). This seemed
 unusually low given that the early morning reading that day was 70% SOC.
At the time we noticed this value (see photo) Namadgi was alongside at
Quays and connected to shore power.



A bit of manual reading suggests that the BlueSea computes SOC on the basis
of terminal voltage both during the charging and discharging process. I'm
wondering if the main motor alternator develops a different charge voltage
to the main charging unit (which works from 240V) and this may be confusing
the BlueSea unit. Alternatively, the charge voltage thresholds may simply
be configured to the wrong values in the BlueSea unit.



All skippers need to keep an close watch on the BlueSea unit. I don't think
we are getting a reliable SOC reading.



Another issue is one cannot seem to get a reliable instantaneous charge
rate value (In AMPs) while the batter is charging. The BlueSea unit
initially shows a positive charge current up to about 20A and then switches
to an what seems to be an aggregate value* (in our case about -600A). It is
very difficult to confirm that the battery is charging. Again see photo.



regards

Steven



* on reflection, an aggregate value would be expressed in Amp-hours (Ah)
*not*  Amps (A) -- is -600A a real discharge rate -- if so, things would be
getting pretty warm!! :D



-- 

*Steven Ring*

Software Engineer

BSc MIT (ANU)

m: 0417 495 268



-- 
*Steven Ring*
Software Engineer
BSc MIT (ANU)
m: 0417 495 268

**Comment by DeeTaylor87** [comment]
Communication with Daniel from BME 28th August
Hi Daniel, Jack Hayden CORC here. The matters we wanted to address are: Light in the engine bay, provision of fuse kit, check the battery monitor, check the electrical cable on the forward keel bolt, Isolation transformer is noisy, Provision of 12V and 240V circuit diagrams

**Comment by jphayden** [comment]
Spoke to Daniel , BME and asked him to check he installation of  battery monitor I described the problems we had witnessed .

**Comment by DeeTaylor87** [comment]
Chris from BME has tested the monitor and thinks there is a fault. Tim (electrician from Quays) will be speaking to Chris to clarify.

**Comment by DeeTaylor87** [comment]
Chris tested it and found that it was ok with voltages. He checked all the connections frolm the shunt to the meter and it was all fine.  The meter is faulty  when it exceeds 10Amps – works ok at 4 to 5 amps it goes haywire.  It was discharging when he had the engine running.  Jack has taken it to return to the company today (4th September)

**Comment by smr547** [comment]
That's exactly the problem as I saw it. Well done.

**Comment by smr547** [comment]
Closing this one -- Please refer to #217 for more information.
