### ISSUE TITLE
Ground fault isolation ciircuit interruptor 2 pole CB

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#42]
fitted as standard
timing: July

**Comment by DeeTaylor87** [comment]
Has this been done? Can it be closed? @smr547

**Comment by smr547** [comment]
I think @jphayden should check with Dan before we close this

**Comment by jphayden** [comment]
Will discuss with Bill and Dan

**Comment by DeeTaylor87** [comment]
Had a look at this with Bill today. The circuit breaker has been installed in the rear of the aft starboard cabin just above your head as you poke it into the bay (adjacent to the shore power connector plug).
