### ISSUE TITLE
Multi-step regulator to suit 110 amp alternator

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#43]

**Comment by smr547** [comment]
Is this done at the same time as the upgraded alternator

**Comment by smr547** [comment]
BME are doing this today

**Comment by DeeTaylor87** [comment]
I think this can be closed, but will await discussion on Monday with @jphayden

**Comment by DeeTaylor87** [comment]
Balmar Pretolight Leece Neville Model LBA2287  170A 12V   Manuals etc online
