### ISSUE TITLE
Replace diode splitter with voltage control relay

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#45]
timing: July
estimate: $200

**Comment by smr547** [comment]
Wnat is this and what does it do for us?

**Comment by smr547** [comment]
BME are doing this today

**Comment by smr547** [comment]
See #109

**Comment by DeeTaylor87** [comment]
This job is complete

**Comment by DeeTaylor87** [comment]
Discussed with Chris from BME. He explained how the Voltage sensitive relay he installed to replace the diode splitter will help us. This device will charge the batteries in series. First it charges the house batteries, then when the voltage returns to an acceptable level (13.2V) it switched to engage the engine starter. Then when that returns to 13.2V, it switches to the Bow Thruster and charges it. It then keeps all batteries at that Voltage until the engine shuts down. He is also putting in an emergency bypass to run the starter motor off the house batteries in case of emergency.

**Comment by DeeTaylor87** [comment]
The Voltage Sensitive Relay is houses in the engine bay.  It is mounted on a board up above the Engine sea-cock.  The relay is mounted aft of the fuses that have been mounted on the same board. There appears to be two largish black boxes (about the size of a fist each) which makes up the relay.
