### ISSUE TITLE
FWD Head inlet Sea Cock Jammed open

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#450]
Reported By Garth Brice. Recommended replacement  when boat comes out of WATER in  Sydney @SMR

**Comment by smr547** [comment]
The lever for the seacock is moving freely on the shaft but the shaft appears to be seized in the cock. Perhaps the shaft has snapped within the body of the valve.

The entire seacock will need to be replaced at next haulout (14/12)

**Comment by smr547** [comment]
Replaced by Pittwater marine 17/12/21
