### ISSUE TITLE
Water maker won’t start 

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#452]
When following the procedures for operation of the  water maker the system won’t start when the pressure valve is turned.Could be the solenoid not engaging or an air locks. Needs further investigation.

**Comment by smr547** [comment]
Was the water maker switch turned on at the switch panel? Test at working bee.

**Comment by smr547** [comment]
Bill Lesley has found a badly corroded electrical connection in the clutch circuit of the high pressure pump.

**Comment by smr547** [comment]
Bill has tested the system. All working well. He notes that it is hard to bleed the inlet system with the low pressure pump. One just has to be patient and wait for all the air to be purged.

System working OK. Closing this issue.
