### ISSUE TITLE
BBQ Starter and gas switch broken

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#455]
Replace starter and gas switch. The broken gas switch has the potential to leak gas unless not turned off correctly. Safety issue if not fixed quickly

**Comment by smr547** [comment]
Take to Stem First ... during working bee

https://contacts.google.com/person/c7354719018862056511?hl=en-GB

**Comment by smr547** [comment]
Mounting legs lost overboard when dismantling 

[Original manufacturer's website](https://contacts.google.com/person/c7354719018862056511?hl=en-GB)

**Comment by smr547** [comment]
New legs cost $140 [see here](https://cookout.com.au/product/clamp-on-rail-mounts/)

**Comment by smr547** [comment]
Closing this issue as we have replaced the BBQ. Bill Leslie has offered to look at refurbishing the old BBQ which is currenly located in the  storage container in Fyshwick. The old unit is very well made and an overhaul might be worthwhile.
