### ISSUE TITLE
Main Halyard jammer not holding 

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#457]
The main halyard needs maintenance. Replace teet
[IMG_0651 2.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/7567482/IMG_0651.2.pdf)

**Comment by smr547** [comment]
Rigger should shorten the halyard by half a metre or so

**Comment by smr547** [comment]
We will also get Mario to replace the clutch

**Comment by smr547** [comment]
Halyard shortened (to move worn section) and Jammer jaws replaced by Ruel Rigging. New backing plate installed as old one was corroded. Rigger reported that the mounting bolts had been poorly installed and were at the point of failure -- possibly some bodgy work by members?  We should specify that critical work like this be done by a rigger -- or at least inspected

**Comment by smr547** [comment]
Reported as a new problem by John Rowling -- reopening this issue

**Comment by smr547** [comment]
@delcosta inspected clutch and found it to be severely worn. Sam puchased new clutch components but didn't have time to install them.
@mrmrmartin replace one of the jaws  (handle part) but also swapped the halyard to the spinning topping lift clutch. All working OK -- see skippers report #634

@mrmrmartin please summarise final status of the halyard. Will leave this open to be checked at working bee (or associates weekend)

**Comment by smr547** [comment]
Recent users  now seems happy with the clutch operation -- closing this issue, but it should be checked as Routine Maintenance

**Comment by smr547** [comment]
@Christopher-w-green has reported that the main halyard clutch is not work properly en route to Sydney. They have resorted to using the coach house winch to secure the halyard.

Reopening this issue for repairs in Sydney -- @mrmrmartin @peterottesen will be interested.

**Comment by smr547** [comment]
Rigger in Opua has inspected the clutches -- all OK

@mrmrmartin has end-for-ended the halyard and removed some length from the halyard. 

All working well now. The reefing lines and the main halyard marks need to be re-marked.

@peterottesen will look at this for the next cruise

**Comment by pcbaston** [comment]
Peter Ottesen marked 1st Reef in main halyard after it was end-for-ended (turned around).  Working fine during NZ cruising. Issue CLOSED.  Further problems to be recorded as a NEW Issue.
