### ISSUE TITLE
Sail bag support rod end cap

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#458]
The sail bag support rods that are held by the lazy jacks are protruding the end stops

Steven ring to “print” new endcaps
[IMG_0592 3.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/7567468/IMG_0592.3.pdf)

**Comment by smr547** [comment]
Boom bag replacment ?? #423

**Comment by smr547** [comment]
See #494

**Comment by smr547** [comment]
Sail bag replace -- closing this issue
