### ISSUE TITLE
FWD STB Hatch support broken

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#460]
The support for the hatch is broken and no longer attache
[IMG_0655.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/7567489/IMG_0655.pdf)
d

**Comment by smr547** [comment]
Repaired by Bill L and Garth at the recent working bee.

The broken piece was drilled and through bolted before being reinstalled with silicon seal
![IMG-5402](https://user-images.githubusercontent.com/4327895/147136257-210ed538-fa1d-4616-9320-e9c0111fe816.jpg)
