### ISSUE TITLE
HF Radio Licence renewal 

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#467]
Michael Martin has received a letter from ACMA advising that our HF radio licence has expired
[ACMA_Expiry_Notice_20211022_3336763.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/7599173/ACMA_Expiry_Notice_20211022_3336763.pdf)

**Comment by smr547** [comment]
Emailed ACMA requesting a copy of the renewal notice so that it may be paid.

**Comment by smr547** [comment]
Made payment of $45 to renew licence for 12 months.

* Next renewal due 21/10/22
* ACMA client no 20040039
* Callsign VNZ2930
* Lic No: 10757003/1 

[ACMA_Renewal_Notice_C_3277650.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/7605211/ACMA_Renewal_Notice_C_3277650.pdf)

Closing this issue but leaving it as routine maintenance. Diary entry created.

@pjwain and @mrmrmartin will be interested

**Comment by mrmrmartin** [comment]
Thanks Steven
