### ISSUE TITLE
Water leak in exhaust system 

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#469]
Pittwater Marine have identified a  water leak in the exhaust system somewhere between the engine and the cooling jacket. They will investigate further when the boat is alongside next week. This may account for the water and oil mixture accumulating in the engine bilge.

@PSARN , @delcosta and @peterottesen will be interested.

**Comment by smr547** [comment]
Craig from Pittwater Marine has confirmed that there is a corroded part in the exhaust system. A replacement part has been ordered and will be fitted before Christmas. The new part is made of plastic which should eliminate the corrosion problem.

@PSARN @peterottesen @delcosta will be interested

**Comment by PSARN** [comment]
Is there a picture of the corroded part?

**Comment by smr547** [comment]
Not at the moment. I'll try and get one.

**Comment by smr547** [comment]
![muffler](https://user-images.githubusercontent.com/4327895/144561373-fb255f95-da24-4726-8453-d7bf2dec177c.jpeg)

**Comment by smr547** [comment]
Rusted unit was replaced by Pittwater Marine on 17/12/21

**Comment by smr547** [comment]
Water leak continued after repair.

**Comment by smr547** [comment]
Fixed by Josh from Pittwater Marine who gave us an hour of their time before our cruise to Sydney Harbour. The problem was found to be a o-ring which had been damaged in the initial installation.
