### ISSUE TITLE
Water leaking from Volvo seawater pump

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#496]
There is a steady drip of water from the water pump at the front of the engine. It seems to be coming from the house coupling. Only discovered after engine stop so I'll test it later today with the engine running and determine the rate of the leak.

**Comment by PSARN** [comment]
Mark Miller  spoke to Peter Wain toady about the engine leak - the engine is leaking aprox 0.7 Ltrs of sea water into the engine bay per running hour - Suspect water pump or hoses??? 

Mark removed about 6-7 liter of clean sea water today - will need monitoring. and FIXING. @smr547

**Comment by smr547** [comment]
Fixed in Sydney
