### ISSUE TITLE
NEW Fender Step Leaking

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#497]
New Fender step is flat and either needs repair or re-Inflating. May require a pump with the appropriate valve to re-inflate. @smr547

**Comment by smr547** [comment]
I've ordered an [inflation adaptor](https://www.theboatwarehouse.com.au/anchors-chain-fenders-buoys-mooring/fender-accessories/dan-fender-inflation-adaptor/?gclid=Cj0KCQiA_8OPBhDtARIsAKQu0gbzIowLWUIEV-GWyUQpKVfWSdTJnsDWXPQQ86jRaUaI1m_w1r9QUqQaArRBEALw_wcB) and new valve on the assumption that re-inflation is all that is necessary. Failing this we will buy a new fender step at a cost of $160 + delivery.

**Comment by smr547** [comment]
Fender was found to be split and has been replaced.
