### ISSUE TITLE
Stern light arc restricted by position of outboard motor.

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#501]
Many police on Pittwater today and a 3rd party commented on the restriction the outboard motor provided to the arc angle of the stern light. Another Bavaria 46 Crusier (same model newer version) suffered the same problem. ![image](https://user-images.githubusercontent.com/32588100/151655373-301b97ea-2528-4285-bf86-262c77c101f4.jpeg)

**Comment by smr547** [comment]
We moved the mounting bracket about 15cm outboard. Now with  the motor secured in a rotated position the [135 degree viewing angle](https://www.transport.wa.gov.au/imarine/lights-required-on-boats.asp) can be achieved.

See photos.
![IMG-5781](https://user-images.githubusercontent.com/4327895/152110376-55c2332b-4af2-4d3f-a275-0a67b8a7ad4f.jpg)
![IMG-5782](https://user-images.githubusercontent.com/4327895/152110386-925b6c78-bcfa-4bba-8852-552ae7207de2.jpg)
![IMG-5783](https://user-images.githubusercontent.com/4327895/152110396-bdb340af-e6a2-415d-a83e-3cc3e6bc8189.jpg)

**Comment by PSARN** [comment]
Well done

**Comment by smr547** [comment]
Outboard move to give a clear 135 degree arc as required by col regs. Closing this issue
