### ISSUE TITLE
Galley - Dinner plates missing

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#508]
There appears to be 6 dinner plates missing. Only Two remain
![image](https://user-images.githubusercontent.com/32588100/155624830-5bca7b7b-489d-49e1-8b11-951cb0a59edb.jpeg)

**Comment by pcbaston** [comment]
Not a maintenance Issue. If we need plates (due to loss), replace them.

**Comment by smr547** [comment]
We have plenty on board -- closing this issue
