### ISSUE TITLE
Speed Log requires calibration

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#512]
There is a continual one knot offset in the log which usually indicates that the device requires calibration

**Comment by smr547** [comment]
We calibrated the log during race week at Port Stephens

* Did two 1nm runs (NS then SN) across the channel at Nelson Bay at slack tide
* Maintained constant water speed (approx 6.15 knots)
* Logged track information to GPX using Navionics

Later analysed GPX file

* found average SOG to be about 5.65 knots. 
* Computed water speed correction factor to be 0.91 
* Used Airmar Cast application to Bluetooth to DST810 log instrument
* Applied correction factor of -10% to speed reading

Namadgi instruments now showing realistic Drift values that seem consistent with the prevailing tide.

More accurate calibration experiments are recommended to refine the adjustment (especially to allow for heal angle) but these will have to wait until we have a better data collection system attached to the ship's backbone. 

Closing this issue for now.
