### ISSUE TITLE
Navionics does not show the correct EPA 

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#513]
The navionics app does not show the correct EPA and distance after a way-point is inserted
![IMG_EFD763587AE8-1](https://user-images.githubusercontent.com/32588100/155819034-7027fd1b-b461-4fbd-9711-9c7fa3333550.JPEG)
.

**Comment by pcbaston** [comment]
Issue CLOSED.  Navionics is not something CORC can fix using this database.
