### ISSUE TITLE
extend gas bottle compartment

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#52]
(need before major cruise
who: Maybe us if they can't

**Comment by DeeTaylor87** [comment]
Note Cat One Requirements

3.17.4(a) | A sign reading   "REMEMBER Turn Off Gas At Bottle" shall be displayed near any gas   appliance.
(b) | Boats   equipped with gas systems using permanent flames, e.g. a pilot light, shall   be fitted with a combustible gas detection system.
3.17.5 (a) | Disposable   gas cooking canisters used inside the boat must be no more than 225 gram   capacity.
3.17.6 | Gas   bottles, cylinders and reserve canisters shall be contained in separate   ventilated and self-draining compartments where vapour can only escape   overboard.

**Comment by DeeTaylor87** [comment]
Good site on leaking gas cylinders - care and testing protocols
http://www.elgas.com.au/blog/390-turn-your-bbq-off-at-the-gas-bottle-first

**Comment by DeeTaylor87** [comment]
Have asked Darren Skinner 0415 280 048 for quote. He is quoting to extend compartment down to double capacity of gas bottle. New bottle will be harder than old - apparently existing style corrodes quickly.

**Comment by smr547** [comment]
See also closed/duplicate issue #140 which has relevant comments

**Comment by DaveHolt** [comment]
Bill said: Took the liberty to reposition the gas regulator/shutoff valve, in order to fit the 4kg. SS gas cylinder into the existing gas stowage locker. Will need further work at later date such as adjusting hose length and lead angles etc., but the cylinder will fit in OK, cutout side in first. Care should be taken as the guard on top of the cylinder comes close to the shut off valve.

**Comment by DaveHolt** [comment]
The 4.5kg stainless steel bottle now fits thanks to Bill. It is a tight fit. You need to face the cutout to the regulator and manipulate the hoses a bit. Very nice work! Further work could be done but closing the original issue.
