### ISSUE TITLE
Water leak near hot water unit -- system depressurised

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#522]
Persistent spray from inlet pipe. This may explain the periodic unexpected operation of the cold water pressure pump.
![IMG-0145](https://user-images.githubusercontent.com/4327895/160707274-31815792-e216-4878-a8e3-382fa22fc59b.JPG)
![IMG-0144](https://user-images.githubusercontent.com/4327895/160707283-93938bd9-818e-4628-b8d9-2f21f3c241a1.JPG)

**Comment by smr547** [comment]
This problem has not been observed in several months. We will leave the issue open for regular checking.

**Comment by pcbaston** [comment]
Close issue. Regular checking is routine maintenance.

**Comment by pcbaston** [comment]
Piping repaired/replaced. Refer Issue #680 for more details.
Issue CLOSED.

**Comment by smr547** [comment]
Hi @pcbaston 

Unfortunately this problem has happened again to @pjwain. Just yesterday water water was found spraying from a leak near the hot water system and, once again, there has been minor flooding of fresh water into under floor compartments. The pressurised water system is now out of actions. 

In previous posts @delcosta and yourself have suggested ways of fixing the problem including re-plumbing the system, keeping lines long, fixing pipes to bulkhead to ensure that they do not vibrate and are maintained in proper alignment with the fitting. 

In recent weeks @allister-polkinghorne has had to fix an leak in the same area and has recent relevant experience. Once again by trimming the split end and refitting. Yesterdays fault appeared to be the short, blind, blue drain hose which is now only 100mm long. This was the same pipe that leaked for Allister.

Could we all please workshop a permanent solution to this problem?  Chris Smith, our new found plumber, is on standby to work on this problem in the week after Australia Day if we don't fix it in the meantime. If we do proceed with Chris, he will need instructions. @SamMcDonald2538 knows an excellent plumber who might be able to help us while the boat is in Bateman's bay.

noting that issues #680 #522 #426 #583 #748 are records of this problem repeating itself. All these issues have relevant and productive comments.

Making this priority 1 as it is damaging the boat and spoiling peoples time on it.

@CORCpete will be interested not only because he has an upcoming booking.

**Comment by pcbaston** [comment]
Interesting that the drain hose fitting is really the only problem child.
Perhaps it's the fitting or seal that needs replacing. 15mm diam from
memory, unlike RV stuff that's only 10mm. Found a shop in QBYN that only
sells online, but offers pickup previously for spare pipe I took to NZ.
Might be worth a look.

Here's the link to part:
https://www.caravansplus.com.au/jg-tee-15mm-push-on-fitting-p-5416.html
$12.
I thought I also bought the cheap cutter previously to avoid frayed edges
that lead to leaks.....


Paul Baston

**Comment by pjwain** [comment]
I had a closer look this afternoon and the leak appears to be in the short
pipe itself, about half way along its length, not at the connector. Peter W.

**Comment by allister-polkinghorne** [comment]
There is spare pipe, a cutter and fittings on board to fix the pipe. Spare pipe comes in two colours that I think Paul procured previously. Gear is located in fwd port cabin under the seat.

**Comment by pcbaston** [comment]
Peter, that's an easy fix. Well done in locating the source

There is spare pipe onboard. Can't recall where.

The connectors let go if you push in the pipe and hold the centre ring.
Installation is just push in. Same as the 8mm connectors for water filters
if you ever had one.

Paul Baston

**Comment by pjwain** [comment]
Thank you Paul. We found the spare pipe and cutter, and managed to separate
the damaged pipe from the plug connector, but the T-junction connector was
stuck fast, so I'll leave it for you to work on tomorrow. Regards, Peter W.

**Comment by pcbaston** [comment]
👍

Paul Baston

**Comment by pcbaston** [comment]
Problem fixed. Several attempts at repair resulted in a very short tube, which split during Peter Wain's booking 
Compression supports were inserted into old 2' length and reinserted. After a couple of attempts, the connector sealed and leaks were no longer present. A day so far with no leakage. 
Issue CLOSED.

**Comment by smr547** [comment]
Nice work Paul!
