### ISSUE TITLE
Service PFDs

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#524]
PFDs are due for service -- Feb 2022. Only one service agent in Australia

MAJCORTON PTY LTD T/As M.O.S.S. Australia
E30 / 74 Mileham Street
2756 South Windsor

Phone: +61-2-9899 4747

**Comment by smr547** [comment]
These need to serviced in Sydney before the Pacific Cruise -- talk to greg Hall

**Comment by smr547** [comment]
Wondering if Greg Hall can do this when N3 returns to Sydney

@smr547 to call to book the units in.

**Comment by smr547** [comment]
These PFDs are due for service

**Comment by smr547** [comment]
Hello,

We have 8 Secumar PFDs on board of Namadgi 3, our club yacht. You have
serviced these in the past and they are now due for their next service.

Could you please book us in for the service in the first week of December?

Could you please indicate the approximate cost of the service.

kind regards
Steven

-- 
Steven Ring
Maintenance Officer
Canberra Ocean Racing Club
m: 0417 495 268

**Comment by smr547** [comment]
Hi Matt,

Thanks for chatting with me today.

Just a quick note to confirm that we will deliver 8 Secumar PFDs to you on
24 Nov or soon thereafter. We are grateful that you will be able to service
those PFDs with a 2 week turnaround.

Kind regards
Steven

-- 
Steven Ring
Maintenance Officer
Canberra Ocean Racing Club
m: 0417 495 268

**Comment by smr547** [comment]
PFDs will be ready at the end of this week -- Invoice will be emailed to Peter Wain and also to canberraoceanracingclub@gmail.com. Greg Hall had offered to pick these up but I will confirm with him now that N3 is in Batemans -- we may have to make other arrangements.

Interesting comment from Matt at MOSS, who is doing the service

1. Our MOB1 units were mis-installed -- which is a shame because Garth, Peter and I spent a day doing it and we thought we had it right
2. Matt seemed a little perplexed that we purchased the unit's through Geraldine and not directly through him as organised by Paul Jones
3. Matt said his original quote included installation into our Secumar PFDs -- It seems Geraldine's quote did not. 

Perhaps there are some lessons here for CORC

**Comment by smr547** [comment]
PFDs have been service at MOSS

**Comment by smr547** [comment]
Re-opening this issue as the PFDs are due for their 12 months service again -- PFD 5 also needs repair. I've written to MOSS to book a time after N3 returns to Sydney.  

@mgrybaitis @pcbaston @CORCpete

**Comment by mgrybaitis** [comment]
Hi Steve

I'm not sure $500 is enough of a budget for servicing the life jackets. I have this recollection that last year it cost something like $1300. My memory may be faulty.

I'll see if I can find the previous invoice.

Regards

Michelle



Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by smr547** [comment]
I think you might be right Michelle -- Thanks for looking up the detail.

I'll give MOSS a call today to book the jackets in. At least one needs repairing.  The next trick will be to find some spare jackets and willing couriers --  a repeat of the last service.

Let's go for self-service jackets next time -- we have the skills in the club to do this work

**Comment by smr547** [comment]
PFDs have been shipped to MOSS today -- $206.40 shipping including $5k insurance cover.


![IMG-0044](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/185b89ef-1368-467f-bcc5-398faee823f1)
![IMG-0045](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/44397166-449f-48ff-ae10-ecac473bc65e)

**Comment by smr547** [comment]
Documentation from the last service

[Life Jacket Paperwork.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/15071271/Life.Jacket.Paperwork.pdf)
