### ISSUE TITLE
Purchase 240V tester

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#527]
Simple tester with light (non contact)

**Comment by pcbaston** [comment]
What is this Tester for? Non-contact tester????
 Recommend closure and 240V tester be procured IDC if its still a requirement for maintenance.

**Comment by smr547** [comment]
I purchased a low coast Delta tester from Bunnings and put it in the nav station. Indicates the presence of 240V active line when held close to a socket. Great for debugging those annoying "no power" situations

Closing.
