### ISSUE TITLE
Hull clean certificate

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#529]
Prior to departure to NZ

**Comment by smr547** [comment]
A diver needs to clean the hull and issue  a certificate within 30 days of arriving in NZ

@mrmrmartin will be interested in this issue

**Comment by pcbaston** [comment]
Hull was cleaned in Sydney prior to departure from Australia.
Hull Clean certificate provided to NZ authorities at Opua to enter NZ.
Issue CLOSED.
