### ISSUE TITLE
Swim (bathing) platform is inoperable -- new motor drive unit required

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#537]
The motor drive needs to be replaced

**Comment by peterottesen** [comment]
Bavaria spare parts in Europe has a replacement unit (includes motor, spool, line and mounting bracket for about 680 Euros. Might be the best solution, even though the problem is with the plastic spool.

**Comment by peterottesen** [comment]
@smr547 see previous

**Comment by smr547** [comment]
Multiple view of the motor and drive drum mechanism for the swim platform

![Resized-20221006-135539](https://user-images.githubusercontent.com/4327895/194238423-6bce211a-044b-4da2-9273-055a4d3ce334.jpg)
![Resized-20221006-135544](https://user-images.githubusercontent.com/4327895/194238447-87b051b1-507a-42f9-8ad3-a68ba47b7cc4.jpeg)
![Resized-20221006-135551](https://user-images.githubusercontent.com/4327895/194238462-fd5dfb30-25f0-47fd-a38f-575eabe2e8f9.jpg)
![Resized-20221006-135600](https://user-images.githubusercontent.com/4327895/194238474-1ee3d0bc-b293-44d3-b9f0-53e9d2ad697a.jpg)

**Comment by smr547** [comment]
I've asked David O'Shea for a price to machine the part form aluminium. The unit has also been delivered to Baxter Engineering at Hume. Steve in the workshop says it's an interesting job and will give us a price. I'll call him today.

@delcosta will be interested

**Comment by smr547** [comment]
Removing this from the Boatworks list -- we will install the repaired unit in Sydney or Batemans Bay

**Comment by smr547** [comment]
Steve from Baxter Engineering (6280 5688) has quoted $750 + GST to manufacture a new drum and shear pins for the swim platform winch. He can have the unit assembled and ready for re-installation by end November. I've given him the go-ahead as we have timing constraints (David O'Shea said he will required the whole assembly be shipped to him in Brisbane).  Baxter's quote is well under our $1500 budget for this issue.

cc @delcosta @mrmrmartin @pjwain

**Comment by delcosta** [comment]
Steve
I agree we must proceed with the fabrication.

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603
______________________________________________________________________________________
IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail

**Comment by smr547** [comment]
Paul Jones reported

```
The rear platform is manual only and cannot be secured in the closed position (standing/sitting on it is dangerous) and in heavy seas might allow ingress of seawater.
```

We need a SOP to fully document the manual operation -- see issue #609 

The swim platform can be secured closed by tying the lifting line to hard spot near the port wheel

**Comment by smr547** [comment]
The drive mechanism has been repaired by machining a new drum from aluminium to replace the damage plastic drum. Unfortunately, during testing, the new drum was found to have mis-aligned bearing journals at each end resulting in a significant wobble in the drum. The wobble would stress the bearings and the support structure which would soon fail. The drum has been returned to Baxter Engineering so the journals can be "trued".

![IMG-7880](https://user-images.githubusercontent.com/4327895/205646577-c68351b6-3b35-4611-bf90-cd5e91398b9f.jpg)

**Comment by smr547** [comment]
Repaired motor drive is on board. I need to confirm that @DimitD will install the drive at CYCA on Saturday 7/1/22

**Comment by delcosta** [comment]
Swim platform Motor reinstalled, tested and commissioned by at CYCA on Saturday 7/1/22. 
The lowering cut-off microswitch still not working.
Operation still not to wind down past the lowered position.
3 Marks in the on the winch line indicate to stop lowering on 3rd mark. (photo to follow for SOP)
Skipper briefed and this will help control overwind. 
Operation still not to wind down past the lowered position.
This Item can otherwise be closed,

**Comment by delcosta** [comment]
Work done by @delcosta

**Comment by smr547** [comment]
@delcosta -- well done!!

We will close this issue but open another issue noting the malfunctioning "lower limit" micro-switch
