### ISSUE TITLE
Mounting brackets for fuel gerry cans on decks

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#538]
For gerry cans to be mounted on the rails. Peter Ottesen has a good design.

**Comment by peterottesen** [comment]
Based upon observing and discussing with other cruising yacht crews, a simple solution is to install a hardwood boat between the stanchions before and aft of the side stays. It is fastened at each end with a U bolt to the stanchions. The jerry can then be lashed to this board and the side stays.

**Comment by smr547** [comment]
We have purchased a bladder -- see #653 -- closing this issue
