### ISSUE TITLE
Storm Jib bending arrangement

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#540]
We need to develop a mechanism to bend on a Storm Jib while the genoa is furled on the forestay.

**Comment by peterottesen** [comment]
Ben at Hood has advised that they can do this when the boat is in Sydney during December. Modify the storm jib to create a sleeve so it can be hoisted up around the furled headsail.  He will provide a quote.

**Comment by smr547** [comment]
Hoods advise that the altered storm jib has been returned to the CYCA sail locker for collection. 

Do we need it brought to B/Bay for testing?

@peterottesen @mrmrmartin @Christopher-w-green will be interested

**Comment by mrmrmartin** [comment]
Yes but I guess it depends if we can get anyone to pick up and deliver the other stuff (liferaft, PFD's) as well.

**Comment by smr547** [comment]
@mrmrmartin reports 

>The storm jib has been retrieved from the CYCA sail locker and was bent on and tested today. All working fine -- crew happy

Closing this issue
