### ISSUE TITLE
Replace transom bumper rubber

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#542]
On the B46 the bumper rubber extends from the sheerline around the transom at the topsides down to the water line. It has been subject to impact damage and mould deterioration over time. It needs to be replaced at the next opportunity. The part will need to be ordered from Bavaria.

* remove the old rubber
* clean f/glass surfaces
* rebed new rubber

**Comment by smr547** [comment]
@delcosta advises that the length of the rubber trim is 5050mm -- suggest we order a 6m length for the repair.

Sheerline finishing details are can be seen in the attached photos supplied by Sam

![Resized-20221006-140007](https://user-images.githubusercontent.com/4327895/194233487-6ab7294c-4726-45ff-a5cf-55f251966973.jpg)
![Resized-20221006-140018](https://user-images.githubusercontent.com/4327895/194233498-a4b82bff-db5c-4948-9519-87e609444104.jpg)
![Resized-20221006-135959](https://user-images.githubusercontent.com/4327895/194233594-474d7d14-ba37-4a25-b14e-8f968df9d608.jpeg)

**Comment by smr547** [comment]
Not done at boatworks, part not available from Europe. Leave open

**Comment by pcbaston** [comment]
Parts available from SVB in 5m and 10m lengths. Bavaria Part-No. 300527.  Confirm correct profile?
See link:  - https://www.svb24.com/en/bavaria-pvc-skirting-board.html

**Comment by delcosta** [comment]
Paul/Steve
It looks OK to me on the picture, it also looks like the only profile available.

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603
______________________________________________________________________________________
IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail

**Comment by pcbaston** [comment]
I sent an enquiry email re correct part and price/shipping 3 Apr 23.

**Comment by pcbaston** [comment]
From SVB - Bavaria <bavaria@svb.de>

Dear Sir,
Thank you for your inquiry.
The skirting board 300527 is correct. 
We can offer this item as a length of 5m or 10m please check the length you need . Shipping depends on the needed item . Best regards
Christian Naujeck
Sales

**Comment by smr547** [comment]
It looks much better following a cleanup at Boatworks. Considering the cost and disruption of have the bumper replaced I suggest we close the issue and have another look at next haul  out.
