### ISSUE TITLE
Dinghy paddles need to be replaced

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#547]
@pjwain reported: Dinghy paddles: They need replacing. Both are held together with gaffer tape.

@peterottesen and @delcosta will be interested 

We need to find make and model info -- the supplier is in Brookvale

**Comment by peterottesen** [comment]
The paddles are in good condition and do not need to be replaced. The problem is the clips that hold the two halves together.  They have corroded and broken, hence the use of tape. We should seek out new clips. They are easy to fit.

**Comment by smr547** [comment]
@delcosta please, We need make and model of the Zodiac -- maybe even serial number -- so we can order new clips

@pjwain may have records

**Comment by smr547** [comment]
Duplicated by #599 -- closing this issue

Paddles to be ordered via [Sydney Power Boat Centre](http://www.sydneypowerboat.com.au/)

**Comment by smr547** [comment]
Forgot to mention, Roy from Sydney Power Boat Centre said they do not sell the oars and mounting clips separately.
