### ISSUE TITLE
Power outlets not working

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#549]
@pjwain reports: The 240v outlets in the main saloon and kitchen don't work, but the ones in the heads are OK. When the "Sockets" switch on the 240v panel is turned on, it throws one of the circuit breakers; either the one in the lazarette if on "Land" power, or the one in the grey box labelled "Inverter Outlet" behind the saloon lounge if at sea on "Inverter" power. Moreover, the 240v readout flickers badly when at sea on "inverter" power.

@peterottesen and @delcosta will be interested

Try to get an electrician on board in Airlie -- otherwise Boatworks

**Comment by smr547** [comment]
Issues appears to be fixed

**Comment by allister-polkinghorne** [comment]
Repaired... and holding. Need new glue for the repair kit though.
