### ISSUE TITLE
Gas installation routine check

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#551]
A gas fitter should check the LPG installation for safety and reliability

**Comment by smr547** [comment]
Organise a gas check for NZ maintenance window.
@mrmrmartin will follow the gas off procedure

**Comment by pcbaston** [comment]
Why? Is there a legislated requirement?

**Comment by smr547** [comment]
Local gasfitter at The Boatwork says that this certification work needs to be done in the home port of the vessel (Sydney). It  seems that standards vary from state to state (ridiculous).

**Comment by smr547** [comment]
Maybe we need another gasfitter?

**Comment by smr547** [comment]
The gas fitter will be on board tomorrow morning to fix the stove. He will also check the entire LPG installation and issue a new compliance certificate - The certificate costs $350. It's required every 10 years or whenever work is done to modify the LPG installation. We are not at the 10 year mark yet but the check of the LPG is vital given our usage profile and the consequences of any LPG failure.

$budget=$350

@pjwain @mgrybaitis @mrmrmartin @SamMcDonald2538 @DimitD @pcbaston @CORCpete @delcosta @allister-polkinghorne

**Comment by smr547** [comment]
The gasfitter has issued a 
[Gas Supply - Certificate of Compliance_Inspection Report - Licensee's Copy.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/14117509/Gas.Supply.-.Certificate.of.Compliance_Inspection.Report.-.Licensee.s.Copy.pdf)

A new certificate will be issued when the stove is replaced next week -- see #546 

Closing this issue
