### ISSUE TITLE
Obtain MMSI number for radio

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#56]
who: Steven
timing: July

**Comment by DeeTaylor87** [comment]
https://www.amsa.gov.au/search-and-rescue/about-the-gmdss/mmsi-information/

Forms available online

**Comment by DeeTaylor87** [comment]
Note Cat One Requirement

( c ) | Where permanently installed, DSC   HF/VHF transceivers shall be programmed with an assigned MMSI (unique to the   boat), and where there is permanently installed GPS, be connected to a GPS   receiver, and be capable of making distress alert calls as well as sending   and receiving a DSC position report with another DSC equipped station.   Periodically a test call should be made to AMSA which should be automatically   acknowledged.
-- | --

**Comment by smr547** [comment]
The MMSI form is at http://www.amsa.gov.au/forms-and-publications/AMSA89.pdf

**Comment by smr547** [comment]
@smr547 to get form for @mrmrmartin to complete

**Comment by DeeTaylor87** [comment]
Correspondence from Michael

Hi guys
Here is our new MMSI number 503058550 for Namadgi 3 provided by AMSA.
Not sure of the procedure but I believe this number has to be programmed into our radio before the AIS for Namadgi 3 is sent to other vessels.
Richard can you inform us how this is done?
Richard has volunteered to organise the SOP for the radio but we should try and get the radio programmed before we move Namadgi 3 to Batemans Bay.
cheers

**Comment by DeeTaylor87** [comment]
@DaveHolt see information above.

**Comment by smr547** [comment]
Thank you @mrmrmartin for getting the  MMSI number for N3, it is : 503058550
@DaveHolt will also be interest
The MMSI needs to be programmed into the VHF transceiver and also the AIS transmitter.
closing this item
