### ISSUE TITLE
Update AMSA registration of 8 PLBs associate with Namadgi3 include reg number 

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#57]
who: Daveh
timing: July

**Comment by DaveHolt** [comment]
Hi,
please can someone let me know the NSW registration number and/or radio call sign if we have one (VNCA?).
Thanks

**Comment by DaveHolt** [comment]
Closing this one as it is effectively the same as #211

**Comment by smr547** [comment]
Dave, I don't think we can transfer our callsign until we have a HF radio. But Sam Hughes would know for sure
