### ISSUE TITLE
cockpit light - wire a fitting to the table socket to hang from Bimini

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#58]
Do we need to do this?

**Comment by smr547** [comment]
Is there one already??

**Comment by DeeTaylor87** [comment]
There is the cockpit light which fits into the socket of the cockpit table for elegant evening entertainment. 

However, if people aren't happy with that alone, we could always purchase one of these LED battery powered motion sensor lights for the cockpit. https://www.roadtechmarine.com.au/adjustable-led-night-light-bar-with-pir-sensor/p/TLA244  They are small enough to fit into the cockpit table and would be light enough to make night time trips to the cockpit safe and convenient. 
![image](https://user-images.githubusercontent.com/30706096/29756284-2fc820dc-8be6-11e7-9d2d-67557acb180f.png)
I don't think we need to wire anything in.

**Comment by DeeTaylor87** [comment]
@smr547 @jphayden @delcosta  Could this item be closed????

**Comment by smr547** [comment]
There appears to be more to discuss on this item -- we should leave it open.

I agree that we should not wire anything into the bimini -- wires always break (as they did on the Elan). I really like the idea of the portable/rechargeable light. Great hunting Dee!!

Lets see what others have to say. @GarthBrice has lots of experience with cockpit ambience and elegant entertaining :D

**Comment by smr547** [comment]
Closing this item -- historical
