### ISSUE TITLE
Hot Water Service Red Pipe

### ISSUE THREAD

**Issue by delcosta** [CanberraOceanRacingClub/namadgi3#583]
The res Hot water pipe was leaking and Greg Hall cut the leaky bit off (about 35mm) and re-joined it.
As a result the shortened pipework was not able to be re-fixed to the adjacent panel.
The red pipe should be either replaced or otherwise re-fixed to the adjacent panel. See Pics

![HWS N3 1](https://user-images.githubusercontent.com/30795874/200757413-72ac4f6f-efa4-4264-b9c7-25c7e1ed4bfe.jpg)
![HWS N3 2](https://user-images.githubusercontent.com/30795874/200757421-e8453702-bd57-47a3-a3e5-ee3646213f70.jpg)

**Comment by delcosta** [comment]
See that the junction is held in place with a bit of cardboard.

**Comment by pcbaston** [comment]
These connectors are held in under pressure. They are designed to be kept straight (enter with no bends). Bending the pipe at the connector will allow leakage to occur.  I had the privilege of fixing a leak nearby this location in the blue (cold water) line.  
R-All pipes should be long enough to be supported and restrained near the connections to prevent movement.

**Comment by smr547** [comment]
Issue now duplicated by (and is relevant to) #522  -- closing this issue
