### ISSUE TITLE
Cruising Permit for Fiji

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#588]
@peterottesen  -- Some more information:

[iTaukei Affairs Board website](https://www.fijimarinas.com/itaukei-affairs-board-cruising-permits/) outlines the requirement for a Cruising Permit for Fiji.

It seems we could employ an agent to process our application prior to arrival, otherwise we have to do it in person or (as you have mentioned previously) doi it as part of the [Pacific Rally 2023 ](https://www.islandcruising.nz/events/pacific-rally-2023)

There is a need to nominate the Master of the vessel who will be cruising the region. In our case that amounts to 5 people:

 1. Steven Ring
 2. Rob Holland
 3. Dimitri Dermatis
 4. Sam DeLorenzo
 5. John Rowling

I wonder if that might cause a complication which would suggest the Agent is the preferred approach?

BTW: A [Comprehensive 95 page guide to cruising Fiji](https://www.fijimarinas.com/pdf/2020_Fiji_Shores_And_Marinas_Guide.pdf) is also available

**Comment by pcbaston** [comment]
This is not a boat maintenance issue but an operations one.  Suggest close this issue here and take information to Skipper's Notes for Fiji.

**Comment by smr547** [comment]
I agree with Paul's observation that this is not a maintenance issue. I'll close this issue. 

@peterottesen @mrmrmartin @delcosta please note -- I think you are well aware of the requirement for the Fiji Permit as you mentioned it to me in the first place.
