### ISSUE TITLE
Inverter fuse needs new cover

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#589]
Was damaged in April 2021 -- see #377 

![20221115_154629](https://user-images.githubusercontent.com/4327895/201851840-e9e5d4ef-9405-4b70-9fb0-7dda22631bf8.jpg)

@pjwain reported that the fuse is rated at 200A and is in good condition. The Inverter is operational and the problem is cosmetic.

**Comment by pcbaston** [comment]
Is this an issue or not? Yes, agree the damage is cosmetic, but the underlying cause (excessive heat caused by excessive current / bad connection) could cause a fire. Labelled as SAFETY for inspection in Opua.

**Comment by smr547** [comment]
Cover has been replaced. A new label needs to be attached.

Closing this issue
