### ISSUE TITLE
Outboard bracket

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#59]
in store
timing: July
estimate: nil

**Comment by smr547** [comment]
Greg Hall could look at this please?

**Comment by DeeTaylor87** [comment]
RT Marine has these:
https://www.roadtechmarine.com.au/outboard-motor-mounting-pad/p/MGM005
https://www.roadtechmarine.com.au/outboard-motor-brackets-stainless-steel-up-to-7-5hp-motor/p/MGM020
https://www.roadtechmarine.com.au/outboard-motor-brackets-alloy-up-to-20hp-motor/p/MGM015

**Comment by DeeTaylor87** [comment]
We've recovered the outboard bracket from the store and we cna fit it this weekend.  Sam suggests Paul Jones recommendation would work a treat.  https://www.youtube.com/watch?v=NMQPVnmX-0U

**Comment by DeeTaylor87** [comment]
Outboard Bracket fitted.
