### ISSUE TITLE
Damage to gelcoat

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#596]
Note: minor damage to gelcoat port side mid ships due to interference with marina Bollard (cleats)
@smr547

**Comment by PSARN** [comment]
Damages Spot polished out minor damage remains

**Comment by smr547** [comment]
Repair is best left to the next haulout scheduled for Nov 2023 at Boatworks -- I'll keep the issue open until then 

@delcosta will be interested.

**Comment by smr547** [comment]
Repaired at BoatWorks

Closing this issue
