### ISSUE TITLE
Cockroaches on Namadgi

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#597]
Several Cockroaches found on Namadgi. Crew suffering PTSD, shock and horror. Suggest baits be added, before heading to NZ
<img width="515" alt="IMG_7002" src="https://user-images.githubusercontent.com/32588100/204156833-1a8074cf-644c-4c76-9904-2b1dafd3ba2a.png">

**Comment by PSARN** [comment]
Baits deployed on Namadgi

**Comment by smr547** [comment]
Bombed at working bee -- all dead (hopefully)

Closing this issue
