### ISSUE TITLE
Broken oars

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#599]
The two oars are held together with duct tape, In addition the spare blade does not fit the pole. They need replacement 
![IMG_6520](https://user-images.githubusercontent.com/32588100/204728988-f3067d7d-3c9f-4206-922e-c9824877c7ac.jpg)
![IMG_6561](https://user-images.githubusercontent.com/32588100/204729257-2744fc75-1ff6-4211-accf-b4ff8cecf14a.jpg)

@smr

**Comment by smr547** [comment]
Hi Peter, 

Thank you for documenting this problem -- they are quite a mess. Obviously both oars need replacing. And perhaps we should have a spare blade and latching pin?

- [ ] The supplier is [Sydney Power Boat Centre](https://goo.gl/maps/CoKqpL3jbyq6PWvQ7) at Brookvale.
- [ ] @mrmrmartin could you please take a photo of the compliance plate on the zodiac
- [ ] @PSARN, can you order the replacement oars please?

@pauljones17 and @peterottesen will be interested.

**Comment by smr547** [comment]
The contact is [Roy Baskin](https://contacts.google.com/person/c2043467612732898855?hl=en-GB), phone [0400 227 555](tel:+61400227555)

**Comment by smr547** [comment]
Dinghy serial number -- FR-XDC1Z072G819

Roy has paddles in stock. He thinks that we need the 1.6m long paddles. I've asked @mrmrmartin to confirm length of existing paddle and take a photo. We can collect these items when we pick up the safety gear from Greg Hall.

**Comment by smr547** [comment]
Paddled confirmed at 1.6m long by @mrmrmartin 
Placing order with [Sydney Power Boat Centre](http://www.sydneypowerboat.com.au/) today via Roy
![paddle_cropped](https://user-images.githubusercontent.com/4327895/206937255-7eeb5208-c906-4faa-87d0-edfbe0f25b5f.jpg)

**Comment by smr547** [comment]
Order invoice paid today. Ready for pickup from Brookvale.

[dingy_paddle_invoice.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/10251059/dingy_paddle_invoice.pdf)


@pjwain will be interested -- Peter, could you please process claim for $256.65?

**Comment by smr547** [comment]
Replacement oars collected and on there way from sydney see #641 

closing this issue
