### ISSUE TITLE
Cupboard Jamming and hinges loose

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#600]
The bottom cupboard adjacent the oven is Jamed. The problem being if not fixed will result in saucepans spilling onto floor creating a safety hazard.

**Comment by smr547** [comment]
Thanks Peter,

Many of our hinges are rusty and in need of our replacement. Fortunately, Bunnings sell a plug compatible replacement for the existing hinges.

https://www.bunnings.com.au/blum-110-soft-close-full-overlay-hinge_p4160514

I plan to buy a supply of these to take to the working bee and task someone to replace all the broken and/or rusty ones.

@delcosta How are you coming along with a swaging tool for the locker restraints?

<3 loves youse all!!

**Comment by smr547** [comment]
* all offending hinges replaced
* drawer runner screws reattached and reinforced

many thanks to Bob Richards and John O'Donnell -- job well done -- closing this issue
