### ISSUE TITLE
Irridum go download timeout

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#602]
Download limit of 4 hrs reached when downloading predict wind offshore GRIB Files. when the Ocean currents file is selected a download size of 11mb and not achievable using Irridum go with the 4hr limit. Investigating how to utilise past ocean currents dara on newly downloaded GRIB files. All models (6) grib files can be downloaded in 10 minutes over iridium go.
@smr547

**Comment by smr547** [comment]
Timeouts can be controlled by

* specifying smaller areas
* disable some file downloads at requrest time


closing this issue
