### ISSUE TITLE
Swim platform hinges SAFETY

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#603]
The hinge on the port side of the swim platform has lost a grub screw and pin is loose and has the potential to fall out.
@smr

![IMG_6551](https://user-images.githubusercontent.com/32588100/204720392-8e5d415f-5a49-4e6a-9441-248df2914f83.jpg)

**Comment by smr547** [comment]
Comment from Paul Jones  read:
```
The pin in the port pivot point of the platform is loose and was found to be almost disengaged (the grub screw which locates the pin is missing).  This represents a very high safety risk.
```

This is an excellent find. Congratulations to all involved.

**Comment by smr547** [comment]
@mrmrmartin has reported that one of his crew has replaced the grub screw and the pivot point is now secure. 

We will check this fix at Batemans Bay during the working Bee. Will also put the grub screw on the. spare parts list.

**Comment by PSARN** [comment]
The grub screws need to secured with “lock tight” .

From: Steven Ring ***@***.***>
Reply to: CanberraOceanRacingClub/namadgi3 ***@***.***>
Date: Monday, 5 December 2022 at 23:26
To: CanberraOceanRacingClub/namadgi3 ***@***.***>
Cc: ***@***.***" ***@***.***>, Author ***@***.***>
Subject: Re: [CanberraOceanRacingClub/namadgi3] Swim platform hinges SAFETY (Issue #603)


Comment from Paul Jones read:

The pin in the port pivot point of the platform is loose and was found to be almost disengaged (the grub screw which locates the pin is missing).  This represents a very high safety risk.

This is an excellent find. Congratulations to all involved.
