### ISSUE TITLE
Sail Drive Oil Level Low

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#604]
The sail drive oil level is below the minimum level shown on the dip stick. 
Sam Delorenzo advises that there is a vacuum switch in the on the engine that once released will return the oil level on the sail drive to the correct level.
If this statement is true there is a risk of overfilling the sail drive and causing serious damage.
Peter Lucey will investigate this issue with VOLVO and report findings.

 
![IMG_6540](https://user-images.githubusercontent.com/32588100/204723212-e76eef52-ab91-4cc6-b960-2c3f09c7ddc6.jpg)

**Comment by smr547** [comment]
Paul Jones comment was
```
Oil in Sail drive, but it is below minimum mark on the dipstick.  This requires urgent attention.
```

**Comment by smr547** [comment]
@mrmrmartin reports that he has topped up the oil level with about 300ml of oil to restore the oil to the correct level. This is about 10% of the total capacity. Questions remain:

1. Was adequate oil installed when the saildrive was serviced in Boatworks? or
2. Is there oil leaking from the saildrive?

Until we know for certain, skippers should keep an eye on this and report findings to the maintenance team.

@PSARN, could you please update this issue with the advice received from Volvo?

**Comment by smr547** [comment]
250ml added by Michael Martin at beginning of delivery passage. Oil level good at the completion of the passage (see skipper's report #634)

We need to keep an eye on this so I'll leave the issue open. Check during Working Bee and subsequently.

**Comment by smr547** [comment]
I checked the oil level on 22/12 and found it to be clear, clean and at the correct level.

Closing this issue for now with the expectation that skippers will continue to check the sail drive oil level
