### ISSUE TITLE
Refit emergency knives -- cockpit and vang

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#605]
The emergency safety knife is breaking away from its holder. Needs to be rescued.
![IMG_4504](https://user-images.githubusercontent.com/32588100/204726790-f6fde10d-787a-487c-8d64-15035f1b56b6.JPG)

**Comment by smr547** [comment]
Cockpit knife has been refitted thankyou @mrmrmartin  -- we need to do the same with the one at the Vang -- I'll update the title of this issue and leave it open until the Vang knife is fitted

**Comment by mrmrmartin** [comment]
Hi Steve

Peter O and I have looked at this issue and there is no safe place to attach this knife near the mast or on the boom.
So I suggest we keep a spare in the centre table and one attached to the outside of the table and leave it at that.

**Comment by mrmrmartin** [comment]
It might possible to use cable ties to fit the knife sheath against the vang, but we would lose the knife very quickly unless held in place by some shock cord??

**Comment by smr547** [comment]
I'll leave the issue open until you have decided on the best approach. My preference would be to have a knife near the mast. When it's needed, it's really needed!!

@peterottesen @pauljones17 will be interested

**Comment by smr547** [comment]
@mrmrmartin reports

> knife fitted to boom

Closing this issue
