### ISSUE TITLE
Fire extinguisher in Lazerette

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#607]
The Fire Extinguisher in Lazerette has dislodged from bracket. New mounting mechanism required. 
@smr547 
![IMG_4506](https://user-images.githubusercontent.com/32588100/204778209-9e8248aa-a20c-435e-a161-6d7f6489f0fb.JPG)

**Comment by smr547** [comment]
Duplicated by #620. Closing this one
