### ISSUE TITLE
HF radio is locked at a “DSC Watch” screen

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#608]
Paul Jones commented: 

HF radio is locked at a “DSC Watch” screen.  I was not able to progress beyond this screen to select channels/frequencies.  Accordingly, no test transmissions have been conducted. Neither you nor Sam Hughes was able to offer a way ahead.  (The Club website link to the ICOM HF manual takes you to the Iridium GO! Satellite Device Quick Start Guide.  Also, the Club website suggests the HF radio is an ICOM M802.  The fitted unit is an ICOM IC‑M801E).

**Comment by pcbaston** [comment]
The HF radio can toggle between Freq Scan and DSC Scan modes by toggling the DSC button.  Touching DSC button puts the radio in DSC scan/calling mode. Touching the DSC button again toggles back to Freq selection/scan mode. 
This info is not clear in the Operation Manual and will be included in a Operators aide memoire (SOP) being written.
