### ISSUE TITLE
Additional grab rail required

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#613]
@pauljones17 reports:

```
No internal rope grab rail fitted to allow safe movement through Namadgi in heavy weather, after coming down the companionway.
```

One or more additional hard point will be required. Next actions:

- [ ] Specify location of hard point(s)
- [ ] Shipwright to install hardpoint(s)
- [ ] Install suitable rope handrail(s)

**Comment by pcbaston** [comment]
A movable grabline is not ideal for safety. The grab rail needs to be solid.
For discussion Maintenance Sub-committee
@smr547

**Comment by smr547** [comment]
General opinion after the pacific cruise is that this grab rail is unnecessary -- closing this issue
