### ISSUE TITLE
Movement in grab rail port side of companionway

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#615]
initially reported by @pauljones17 

```
There is movement in the grab rail of the port side of the companionway.
```

**Comment by pcbaston** [comment]
Inspected and agree. Will need a l-shaped, short Phillips head screwdriver to access the screw. 5 min job.
![Screenshot_20221213-192302](https://user-images.githubusercontent.com/120452016/207263633-cc027648-b715-47d4-9c60-866a7c98f278.png)

**Comment by smr547** [comment]
That will do the trick. I think Bob Richards has the required too. Perhaps we should acquire a set for the tool kit -- they would help with replacement of other screws in tight places, e.g. kitchen hinges

**Comment by smr547** [comment]
Tighted by @delcosta at working bee -- thanks Sam

Closing this issue

@pauljones17 will be interested
