### ISSUE TITLE
Unpack and reload stuff from store

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#62]
Done basic safety and galley items
timing: July
estimate: nil

**Comment by DeeTaylor87** [comment]
There were a few more things returned by Rob, Wayne and Dee which were stored in the storage bays on the starboard side of the saloon table under the seat.

**Comment by DeeTaylor87** [comment]
Largely completed. We picked the eyes out of what we thought was needed and we have everything we think is needed from there.
