### ISSUE TITLE
Replace wire restraints on galley doors

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#624]
@pauljones17 reports

```
At least two wire galley door restraints have failed such that the door falls past horizontal.
Port side aft and port side midships lower.
```

A perfect task for the working bee.

@delcosta is going to buy a small swaging tool so that we can make our own replacement wires (it may come in handing for other work on board).

Sam, will you have this tool (and the wire/swages) in time for the working bee?

**Comment by delcosta** [comment]
I have made up several wire restraints
Ready to install

**Comment by smr547** [comment]
Wire restraints have been replaced.

Bob Richards recommends putting to restraints on each door. I'll leave that to Sam for comment

Closing this issue

**Comment by delcosta** [comment]
If we are talking all doors, we have cabin hooks, but need more robust hardware to take forces imposed by a slamming door.
I would suggest that a lighter latch system be investigated.
I am happy to continue looking at this.

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603
______________________________________________________________________________________
IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail
