### ISSUE TITLE
Boom bag is too tight -- adjustment required

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#625]
@pauljones17 reports

```
Boom bag is too tight – suggest a new front panel to add some 10cm to the length of the bag.  
Further, engaging and closing the zip on the new sail is so difficult, I suspect many will not persevere.  
Suggest the sailmaker be invited to develop a more user-friendly solution.
```

**Comment by pcbaston** [comment]
Boom bag is fit for purpose and does up easily if the following procedure used for doing up or removing:

1. Move boom to side
2. Fold back bimini
3. Stand on side coming of cockpit (need to ensure sails and reefing lines are inside bag before zipping up
4. Stand on vang/dinghy to get top of bag zipped
5. Slide front peice between mast and spinnaker pole
6. attach zips and zip up one side at a time (it is important to hold panel up to keep zip aligned). Does up easier is panel is not over all the excess spare halyards hanging around mast.

Consider Issue CLOSED.
