### ISSUE TITLE
Annual radio check (HF, VHF, AIS)

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#629]
Complete the [HF Radio Check form](https://cyca.com.au/wp-content/uploads/2021/06/2021-Radio-Installation-Survey-and-Inspection-Form-June-21.pdf)

**Comment by smr547** [comment]
We have run out of time to have this check done at CYCA but we will endeavour to complete an internal check by suitably qualified CORC members as part of the forthcoming working bee.

@pauljones17 will be interested.

**Comment by pcbaston** [comment]
VHF radios working fine. Radio checks completed in BB. Radio check should be performed each time yacht leaves dock/berth.

HF radio working. Receipt of weather from BOM on ch52 ok. I attempted to do a radio test with station VIC as per AMSA website with no luck across multiple freqs. May need to conduct Radio Test at sea away from land clutter.

I note several references to our old callsign that need to be updated to new VNZ2930.

This task cannot be closed out until HF radio check conducted successfully.

**Comment by pcbaston** [comment]
Recommend task be divided into separate tasks for VHF, HF radios and AIS.

AIS was responding correctly?? during the relocation last month, as reported in position reports.  Is there anything that needs to be done such as check connections for signs of corrosion, torn cables, etc?  A quick check on MarinTraffic.com reveals, as of 10:52 on 16Dec22 Namadji's position in Batemans bay as per screenshot.
![Screenshot (2)](https://user-images.githubusercontent.com/120452016/207991043-6af2bac0-3b30-4787-b53e-b8407dc109be.png)

**Comment by smr547** [comment]
Agreed, separate "Routine Maintenance" issues are appropriate for each of these systems. 

Closing this issue
