### ISSUE TITLE
Develop a waiver form for skippers to sign

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#632]
The document asked each skipper to:

- Acknowledge that sailing is a dangerous sport
- Acknowledges that the skipper is ultimately responsible for the safety of the vessel and its crew
- Waiving all rights to sue CORC in the event of an incident

**Comment by smr547** [comment]
For info

---------- Forwarded message ---------
From: Steven Ring ***@***.***>
Date: Sat, 10 Dec 2022 at 10:35
Subject: Re: Skippers waiver
To: Peter Wain ***@***.***>
Cc: CORC Committee ***@***.***>, garth.brice <
***@***.***>


Hi Peter,

Interesting. I've copied Garth in to see if he can find the CORC-specific
document.

Meanwhile I've found the Waiver Document from Sailing Virgins
<https://sailingvirgins.com/waiver/> which could be adapted for CORC --
they are a sailing adventure firm run by a couple of Aussies in the Virgin
Islands so it may not be a good match. Would we be asking each skipper to
provide a waiver on behalf of themselves and their crew. i.e. CORC would
only require the skipper to sign the waiver.

A Google Search "Sailing Club Waiver"
<https://www.google.com/search?q=sailing+club+waiver&rlz=1C5CHFA_enAU1025AU1025&oq=sailing+club+waiver&aqs=chrome..69i57.7834j0j7&sourceid=chrome&ie=UTF-8>
-- has many hits among which may be better templates for us.

Could someone please review some of these documents with a view to adapting
for CORC -- it's a very worthwhile thing to do but I've got no time to put
into it at present. I've created an issue on the Club's Maintenance System
<https://github.com/CanberraOceanRacingClub/namadgi3/issues/632> to track
the discussion.

kind regards
Steven

On Sat, 10 Dec 2022 at 09:11, Peter Wain ***@***.***> wrote:

> Hi Committee, I must say I have no recollection of skippers ever having to
> sign a waiver on the past. Perhaps we could ask Garth for a copy of it.
> Regards, Peter.
>
> On Sat, 10 Dec 2022, 8:23 am Steven Ring, ***@***.***> wrote:
>
>> Colleagues,
>>
>> I was speaking with Garth yesterday and he mentioned that CORC had asked
>> skippers to sign a document in the past before any major cruise or passage.
>> The document asked each skipper to:
>>
>>
>>    - Acknowledges that sailing is a dangerous sport
>>    - Acknowledges that the skipper is ultimately responsible for the
>>    safety of the vessel and its crew
>>    - Waiving all rights to sue CORC in the event of an incident
>>
>>
>> I remember signing such things before going on a training cruise with a
>> Sailing School but the CORC waiver is before my time.
>>
>> It might be worth resurrecting the document for the Pacific Cruise. What
>> does the committee think?
>>
>> regards
>> Steven
>>
>> --
>> *Steven Ring*
>> m: +61 417 495 268
>>
>

-- 
*Steven Ring*
m: +61 417 495 268


-- 
*Steven Ring*
m: +61 417 495 268

**Comment by mgrybatitis** [comment]
I suppose we could do this

**Comment by Bill-Russo** [comment]
This is my comment test

**Comment by peterottesen** [comment]
This is not simple: what about the crews: associates and family/friends?  And pets?

**Comment by Bill-Russo** [comment]
We are still discussing issues like the one Peter has raised and yet we
have only 26 days to departure.
As a committee member I asked at the last meeting who was in the crew and
got no answer.
I am concerned at the lack of information and preparedness for what is a
significant ocean crossing.

Bill

**Comment by pcbaston** [comment]
Surely there is not a legal requirement to do this. It's standard practice. If you want Debenture members (only they can skipper the yacht), then that should be part of the joining process. When I took out a Debenture, I didn't sign anything so sometimes I wonder if ai actually own anything!!! 
Yes, boating is dangerous and all the messaging tells us this. pS. This is not a maintenance item, so take it out of this forum......

**Comment by smr547** [comment]
@pcbaston is quite right, this is a committee only discussion. I'll remove this from GitHub.
