### ISSUE TITLE
Install bungy cord for securing lazarette door

### ISSUE THREAD

**Issue by mgrybaitis** [CanberraOceanRacingClub/namadgi3#633]
Installing a bungy cord will if used prevent the lazarette door from falling down and potentially injuring a crew member.

**Comment by mgrybaitis** [comment]
@smr547 will be interested

**Comment by pcbaston** [comment]
Looked at lazarette hatch. Being heavy, recommend bunggy cord, or solid line, of at least 6mm be used. The meatier the better. A plastic hook is available in the spares box in stowage #19.

**Comment by pcbaston** [comment]
Completed. Procured 1m bunggy from BCF in BB - cost $1.99. Installed with shock cord to spare. May be tightened thru use if desired.
![IMG_20221214_084533043_HDR](https://user-images.githubusercontent.com/120452016/207451380-38d70371-8eb4-403a-89ab-af07007b7f3d.jpg)
