### ISSUE TITLE
Service all toilets

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#635]
This will be done as part of working bee. @delcosta is coordinating the effort.

**Comment by smr547** [comment]
All toilets were thoroughly serviced and tested. New pumps installed and working well. Great work @delcosta and @DimitD 

It is absolutely critical that the black water tanks NOT be allowed to overfill. It leads to diabolical problems (hydrolic lock)in the systems from which there is only two remedies:

* go to a marina pump out station
* pump the tank out 

OR 

* remove breather tube from the top of the tank
* dump the tank to sea
* flush breater tube from topside inwards (tought to do at sea)
* re-attach breather tube


@mgrybaitis @mrmrmartin @Christopher-w-green will be interested

closing this issue

**Comment by mrmrmartin** [comment]
Excellent work guys and good info for all members

**Comment by smr547** [comment]
Colleagues,

Please review my previous instructions in GitHUB -- I missed a couple of important steps mainly

* First remove pumpout deck cap to partially relieve pressure in the system
* some of these steps are messy
* Possible adaptation of the deck seawater hose (pullpit) to allow breather tubes to be flused at sea

I'll create a task on github for this last step


@mgrybaitis @mrmrmartin @Christopher-w-green will be interested
