### ISSUE TITLE
Grille on galley stove top in danger of collapsing

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#639]
@JCRowling reports that the grille has corroded and is in danger of collapsing completely. It's certainly in a bad way and one suspects that it is chrome plated mild steel rather than the much more durable stainless steel.

![stove_grill_failing](https://user-images.githubusercontent.com/4327895/208227605-f1afc672-642d-4e19-9ba5-2e17c4de8ffa.jpg)

Thanks for reporting this John

**Comment by smr547** [comment]
Our associate member Bob Richards from Batemans Bay has used his welding skills to fabricate a new grille from stainless steel sourced locally. @mrmrmartin reports the new unit is very sturdy and requires only a little adjustment before it is reinstalled tomorrow by Bob.

The committee will be please to know that a few associates including Bob have emerged to help with the working bee. I'll provide a separate report on the working bee at the end of next week.

@JCRowling @mgrybaitis @peterottesen @Bill-Russo @pjwain and @delcosta will be interested

Leaving this issue open until the final fitting

**Comment by Bill-Russo** [comment]
Thank you Bob!!!

**Comment by mrmrmartin** [comment]
Hi Bill

I met Bob on Saturday at the boat - he has made a much stronger looking grill which needs a little refinement before it can be put in place.

cheers

**Comment by Bill-Russo** [comment]
👍

**Comment by smr547** [comment]
Bob Richards has done a fabulous job in fabricating a new stove top grille -- we must extend special thanks to him

@mrmrmartin and @Christopher-w-green will be interested. Closing this issue
