### ISSUE TITLE
EPIRB - source and mount it — got it, mounting required

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#64]
GME to donate - requires registering with AMSA
timing: July
estimate: $350

**Comment by DeeTaylor87** [comment]
EPIRB has been mounted

**Comment by jphayden** [comment]
Has the EPIRB been registered with AMSA. As I am on the BB trip it would be comforting to know that it had

**Comment by smr547** [comment]
Yes it has.
