### ISSUE TITLE
First aid kit -- review and replenish

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#644]
Review the first aid kit and replace items that are out of date or missing

**Comment by smr547** [comment]
Peter O is doing the CAT 1 checklist. Before we pull out the First Aid kit for a thorough review, does anyone know if the First Aid kit has been reviewed lately?

@peterottesen @mgrybaitis @mrmrmartin @pauljones17 @pjwain @Bill-Russo @PSARN @delcosta

**Comment by mgrybaitis** [comment]
I will review the Medical Kit against Cat 1 checklist over the next few days and will purchase and replacements required.

**Comment by PSARN** [comment]
All the prescription medication have been replaced, as all out of date.

From: mgrybaitis ***@***.***>
Reply to: CanberraOceanRacingClub/namadgi3 ***@***.***>
Date: Thursday, 22 December 2022 at 12:21
To: CanberraOceanRacingClub/namadgi3 ***@***.***>
Cc: ***@***.***" ***@***.***>, Mention ***@***.***>
Subject: Re: [CanberraOceanRacingClub/namadgi3] First aid kit -- review and replenish (Issue #644)


I will review the Medical Kit against Cat 1 checklist over the next few days and will purchase and replacements required.

**Comment by smr547** [comment]
The Medical Kit has been refreshed:

- [x] @PSARN has replenished all CAT 1 drugs
- [x] @mgrybaitis has reviewed the first aid kit and replaced expired items

I'll leave this issue open pending a pre-departure check by @mrmrmartin and @pauljones17 prior to the Sydney -> NZ passage

**Comment by smr547** [comment]
This has been checked by @mrmrmartin and @mgrybaitis 
Closing this issue
