### ISSUE TITLE
Galley Stove - conduct service

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#649]
Techimpex gas stove 

Supplier -- [MyYacht](https://www.myyacht.com.au/) , Milsons Point, 02 9925 0071 contact Mia admin@myyacht.coma.au

No longer import these units -- supplier holds only limited parts.

- [ ] Burners are rusty and appear to be rusted in place (screws difficult to remove)
- [ ] General rust developing
- [ ] Stove grille 

Consider purchasing a new stove to fit:

* 500 x 400 x 400 (w x d x h)
* Clear opening 545 x 490. (w x d x d)

**Comment by pcbaston** [comment]
Stove top plates have been repaired and stove operated correctly during NZ3 cruise, both burners and oven.  Suspect this issue can be closed.

**Comment by pcbaston** [comment]
No further isues from all NZ bookings. Issue closed.
