### ISSUE TITLE
Install Radar Reflector

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#651]
Recommended by World Sailing -- [Offshore Special Regulations](https://www.sailing.org/tools/documents/WSOffshoreSpecialRegulations20222023v2-[27823].pdf)

**Comment by smr547** [comment]
@pauljones17 and @peterottesen  -- Should we get one a [hoistable radar reflector](https://www.whitworths.com.au/safety-radar-reflector-octahedral) to cover the fact that we don't have a permanently installed reflector?

**Comment by pauljones17** [comment]
Cheap but nasty.  Have to find all the bits and one nylon bracing piece invariably goes missing - rendering the unit U/S as I recall.  And even when it can be assembled, what's the plan?  Hoist it every evening at sunset or in fog?  I note the Whitworths $52.95 aluminium radar reflector does not mention reflective area.
Consider it better to cut to the chase and install a permanent radar reflector.  Suggest a Echomax EM230MIDI Midi Radar Reflector - 9 Inch which reportedly has a 20m2 radar cross section and weighs 1.9kgs. Cost is some $300 plus P&P.
By way of comparison, the shroud radar reflector ($84.95 at Whitworths) has a radar cross section of only 4m2 - better than nothing but ....

**Comment by smr547** [comment]
Thanks for the comment Paul!! Very useful information. I've taken the liberty of inserting links for the devices you've mentioned.

I consider any cruising yacht should present as large a radar return as possible especially if transiting busy shipping areas (e.g. East coast of Australia). While being chased by a coastal merchant ship off Cape Byron I radioed the vessel on Ch16. The skipper responded by say "We have you on radar Namadgi and will pass your port side" -- interesting she did not say "we have you on AIS" 

Conclusion: Radar reflector possibly not so critical for the immediate sailing plan. In any event we have run out of time to secure and mount the permanent solution. Unless there are other thoughts I'll put this on the work list for BoatWorks, Nov 2023

The committee may wish to review this discussion @peterottesen @pjwain @delcosta @mrmrmartin @mgrybaitis @Bill-Russo

**Comment by pauljones17** [comment]
In view of the time constraints, and considering the relative ease of installing a shroud radar reflector, perhaps that could be the temporary solution.  Would just need to be careful it doesn't become permanent, because you never know you need it until you need it.  My CORC delivery to Noumea almost ended the first night in the shipping channels off Sydney in poor visibility, when a merchantman appeared almost above us - clearly hadn't seen us at all.

**Comment by peterottesen** [comment]
I remember fixing Paul McDonald’s shroud radar reflector while in NZ this year. Simple to install but careful consideration is required to avoid tangles from sails, running gear etc.

**Comment by smr547** [comment]
A [Radar Reflector](https://www.whitworths.com.au/sfty-rad-reflec-lge) has been purchased and left on board. Installation in the upper shrouds is required.

**Comment by smr547** [comment]
Installed by @mrmrmartin 's crew
