### ISSUE TITLE
Diesel fuel bladder to extend cruising range --  stowage and SOP

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#653]
* To be stored in Port cockpit seat locker
* SOP to be developed for fuel handling (see also CanberraOceanRacingClub/SOPs#14)

A lot of work has been done on this by @mrmrmartin. I'll capture the email trail in comments at a later time.

**Comment by smr547** [comment]
Hi @mrmrmartin -- can we please discuss commissioning of the bladder (i.e. filling it for the first time)? Some thoughts:

* ensure all fittings are secured tightly and with appropriate plumbers tape (what tape is specified, if any?)
* fill with air and check for leaks
* ensure main diesel tank is NOT full and has capacity to accept ALL diesel placed into the bladder (just in case of a leak)
* part fill the bladder with diesel and test for leaks
* test the dispensing process by transferring diesel from the bladder to the main tank

Only when testing has been completed should the bladder be filled to capacity.

**Comment by smr547** [comment]
Hi @mrmrmartin and @Christopher-w-green. I've had some further thoughts on commissioning the bladder. 

I think we should initially test the bladder by filling it with AIR, and NOT diesel fuel. I recommend:

1. Fitting the cap to refilling spout (or whatever amended refilling pipe is fitted)
1. Fit the dinghy inflation pump to the outlet tube of the bladder (thanks Chris for this idea!)
1. Open the outlet valve
1. Pump the bladder full of air with the foot pump
1. Close the outlet valve -- the bladder should remain inflated
1. Place some weights on the top of the inflated bladder to further compress the air inside

With this done...

1. check the fittings for air leaks by listening and applying soapy water to the joints
2. check their is not outflow from the ball valve
3. leave the inflated bladder overnight to ensure that no air is lost

**Only when this test passes** should a test with diesel fuel (see my previous comment) be considered.

**Comment by smr547** [comment]
Hi @Christopher-w-green 

When we first test the bladder with diesel (Sydney, next week) it could leak from one or more of the fittings -- a situation that will required the bladder to be  completely emptied prior to repair. We need spare capacity in the fuel tank (and/or the gerry cans) to accept the fuel from the bladder.

Could you please consider NOT refuelling in Shellharbour and, instead, run down the fuel in the main tank. The aim would be to arrive in Sydney with minimum fuel in the tank.  There is a reserve of fuel in the Gerry cans on board (80L I think). That could be transferred to the main tank if required (leaving one or more cans empty).

You will want to avoid running out of fuel during normal operation of the engine. The faulty fuel gauge is not helpful in this regard. 

kind regards
Steven

cc @mrmrmartin

**Comment by Christopher-w-green** [comment]
Ok. Not having to use the motor much. About an hour yesterday.

Got a missed call on the tablet yesterday.  So that was you, then.

Chris

**Comment by smr547** [comment]
Hi Michael,

I've arranged for Ivan Tesvic to come to Trilogy on Monday afternoon to help with the fuel bladder. Ivan is Diesel mechanic with long experience in navy submarines. He can help with any remaining issues. Or, if everything is sorted, give it the final tick of approval.

His contact details are

[ivantesvicmarine@gmail.com](mailto:ivantesvicmarine@gmail.com)
0418 462 646

@pauljones17 and @Christopher-w-green will be interested. @mrmrmartin

**Comment by smr547** [comment]
@mrmrmartin reports that the bladder has been tested overnight with air -- no leaks. Today the bladder was tested with diesel with no leaks

This is a great outcome -- well done Michael. Closing this issue
