### ISSUE TITLE
Install OpenCPN (and relevant ENC charts) onto the Samsung Tablet plus

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#657]
The ENC charts are official charts issued by the various hydrographic services. They replicate and exceed data normally printed on paper charts. Regular chart updates are available online for download

Based on a suggestion by @pauljones17, @Christopher-w-green has is most knowledgeable when it comes to the Samsung tablet.

Other parties interested might include the committee and other skippers ... @mrmrmartin @mgrybaitis @pjwain @peterottesen @Bill-Russo @delcosta @GarthBrice @PSARN @pcbaston

**Comment by smr547** [comment]
I'm installing OpenCPN on my Samsung Tablet by following [these instructions](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:android)

* first thing to note is to load the **Dave Register** version of OpenCPN for Android via the Google Play Store -- this will cost you $14.05  but you will end up with OpenCPN version 5.6.2 -- the current version according to the [OpenCPN website](https://www.opencpn.org/index.html)

**Comment by Christopher-w-green** [comment]
OpenCPN has a version for Android available on the Play Store. It's not free, costs $15 or so. I bought a copy for my own tablet. Official government issued ENCs are available free for New Zealand, including some of the Pacific. I've downloaded the base chart but further charts require registering and having  a S-63 license which appears to need a number from your chart plotter device. Don't know how that works for downloading onto a tablet or computer. The NZ govt site is closed for new registrations until 3 Jan,so I can't try it out before I take Namadgi on 2 Jan. Australia ENCs are for sale by Boat Books, at a cost of over $700. We have Australia already loaded on the chartplotter so I don't see any point in purchasing those. O-carts.org sells Australia charts for a more reasonable €35, but these are not "official" even though they have been taken from official sources.

**Comment by smr547** [comment]
Chris Green finds a problem with Android OpenCPN...

---------- Forwarded message ---------
From: Christopher Green ***@***.***>
Date: Wed, 28 Dec 2022 at 17:56
Subject: Re: New Zealand: ENC now in S-63 format for free - Cruisers &
Sailing Forums
To: Steven Ring ***@***.***>


I admit defeat. Seems you can't get an S-63 permit for Android.  You'd need
to put it on a laptop or compatible plotter. So that's it. Can't get NZ ENC
charts for the tablet.

The downloadable NZ chart through opencpn is a no-longer-supported rasta
chart. It's there, but navionics is better.

I was not keen to try and learn how to use opencpn anyway. The user manual
is over 1000 pages.

On Wed, 28 Dec 2022, 2:21 PM Steven Ring ***@***.***> wrote:

> Agreed! I'm gobsmacked that the Hydrographic Office thinks that all ENC
> users are rich shipping companies
>
> On Wed, 28 Dec 2022, 2:11 pm Christopher Green, <
> ***@***.***> wrote:
>
>> Yep
>>
>> Reckon our first best option is still Navionics charts on the plotter.
>> That's good enough for a recreational cruising yacht. We are not a
>> commercial vessel so there's no requirement for us to have "official"
>> charts.
>>
>> On Wed, 28 Dec 2022, 2:06 PM Steven Ring ***@***.***> wrote:
>>
>>> Nice work Chris.
>>>
>>> I've just been examining the burning hoops we have to jump through to
>>> get the "Official ENC" charts for Australia -- not to mention the
>>> extraordinary costs.  And then you have to buy it all again next year!!!
>>> WFT!!!
>>>
>>> Anger rising!!
>>>
>>> On Wed, 28 Dec 2022, 1:46 pm Christopher Green, <
>>> ***@***.***> wrote:
>>>
>>>>
>>>> https://www.cruisersforum.com/forums/f134/new-zealand-enc-now-in-s-63-format-for-free-237548.html
>>>>
>>>>
>>>

-- 
*Steven Ring*
m: +61 417 495 268

**Comment by smr547** [comment]
Steven also capitulates

---------- Forwarded message ---------
From: Steven Ring ***@***.***>
Date: Wed, 28 Dec 2022 at 19:14
Subject: Re: New Zealand: ENC now in S-63 format for free - Cruisers &
Sailing Forums
To: Christopher Green ***@***.***>


Hi Chris,

I'm with you on this. The same conclusion but from a different perspective.

I downloaded the full set of NOAA ENC charts from US Coast Guard -- all
free and unencrypted. I  finally managed to get Android OpenCPN to index
them (after annoying incompatibility problems with the micro SD card reader
-- not supported but no error messages) and finally incorporate the charts
into the display. The result was hopeless. I was unable to get a coherent
chart display of any use. The "chart bar" option was a mess. The
auto-merging of different overlapping charts of different scales simply
failed.

Hopeless, barely describes the outcome!! OpenCPN is rubbish IMHO!!

I'd really like to see an installation that works. But I don't think we'll
be able to achieve it.

kind regards
Steven

On Wed, 28 Dec 2022 at 17:56, Christopher Green <
***@***.***> wrote:

> I admit defeat. Seems you can't get an S-63 permit for Android.  You'd
> need to put it on a laptop or compatible plotter. So that's it. Can't get
> NZ ENC charts for the tablet.
>
> The downloadable NZ chart through opencpn is a no-longer-supported rasta
> chart. It's there, but navionics is better.
>
> I was not keen to try and learn how to use opencpn anyway. The user manual
> is over 1000 pages.
>
> On Wed, 28 Dec 2022, 2:21 PM Steven Ring ***@***.***> wrote:
>
>> Agreed! I'm gobsmacked that the Hydrographic Office thinks that all ENC
>> users are rich shipping companies
>>
>> On Wed, 28 Dec 2022, 2:11 pm Christopher Green, <
>> ***@***.***> wrote:
>>
>>> Yep
>>>
>>> Reckon our first best option is still Navionics charts on the plotter.
>>> That's good enough for a recreational cruising yacht. We are not a
>>> commercial vessel so there's no requirement for us to have "official"
>>> charts.
>>>
>>> On Wed, 28 Dec 2022, 2:06 PM Steven Ring ***@***.***> wrote:
>>>
>>>> Nice work Chris.
>>>>
>>>> I've just been examining the burning hoops we have to jump through to
>>>> get the "Official ENC" charts for Australia -- not to mention the
>>>> extraordinary costs.  And then you have to buy it all again next year!!!
>>>> WFT!!!
>>>>
>>>> Anger rising!!
>>>>
>>>> On Wed, 28 Dec 2022, 1:46 pm Christopher Green, <
>>>> ***@***.***> wrote:
>>>>
>>>>>
>>>>> https://www.cruisersforum.com/forums/f134/new-zealand-enc-now-in-s-63-format-for-free-237548.html
>>>>>
>>>>>
>>>>

-- 
*Steven Ring*
m: +61 417 495 268


-- 
*Steven Ring*
m: +61 417 495 268

**Comment by smr547** [comment]
Hi Chris,

So, in conclusion, the Samsung Tablet is a NO GO as far as openCPN and ENC charts are concerned. We must look to other platforms and we've run out of time for the Sydney to NZ leg (indeed for the entire Pacific Cruise I suspect)

Not to be discouraged.

[Here is a useful thread](https://www.cruisersforum.com/forums/f134/enc-charts-for-fiji-for-opencpn-221701.html) on Cruisers Forum (focussing on Fiji charts but still relevant).

I've been experimenting with OpenCPN on my MacBook Pro (macOS) and it's performance is encouraging. I've got a full set of official ENC charts for Spain and they work well. I will register CORC for an S-63 licence and also purchase a dongle.

I have to say, the ENC coverage for Spain is inferior to that of Navionics Charts. I would not like to be relying on OpenCPN and official ENC charts while cruising around Menorca or Mallorca. The coverage at the required resolution is just not there. Perhaps I'm missing something. 

The cost of official charts from the AHO is absolutely outrageous!

Given that Android devices are a no-go, I'm thinking that we should be looking at a permanent computing platform on Namadgi 3 -- one capable of running OpenCPN and storing all the charts. We have been working on a system for Trilogy and it has been coming together quite nicely -- more on this later

@pauljones17 will be interested in this thread as he is a strong advocate for the official ENC charts. @mrmrmartin and @PSARN @peterottesen @GarthBrice will also be interested. We must persevere.

**Comment by PSARN** [comment]
Back to navionics I guess.Sent from my iPadOn 29 Dec 2022, at 07:15, Steven Ring ***@***.***> wrote:﻿
Steven also capitulates

---------- Forwarded message ---------
From: Steven Ring ***@***.***>
Date: Wed, 28 Dec 2022 at 19:14
Subject: Re: New Zealand: ENC now in S-63 format for free - Cruisers &
Sailing Forums
To: Christopher Green ***@***.***>


Hi Chris,

I'm with you on this. The same conclusion but from a different perspective.

I downloaded the full set of NOAA ENC charts from US Coast Guard -- all
free and unencrypted. I  finally managed to get Android OpenCPN to index
them (after annoying incompatibility problems with the micro SD card reader
-- not supported but no error messages) and finally incorporate the charts
into the display. The result was hopeless. I was unable to get a coherent
chart display of any use. The "chart bar" option was a mess. The
auto-merging of different overlapping charts of different scales simply
failed.

Hopeless, barely describes the outcome!! OpenCPN is rubbish IMHO!!

I'd really like to see an installation that works. But I don't think we'll
be able to achieve it.

kind regards
Steven

On Wed, 28 Dec 2022 at 17:56, Christopher Green <
***@***.***> wrote:

> I admit defeat. Seems you can't get an S-63 permit for Android.  You'd
> need to put it on a laptop or compatible plotter. So that's it. Can't get
> NZ ENC charts for the tablet.
>
> The downloadable NZ chart through opencpn is a no-longer-supported rasta
> chart. It's there, but navionics is better.
>
> I was not keen to try and learn how to use opencpn anyway. The user manual
> is over 1000 pages.
>
> On Wed, 28 Dec 2022, 2:21 PM Steven Ring ***@***.***> wrote:
>
>> Agreed! I'm gobsmacked that the Hydrographic Office thinks that all ENC
>> users are rich shipping companies
>>
>> On Wed, 28 Dec 2022, 2:11 pm Christopher Green, <
>> ***@***.***> wrote:
>>
>>> Yep
>>>
>>> Reckon our first best option is still Navionics charts on the plotter.
>>> That's good enough for a recreational cruising yacht. We are not a
>>> commercial vessel so there's no requirement for us to have "official"
>>> charts.
>>>
>>> On Wed, 28 Dec 2022, 2:06 PM Steven Ring ***@***.***> wrote:
>>>
>>>> Nice work Chris.
>>>>
>>>> I've just been examining the burning hoops we have to jump through to
>>>> get the "Official ENC" charts for Australia -- not to mention the
>>>> extraordinary costs.  And then you have to buy it all again next year!!!
>>>> WFT!!!
>>>>
>>>> Anger rising!!
>>>>
>>>> On Wed, 28 Dec 2022, 1:46 pm Christopher Green, <
>>>> ***@***.***> wrote:
>>>>
>>>>>
>>>>> https://www.cruisersforum.com/forums/f134/new-zealand-enc-now-in-s-63-format-for-free-237548.html
>>>>>
>>>>>
>>>>

-- 
*Steven Ring*
m: +61 417 495 268


-- 
*Steven Ring*
m: +61 417 495 268

**Comment by smr547** [comment]
We've all capitulated on this issue -- closing it
