### ISSUE TITLE
Bilges - Underfloor storage compartments are WET

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#665]
Increasingly, fresh water is being found accumulating in the sub-floor storage compartments and in the bilge. The source of the water is unknown but may include one or more of

* slow leak in forward freshwater tank
* ingress through starboard window or gunwhale (during rain or deck washing)
* overflow (pressure release) from hot water system
* water release during plumbing repairs
* overflow into sail-locker -- when forward tank refill is left unattended (the drain in the hatch perimeter is inadequate)
* portholes left open

Namadgi's network of under-floor compartments and the extremely poor location of her [Limber Holes](https://www.quora.com/How-are-limber-holes-installed-in-the-structure-of-boats-to-promote-draining)  means that water is trapped in various compartments and does not efficiently drain to the bilge. Trapped water moves around the sub-floor compartments and voids between the stringers in a somewhat random fashion.

There is also evidence to suggest that small amounts of water are moving between GRP layers associated with the keel support stringers.  

In a master-stroke of poor design, our fixed bilge pump is also located away from the main bilge area (saloon underfloor compartment adjacent the "nav" station - starboard side). This may be effective during a significant flooding event but is useless for mopping up routine spills and leaks of the kind we are experiencing. 

The recommendations to skippers are:

- [ ] Take care when stowing items below the floor boards (they should be stowed in waterproof containers)
- [ ] Regularly inspect these compartments and remove any water found
- [ ] NEVER leave hoses unattended during water tank refill operations (especially the forward central tank)
- [ ] Fix all leaks when found, or report as a maintenance issue

@peterottesen, could you please include this advice in the Skippers Notes?
@PSARN for stowage plan

The committee and incoming skippers need to be aware of this ongoing and annoying problem.

@mrmrmartin @Bill-Russo @mgrybaitis @pjwain @Christopher-w-green @delcosta

**Comment by PSARN** [comment]
My Namadgi App includes a checklist for NOTICE TO SKIPPERS. The items below have been included. Is there a general list of notice to skippers, that I can ADD
Peter




From: Steven Ring ***@***.***>
Reply to: CanberraOceanRacingClub/namadgi3 ***@***.***>
Date: Sunday, 1 January 2023 at 05:24
To: CanberraOceanRacingClub/namadgi3 ***@***.***>
Cc: ***@***.***" ***@***.***>, Mention ***@***.***>
Subject: [CanberraOceanRacingClub/namadgi3] Underfloor storage compartments are WET (Issue #665)


Increasingly, fresh water is being found accumulating in the sub-floor storage compartments and in the bilge. The source of the water is unknown but may include one or more of

  *   slow leak in forward freshwater tank
  *   ingress through starboard window or gunwhale (during rain or deck washing)
  *   overflow (pressure release) from hot water system
  *   water release during plumbing repairs
  *   overflow into sail-locker -- when forward tank refill is left unattended (the drain in the hatch perimeter is inadequate)
  *   portholes left open

Namadgi's network of under-floor compartments and the extremely poor location of her Limber Holes<https://www.quora.com/How-are-limber-holes-installed-in-the-structure-of-boats-to-promote-draining> means that water is trapped in various compartments and does not efficiently drain to the bilge. Trapped water moves around the sub-floor compartments and voids between the stringers in a somewhat random fashion.

There is also evidence to suggest that small amounts of water are moving between GRP layers associated with the keel support stringers.

In a master-stroke of poor design, our fixed bilge pump is also located away from the main bilge area (saloon underfloor compartment adjacent the "nav" station - starboard side). This may be effective during a significant flooding event but is useless for mopping up routine spills and leaks of the kind we are experiencing.

The recommendations to skippers are:

  *   Take care when stowing items below the floor boards (they should be stowed in waterproof containers)
  *   Regularly inspect these compartments and remove any water found
  *   NEVER leave hoses unattended during water tank refill operations (especially the forward central tank)
  *   Fix all leaks when found, or report as a maintenance issue

@peterottesen<https://github.com/peterottesen>, could you please include this advice in the Skippers Notes?
@PSARN<https://github.com/PSARN> for stowage plan

The committee and incoming skippers need to be aware of this ongoing and annoying problem.

@mrmrmartin<https://github.com/mrmrmartin> @Bill-Russo<https://github.com/Bill-Russo> @mgrybaitis<https://github.com/mgrybaitis> @pjwain<https://github.com/pjwain> @Christopher-w-green<https://github.com/Christopher-w-green> @delcosta<https://github.com/delcosta>

**Comment by PSARN** [comment]
My Namadgi App includes a checklist for NOTICE TO SKIPPERS. The items below have been included. Is there a general list of notice to skippers, that I can ADD
<img width="226" alt="Screen Shot 2023-01-01 at 08 00 23" src="https://user-images.githubusercontent.com/32588100/210155555-444c321a-a13a-4b51-82bc-a2f16ef7d2b3.png">

**Comment by pcbaston** [comment]
All underfloor compartments are dry. There was slight water in center aft underfloor (aft keelbolts) enough to get a sponge wet. I tested the bilge pump operation (correct) so that is now drying out.

Issue should be closed.

**Comment by smr547** [comment]
Happy to close this one!! Thanks for the update Paul.
