### ISSUE TITLE
Iridium GO - Inoperable due to damaged power socket

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#673]
While on board Namadgi 3 during the Sydney to Opua delivery @Christopher-w-green reported

> There has been an accident with the IridiumGo. While someone was attempting to restart it, the boat lurched, and the fitting for the USB charger has been torn out of the unit. We are not able to charge the unit, but the battery is currently fully charged. We have no idea how long the battery will last. So we will keep the unit turned off and only turn it on to download weather forecasts and to communicate with you on a set schedule. I propose doing this once a day.
> 
> Please propose a time of day for a set communication schedule that works for you, as we have not been getting regular or timely confirmation of our daily reports.
> 
> Turning the IridiumGo off will mean that the PredictWind tracker will not be able to track our progress. It may update during our scheduled communication.
> 
> Any information you can find on the expected battery life for the IridiumGo would be of great assistance.
> 
> I will log back on to the Iridium in about 1 hour from now. Please respond by return email or SMS by that time with your proposal for a communication schedule.
> 
> Chris Green

**Comment by smr547** [comment]
I've contacted PredictWind for assistance and they want us to confirm that the unit was purchased through them. They also need the following info

- what email address was used for the purchase, (I think that is [corc.owner@gmail.com](mailto:corc.owner@gmail.com)) 
- when it was bought, and 
- what was the order number

I've asked Peter Wain if he has the records

**Comment by smr547** [comment]
I've also contacted [Carter Marine](https://goo.gl/maps/FvVQwaKBgtnUgbdg7) who are an Iridium Go dealer located at the Opua Marina. [Craig Pippen](https://contacts.google.com/person/c6693832341320381880?hl=en-GB) from Cater Marine has agreed to assess the damage when Namadgi 3 arrives early next week.

**Comment by smr547** [comment]
PredictWind have responded 

> Hi Steven
>Thanks for providing this invoice.The order was made in April 2019, so the unit is out of warranty.Using a local dealer in Opua is a good arrangement to try to fix the issue.Let us know how you get on.
> --
> 
> ArnaudPredictWind
> 

@pjwain @mrmrmartin and @Christopher-w-green will be interested

**Comment by smr547** [comment]
Some photo from the boat
![20230120_091957](https://user-images.githubusercontent.com/4327895/214236723-7e84c9e7-427d-4f0d-8cab-3328f02559e1.jpg)
![20230120_092126](https://user-images.githubusercontent.com/4327895/214236736-8c4ffc9e-e883-48e3-bb09-e9aa04f46063.jpg)

**Comment by smr547** [comment]
Hi @Christopher-w-green @mrmrmartin @pauljones17 

Could you please give the committee a report on the Iridium Go unit? 

1. How did it perform on the trans Tasman cruise?
2. Did it perform as expected?
3. What were the issues with it?
4. Is it worth repairing or replacing?
5. What would replace it with? 

Your report would be greatly appreciated.

**Comment by pcbaston** [comment]
Looking at the damage, the pcb mounted socket is torn away. Could glue a new piece of PCB to the circuit card and mount a new socket, with wire links to the appropriate tracks on the circuit card. Minute (small) pcb repair facility required. If was still at work or at Navy, I could do this.  May look to a commercial repairer in Canberra or Sydney who is willing...   
What is the cost of a replacement unit?

**Comment by smr547** [comment]
Here is the pinout for the USB Micro B. [Available here ](https://au.element14.com/amphenol-icc-fci/10103594-0001lf/micro-usb-2-0-type-b-receptacle/dp/2293752?st=usb%20micro%20b)for less than $2

<img width="793" alt="Screen Shot 2023-01-29 at 11 38 55 am" src="https://user-images.githubusercontent.com/4327895/215297716-00ad3265-7794-4a1f-adb3-d4635ad5c6a0.png">

**Comment by pcbaston** [comment]
What about second-hand units as the newer version enters the market.
Saw this:  https://www.outfittersatellite.com/used-iridium-go.html  US$579
plus our antenna that is compatible with mast mounting:  https://www.outfittersatellite.com/iridiumantenna.html (easy to extend cable by disassembly of mounting base..

**Comment by smr547** [comment]
Sorry @pcbaston, I’ve been busy and should have mentioned this earlier. I’ve managed to solder the USB socket to the PCB and the unit is working. My recommendation to the committee is to continue to use the repaired unit until the end of the year. Meanwhile we should research alternate satcoms with data plan. Starlink perhaps?

**Comment by smr547** [comment]
Michelle will bring the repaired unit back to the boat when she joins in March.

![35BB0D19-0713-4103-BB67-DFE44D594834](https://user-images.githubusercontent.com/4327895/220804147-0ad0cc24-ce80-48a1-9508-79d7a37b87fc.jpeg)
![0744C7B9-3D4E-4665-A6A3-FB006E271B10](https://user-images.githubusercontent.com/4327895/220804159-fb998fc2-5d52-452c-aaab-f4120f3c5b84.jpeg)
![4F4E369B-FFB1-41F8-BFAD-BB37E97C13F4](https://user-images.githubusercontent.com/4327895/220804162-7bb53a9f-6155-4155-91c6-cc15d04a92f3.jpeg)
![A3FD0F8B-6CC8-4FE8-A65B-257EFA4F12D4](https://user-images.githubusercontent.com/4327895/220804163-f22e81a3-5ebe-494b-9277-df0b790c5bca.jpeg)
![164FDB0E-06BD-412B-B1C7-A5AFD7177212](https://user-images.githubusercontent.com/4327895/220804169-d734cae1-725a-4d28-a989-dc360e74d1dc.jpeg)

**Comment by pcbaston** [comment]
Great work.
I hope the residue is cleaned up (isopropyl alcohol) to prevent corrosion..
I would also recommend epoxying in the connector - people can disconnect
the unit by pulling out the other, more substantial USB connector....

Who is taking it back to NZ - is this also in Github?

Many people do not use Github - Peter Wain said this directly to me - look
at the latest issues (Hot Water pipe rupture, Mainsail Reef point). I am
renaming some to make it easy to search for current and past issues to
build up a collective of information...


We spoke to some others in NZ and Starlink is way too expensive for what it
is offering at present. Most believe he new IridiumGO Exec is the future..

Regards,

*Paul Baston*

**Comment by pcbaston** [comment]
Also, I don't think the shed will fit in a bag!

Regards,

*Paul Baston*

**Comment by smr547** [comment]
Opps about the shed!! 
Thanks @pcbaston regarding the expoxy suggestion. A very good Idea. Wilco.
Regarding Peter Wain's comment -- I'll take that off line

**Comment by smr547** [comment]
@mgrybaitis installed the repaired unit but now reports that the charger is not working and the battery is flat. She will return the unit to Australia for further evaluation.

Time is pressing, and the repair of the unit was delicate and obviously unsuccessful. I recommend that the club offer to pay John May $500 for his Iridium Go unit which he is seeking to sell. This is about half price compared to a replacement unit. 

Issue for the next committee meeting

@pcbaston @mgrybaitis @peterottesen @pjwain @delcosta @Bill-Russo @delcosta

**Comment by pcbaston** [comment]
Issue discussed at Committee meeting 21 Mar. Committee agreed to purchase second hand unit from John May ($500). 
Peter Ottessen will arrange collection/delivery to Garth Brice who will confirm operation with our card/account and install unit during his NZ8 booking.

**Comment by pcbaston** [comment]
Garth Brice reported:
"I picked up the replacement Iridium Go for Namadgi from John May last night.
It is a fully functional unit that I used with John during our recent crossing from New Zealand to Sydney

I will take the replacement unit with me to Namadgi on Friday 14 April and set it up with the tablet onboard and my Ipad.
I have an electronics technician coming to Namadgi on 26 April to fix the card readers in both chart plotters. He will also update the software and download the electronic charts for Fiji and New Caledonia.
Chris and I will ensure that we have full wireless connectivity between the chart plotters and the Iridium Go using Active Captain. I will also have Navionics charts on my iPad as a back up along with the paper charts that I have purchased for the club."

**Comment by pcbaston** [comment]
The replacement Iridium GO unit was installed in Namadgi3 by Garth Brice who reports it is operating correctly.
Total cost of replacement unit (secondhand) $500.
Issue CLOSED.

**Comment by pjwain** [comment]
Hi Paul, I noticed that two days ago the Namagi 3 Iridium Go was reporting
that it was located out in the bush somewhere near Hoskinstown. I don't
know if it was our old one or the second hand one we purchased, but the
most recent report was dated 15 April, when Garth was on the yacht, so I'm
not sure how much testing he has done. Regards Peter.

**Comment by pcbaston** [comment]
Peter,
thank you for checking.
Where is the Position of N3 in the CORC website?  I'll see if I can compare
with AIS data.
If that is inconclusive, I'll ask Chris Green to do an end-to-end email
test with Garth.  He is alongside until Wednesday.

Regards,

*Paul Baston*

**Comment by pjwain** [comment]
Hi Paul,

When the position stopped showing properly on the Predict Wind website, I
took the link off the CORC website, but here is the link showing all the
positions recorded from Dec 2022 to the present:
https://forecast.predictwind.com/tracking/display/Namadgi3/?windSymbol=OFF&weatherSource=ECMWF&mapMode=useAtlas.
When it is working again, I'll publish it. In fact, that's the reason I was
checking it today.

It would be good for Garth (or someone) to test sending and receiving an
email, sending and receiving an SMS, making and receiving a phone call,
requesting and receiving a weather report and GRIB file, and setting the
device up to report its position automatically and regularly.

Regards, Peter.

**Comment by pcbaston** [comment]
On Mon 17Apr23, Garth reported:
I have already tested the following using my IPad and the Namadgi Samsung Tablet:
1. Receiving a PredictWind weather route from the Bay of Islands to Fiji
2. Sending a email to my own email address from the Namadgi in Opua.

As suggested by Peter Wain I will send an email and a SMS to Chris and ask him to reply. I will also give him a call via the Iridium Go.

Then, following testing calls and SMS:
I think that using the Iridium go for phone calls is not a good idea. 
We should use our hand held satcom when making and receiving calls 
Messaging did work very well. 
PredictWind weather routing is working. 
Emails are also working

This confirms Iridium GO is working correctly, albeit voice calls are garbled.  
Position reporting needs to be set-up.
Issue CLOSED as previous.
