### ISSUE TITLE
Port chart plotter pedestal

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#674]
Crew from the Sydney to Opua crossing have reported...

> Good morning Steven
> 
> Attached are photos of the damage.  The chart plotter has been removed, connections taped and stub covered with a plastic bag, reinforced by tape.
> 
> There is some movement in the starboard chart plotter suggesting it may also be on the way out.
> 
> Consider that if a stainless steel fabricator can be identified locally, both plates should be replaced.
> 
> Kind regards
> 
> Paul

![image1 (1)](https://user-images.githubusercontent.com/4327895/213295593-55cad783-2a1a-4358-b8d3-92fe7c62f0cc.jpeg)
![image0 (2)](https://user-images.githubusercontent.com/4327895/213295613-575bae4c-98a1-4faf-b80c-9a29b5db1fd8.jpeg)

@pauljones17 @mrmrmartin  will be interested

**Comment by mgrybaitis** [comment]
I know Paul McDonald had made at Opua stainless steel frame with gate to hold the life raft on Mari. If there was anywhere you would find a stainless steel fabricator Opua is it.

**Comment by smr547** [comment]
Thanks for your observations Chris, Paul has reported the problem and you
may have seen the resulting maintenance issue
<https://github.com/CanberraOceanRacingClub/namadgi3/issues/674>.

Dodgy construction does not surprise me. In one Hobart race (Elan 2013) the
whole cockpit console (including chartplotter and other electrics)
separated from the boat owing to a stainless steel "non-weld" failing..  I
think (and hope) that the hulls of our boats are made with a slightly
higher grade of workmanship.

You may have noticed I've joined the camp that wants CORC to invest in a
higher quality yacht next time we change over. The financial pain will be
worth it in terms of utility (once again, actually going in a RSHYR),
reliability, safety and resale value.

kind regards
Steven

PS. I have shared our discussion with the committee -- It's important!!



On Thu, 19 Jan 2023 at 07:30, Christopher Green <
***@***.***> wrote:

> Steven, don't think anyone has told you about the port helm station
> breaking off the steering pedestal. Dodgy construction with a ton of salt
> corroding unprotected aluminium connecting plate. Got very wobbly on the
> trip, but thankfully didn't actually break off until we were in port.
> Michael has arranged a netal fabricator to look at making a new stainless
> connector. Paul Jones will send a photo.
> Chris
>


-- 
*Steven Ring*
m: +61 417 495 268

**Comment by smr547** [comment]
Chris Green reports

> Hi Steven, 
> 
> Got the helm station back together. Feels solid as. Boat builder said youd rip the bolts out of the plate underneath before you'd break it.
> 
> Chris
> 

Photos below
![20230127_125653](https://user-images.githubusercontent.com/4327895/215297403-c56772fc-0a9f-4d8f-9985-043724b55613.jpg)
![20230127_125634](https://user-images.githubusercontent.com/4327895/215297407-088731ef-9bb2-4d92-9f5f-387a1c056248.jpg)
![20230127_125618](https://user-images.githubusercontent.com/4327895/215297408-a742909e-9086-4683-8c3f-944c0ac874ea.jpg)
![20230127_122738](https://user-images.githubusercontent.com/4327895/215297410-37df1cc7-face-4a7c-bb9d-f1cfba75944a.jpg)
![20230127_115647](https://user-images.githubusercontent.com/4327895/215297411-174ae073-e360-4a1b-a230-7f7d5726d5c5.jpg)
![20230127_115619](https://user-images.githubusercontent.com/4327895/215297412-90223617-663a-4eae-b716-5c08153c8929.jpg)

**Comment by smr547** [comment]
Hi @Christopher-w-green,

What was the cost of this repair. I'm thinking we should do a precautionary rebuild of the starboard pedestal 

kind regards
Steven

**Comment by Christopher-w-green** [comment]
Don't know the cost. Michael was handling the money side as he had the gst
exemption, but we haven't got an invoice yet. He said he charged $85 an
hour, so don't think it will be too much, probably a couple if hours work
for him. The starboard side still feels solid. But you could pull the chart
plotter out and have a look at it if you're worried. I wouldn't think it
necessary to rebuild it if it isn't broken. From the broken bit on the port
side, it looks like it cracked through one of the elongated bolt holes
first, and then the movement gradually fatigued the plate at both ends. As
it got more wobbly during our passage, we thought the bolts had worked
loose and were planning to tighten them up when we got in. So if the
starboard side starts to wobble that would be a flag to pull it apart.

**Comment by pcbaston** [comment]
Repair complete. Units operable. Closed.
