### ISSUE TITLE
Water Maker - Product disappearing? 

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#675]
@pauljones17 reports that during the Sydney to Opua crossing ....

> Good morning Steven
> 
> During the passage we made water.  After two hours, the tank was still empty. Michael and I repeated the whole process, but instead of turning to tank, left the selector on taste and simply ran the hose from the galley to the tank.
> 
> The whereabouts of some 120 litres of fresh water has not been identified. 
Most peculiar.
> 
> Kind regards
> Paul

![image1 (2)](https://user-images.githubusercontent.com/4327895/213299336-9db53d87-6983-4fdf-ac24-591f837575b2.jpeg)
![image0 (3)](https://user-images.githubusercontent.com/4327895/213299351-704e9a79-bba2-4781-b618-460aa1b842e8.jpeg)

**Comment by smr547** [comment]
Colleagues (@mrmrmartin @pauljones17 @Christopher-w-green)

Please review the following from @JCRowling 

> Thanks Michelle. 
> Had dinner last night with Bill Leslie. During the evening we discussed the NZ adventure. He mentioned that our Open Ocean watermaker was made in Opua, NZ and suggested that it might be useful - if the watermaker was giving any trouble- to contact them for assistance/repairs. He also thought it might be useful to get in contact while we are in Opua to see if there were any improvements available from them for the watermaker as they are regularly updating their system. 
> Cheers
> John R

Could you please contact ``Open Ocean`` in Opua and asked them to investigate the problem. It would be useful if they could service the entire unit.

thank you 
Steven

**Comment by pcbaston** [comment]
Open Ocean were contacted in Opua. Now part of NSR who do rigging and boat maintenance.  NSR and Open Ocean do not conduct maintenance anymore as they do not have a technician on site.  They suggested Seapower 2006 or Total Engineering. Mike at Seapower was able to visit and check water maker. He said it looked fine and was operating correctly, making water. He said the only way water was not going to tank was either a valve was no open (diverting water to overflow - stbd aft head sink drain outlet via tee-joint) or inlet valve was not open. Since water was made on sample, seems unlikely inlet not open.
Did not run the water maker long at the marina due to dirty water after storm.  Suggested changing filters before next ocean crossing.  No charge for 20 mins of his time.

Peter wain is current skipper and familiar with water maker. He was asked to investigate the making of water.

**Comment by smr547** [comment]
I spoke to Bill Leslie a month ago and he said that the "product" pipe from the water maker feeds the aft tank via a "Tee" fitting in that tank's *breather tube*.

The penny has only just dropped for me. If the water maker is feeding water into the breather tube then there is a chance of creating an air lock in the tank (actually pressurising the tank with incoming product water). This  pressure would then force the product water over the side via the breather vent. 

The obvious solution is to remove the water filler cap during water making operations to prevent pressure build up in the tank. 

I recall making this recommendation in the past and also making a handwritting note on the water maker SOP on board. Perhaps this should be a "Notice to Skippers" pending its incorporation into the revised SOP

@pjwain @peterottesen @delcosta @DimitD @mgrybaitis @mrmrmartin @Bill-Russo

**Comment by smr547** [comment]
On 24/2 @pjwain reported

>We had a quiet afternoon and made water for 75 minutes at about 135 litres per hour. The watermaker worked faultlessly, and it was filling the tank so quickly we had an airlock until I removed the deck filler.

**Comment by smr547** [comment]
Notice to Skippers created (see issue #687)
Closing this issue

**Comment by smr547** [comment]
@pjwain 

Hi Peter,

Thank you for your recent report about the water maker -- I think you have found the solution!! We will issue a notice to skippers about removing the filler cap while making water. We will also update the SOP. This issue is now closed.

regards
Steven

**Comment by pjwain** [comment]
Hi Steve,  That's exactly what happened yesterday.  There was some hissing
and a fair bit of pressure released when I opened the deck filler. I'm
betting that Michael Martin's product water was lost through the breather
when he used the watermaker recently. Regards, Peter.

**Comment by peterottesen** [comment]
That’s a relief. We probably need to review the SOP to make this absolutely clear.

**Comment by mrmrmartin** [comment]
Noted and very possible
In fact if it wasn't an alien related loss there is no other possible reason for the loss.
