### ISSUE TITLE
Starboard Pedestal - reinforce as per Port Pedestal

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#677]
Same repair as the port side -- see #674

**Comment by pcbaston** [comment]
Not an issue. Stbd pedestal is OK. Move this to low priority maintenance is deemed necessary.

**Comment by smr547** [comment]
Pedestal is now failing. The aluminum plate glassed into the top section is of poor quality and is cracking along stress lines near mounting bolts. Local fibreglass worker in Vuda Marina, Fiji engaged to replace plate. Work should be done tomorrow. Photos to follow.

**Comment by smr547** [comment]
![10A571FF-3036-4AA4-957E-E74B0E58C8E9](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/c3344649-69c1-4326-a76a-5d3a3e406055)
![07490502-D410-4974-88F8-1F4DFAE94471](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/d8f64e7e-89ae-434a-9159-18e4ca9dbbf5)
![772C8E66-6B17-4DFD-B066-8B303E7802C7](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/04d9a225-b38e-4ca1-9ce3-8ea5dfb490e1)
![842EA377-CC5B-4EE7-B15A-F09CD0622950](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/fe407bca-394b-4d7f-a1ed-e97d1da7a01a)

**Comment by smr547** [comment]
Local contractor engaged. 5mm of epoxy and matted glass fabric laid up over existing plate. Drilled and refitted. Pedestal now sturdy. Let’s hope it lasts. Closing this issue. 
![5BFCA631-C60D-4769-96B4-F05A6E95DB84](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/0587f2bb-079d-4986-9fb4-ada7ca4bffe0)
![Uploading B3BA651C-9774-42C6-83EC-28B809FD83A3.jpeg…]()
