### ISSUE TITLE
Fit check storm sails

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#68]
Rigger has the sail track lugs
timing: July

**Comment by DeeTaylor87** [comment]
Storm sails could not be found in store. They are not with Paul McDonald. They are not with Dave Holt.  We think they may have been left on Namadgi 2

**Comment by DeeTaylor87** [comment]
Storm sails were not on Namadgi 2.  We think they have been loaned to Simon and Pelagic Magic.  The old storm jib was found on Namadgi 2 and is being returned to the store.

**Comment by smr547** [comment]
Check ELAN forepeak locker again

**Comment by DeeTaylor87** [comment]
Really?  We checked pretty well. There was only one large parcel in that front locker. It did look rather large for storm sails....

**Comment by mrmrmartin** [comment]
Hi Dee and Stephen.


Not sure if we checked the forepeak closely enough (that is the two hatches directly ahead of the locker which contained 2 sails - one of which we took).


cheers

________________________________

**Comment by DeeTaylor87** [comment]
@smr547 @DaveHolt @peterottesen @jphayden 
Was the rigger Marc Eady from On Deck Rigging (the person that Q Services uses sometimes).  If he has the sail track lugs (whatever they are), might he also have the Storm Sails.  Who knows about this issue?

**Comment by jphayden** [comment]
Don't recall that we ever had the tri sail and storm jib on the new boat . But  I will check with Marc Eqdy  tomorrow morning .  Thanks for pursuing  the problem Dee

**Comment by DaveHolt** [comment]
The storm sails have been located at Paul McD sail store! Paul will write up an inventory of sails and gear he has at his place. As the delivery crew are already in Pittwater, We will need to transport the storm sails to Batemans Bay by car. I think they have the old Velcro luff storm jib on board.

**Comment by mrmrmartin** [comment]
Hi all

Once we have the sails on board we should check to see if they fit.

The storm jib should be okay as long as the bolt rope in the luff fits into the forestay track.


The tri-sail is a different matter.

To use this sail we will need to work out the size of the track on the mast.

We will  then need to purchase some cars that fit into the track and make sure the clips on the tri-sail (we need to count how many there are) will fit the cars.

The track already has a fitting which I think may be used to attach the halyard but I am not sure about this.

cheeers


________________________________

**Comment by DaveHolt** [comment]
G'day Michael,
the Q-Service rigger Mark Eady left a bag of tri-sail mast track lugs onboard for fitting to our tri-sail. Last I saw them they were in a white plastic bag on top of the 12 volt switch panel. I don't know where they ended up.  Maybe Mark or Q-Service might know.
Dave

**Comment by jphayden** [comment]
I will call Marc Eadie and the Quays

**Comment by DeeTaylor87** [comment]
Is there any further information on this? Where are we up to?  Can we sort this before the boat returns to Sydney?

**Comment by smr547** [comment]
Closing this item -- historical
