### ISSUE TITLE
Plumbing - Hot water pipe ruptured

### ISSUE THREAD

**Issue by pcbaston** [CanberraOceanRacingClub/namadgi3#680]
Sam Delorenzo reported a Split Hot Water Pipe via SMS. It has been repaired temporarily but needs replacement. Length approx 400mm (TBC).  
![-2710685258011686382](https://user-images.githubusercontent.com/120452016/216763879-45d83e0b-1e26-4110-8c02-447dc03e09d6.jpg)

**Comment by pcbaston** [comment]
Pipe is termed "John Guest" piping and push-on connectors. Available in a variety of sizes (diameters) - Namadgi using 12mm diam piping and connectors. Used mainly in the caravan and RV world.  Some fittings and pipe available Bunnings.

Local Canberra supplier is:
Caravans Plus, 22 Endurance Ave, Queanbeyan East NSW 2620
[Parts listing](https://www.caravansplus.com.au/plumbing-supplies/hose-fittings/12mm-push-fit/)

How to Use: 
[CaravansPlus_ How To Use John Guest Push-on Fittings.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/10608482/CaravansPlus_.How.To.Use.John.Guest.Push-on.Fittings.pdf)

1m of red pipe to be procurred and taken by NZ3 crew.

**Comment by pcbaston** [comment]
Can be procured in Opua: 
Burnsco [Opua](https://www.burnsco.co.nz/stores/opua)
Dockside Building, 5 Baffin Street, Opua, 0200 New Zealand
[09 402 5204](tel:09 402 5204)

[Pipe](https://www.burnsco.co.nz/john-guest-fresh-water-tubing)
Will need [cutter](https://www.burnsco.co.nz/sf-tube-cutter-tool) to make clean cuts that will not leak, unless one onboard

**Comment by pcbaston** [comment]
Pipe taken to Opua was incorrect size.  Namadgi using 15mm diameter. Common Rv size is 12mm.  Pipe repair made by Sam is holding.

**Comment by delcosta** [comment]
Paul/Steve
FYI
I have a piece of the pipe that Greg Hall cut off.

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603
______________________________________________________________________________________
IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail

**Comment by pcbaston** [comment]
Can you get it to Michelle? She is also taking the repaired IridiumGO.
May not need to be done immediately, but would be a useful spare.

Regards,

*Paul Baston*

**Comment by pcbaston** [comment]
Allister Polkinghorne (Skipper NZ7) reported a leak in the water system (The water pump was working every 15 minutes to hold pressure). He suspected the flick mixer (tap in galley). After further looking and advice on previous repiar by Sam, he identified the leak as the repair. The repaired line was leaking again. I advised him to use a length of blue line from the nearby breather line (excess to requirement) to make the repair.  He replaced the leaking red line with blue line and reported the leak fixed.

I will seek to source 2m of blue and red (or a common colour if available) 15mm diameter hose for Garth Brice or Peter Ottesen to take to Opua ahead of the NZ-Fiji relocation.

**Comment by pcbaston** [comment]
Related/Same issue as [522](https://github.com/CanberraOceanRacingClub/namadgi3/issues/522), [562](https://github.com/CanberraOceanRacingClub/namadgi3/issues/562) and [583](https://github.com/CanberraOceanRacingClub/namadgi3/issues/583)

**Comment by pcbaston** [comment]
I procured 2m Red and 2m Blue 15mm diam piping from CaravansPlus (online) in Queanbeyan, along with cutter, in-line joiners and hot water (red) pipe inserts. Have requested a crew transfer to Namadgi3 before sailing to Fiji.

**Comment by pcbaston** [comment]
Pipe and fittings provided to @GarthBrice FOD to Namadgi3.

**Comment by pcbaston** [comment]
Allister reported 3 May 23:
"The hot water pipe that had been repaired by me has been replaced with a new section of pipe and has been pressure tested satisfactorily." 
He has confirmed that piping is holding pressure and water pump is not coming on too often to keep pressure.
Issue CLOSED.
