### ISSUE TITLE
Heads - Stbd Aft Shower Pump Inoperative

### ISSUE THREAD

**Issue by pcbaston** [CanberraOceanRacingClub/namadgi3#682]
Shower pump stopped working during shower. Base cleaned of mould with no remedy. 20A 3AG automotive fuze in main supply line to pump blown. Replaced fuze which blew immediately. Suspect pump short. Further investigation required.
![219980555-9bf6ef8c-e7b2-41db-9b14-13b2c25fc1ad](https://user-images.githubusercontent.com/120452016/232970811-75217d9a-16ac-4696-a988-61e967e26634.jpg)

**Comment by pcbaston** [comment]
Investigation on internet reveals fuze should be 10Amp!
Whale manual (https://www.whalepumps.com/marine/siteFiles/resources/docs/resource-library/180.137_v7_0619_sr_db.pdf):
"
**MAINTENANCE**
This Whale Gulper® IC is designed to only require minimal maintenance.
WARNING: Before servicing pump, turn off pump and drain water from system.

Annual Checks
• Whale advise that the boat's plumbing system is checked annually for leaks and obstructions. Also a pump electrics check is advisable.
• Before inspecting or replacing the diaphragm, disconnect the electrical supply.

Optimal Performance
• Ensure this product is clear of debris
**IF THE PUMP IS NOT OPERATING AS EXPECTED:-**
• Loosen the hose clips to release the pump from plumbing.
• Unscrew the Ezi-clamp clamping ring to release the pump head - the screw on the pump head near the inlet/outlets
• This will release the pump head, and allow easy access to the valves & diaphragm.
• The diaphragm and valves should be checked for any excessive wear, damage or cracks, and should be replaced if necessary (service kit AK2050 - replacement pump head).

Cleaning
Gulper® IC and accessories should be wiped clean regularly to maintain optimal performance and ensure no clogging occurs. WARNING: Do not use abrasive cleaners. 
"

FAULT FINDING for Blown Fuze:
If fuse has blown check for reverse polarity, closed valves or seacocks, then **for debris in pump head and clean out if necessary**. (See section 11). Replace fuse and run pump

![bavaria-whale-gulper-ic-shower-pump-with-jst-connector](https://user-images.githubusercontent.com/120452016/220776496-7c99d547-42d0-4567-a19e-520b24025d9b.jpg)

**Comment by pcbaston** [comment]
Repair task passed to SeaPower in Opua 11Apr23.

**Comment by pcbaston** [comment]
Garth Brice reported:
"Dave (Seapower?) came back to the boat this morning.   The pump in the starboard shower is stuffed. The **shaft is broken** and the diaphragm is ruptured. It is not worth fixing. Dave is ordering a new one over night and it will be fitted tomorrow. I have found a 40 mm 10 amp fuse onboard. 

Do we have a spare shower pump onboard? Peter’s app indicates that we are out of stock. Where is 93 STB Seat Locker?

The port shower pumps both forward and aft have also been checked and serviced. They are both working well."

**Comment by pcbaston** [comment]
Thanks for the update. 
I need to get approval for the purchase and repair. The pump alone will cost about $400 - I've checked online previously. Here is the [cheapest] i've found in Australia:  (https://www.marinedirect.com.au/132026-bla-whale-reg-gulper-reg-ic-grey-water-pump)

The diaphragm can be replaced (Service kit) but the shaft probably not.
I would not think a shower pump is a necessary spare to carry onboard. I certainly wouldn't carry a spare.

I expect the locker is behind the table, under one of the seats.  Hopefully, there is a label on it. I do not have a diagram yet.  Peter Lucy will know.

For Committee
Please acknowledge that the replacement Grey Water Pump for the Aft Stbd Shower will cost in vicinity of $400 + labour cost.

**Comment by pcbaston** [comment]
Committee members (Peter Ottesen, Michelle Grybaitis, Sam Delorenzo) concurred with cost of repair. 
Garth Brice reports Seapower to fit replacement pump 18Apr23 alongside Opua.  
Remaining pumps taken apart, cleaned and inspected - all OK.

**Comment by pcbaston** [comment]
Damaged pump replaced by SeaPower NZ (NZD465) and shower drain removed, inspected and excess water removed. Drain resealed and STW.  Repair part of package of work - Invoice 21597 refers.
[INV00021597.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/11271987/INV00021597.pdf)

Issue CLOSED.

**Comment by smr547** [comment]
Hi Paul,

I just noticed this issue on GitHub -- thank you for the superb job of documenting the issue. Hopefully we can train some of the other members up to this level of documentation.

regards
Steven
