### ISSUE TITLE
BEP Matrix Gas Controller - sensor 1 inoperative

### ISSUE THREAD

**Issue by pcbaston** [CanberraOceanRacingClub/namadgi3#684]
Gas detector/switch only shows sensor 2 as operating (green LED). Sensor no.1 is located in pots and pans cupboard facing to the rear of the gas oven.
It's a standard BPE Sensor. 
A spare, claimed to be onboard, could not be located.
A new sensor has been ordered from Cater Marine at OPUA Marina complex. 
Peter Wain should be notified when it is available.

**Comment by smr547** [comment]
My apologies, I have the spare unit in my workshop. I removed it during the Batemans working bee with the intention of fitting a plug but ran out of time.

With a plug fitted to the sensor (with a short length of cable) the sensors can be replace quickly without the need to re-run wires or solder fittings in awkward places

I'll fit the plug to the unit I have and give it to Michelle to bring to the boat.

Please return the old sensor package to me. I've also purchased two "naked" sensors that can be soldered into the existing sensor PCB (printed circuit board) once the defunct sensor is removed.

Given that these units seem to failing a lot, It is best to keep a couple of spares on board.

@pjwain @mgrybaitis @peterottesen

**Comment by smr547** [comment]
@pjwain reports

>I have picked up and paid for the gas detector sensor from Cater Marine. 

@PSARN will be interested in the addtion of a new spare part to inventory.

@mgrybaitis will return the spare I have to Namadgi next week. Please return the faulty uint to me and I'll solder in a replacement sensor module -- I have two spares at home.

**Comment by PSARN** [comment]
Can someone send me a picture of the fast detector, brand and model including cost
PeterL

Sent from my iPhone

On 4 Mar 2023, at 3:21 am, Steven Ring ***@***.***> wrote:

﻿

@pjwain<https://github.com/pjwain> reports

I have picked up and paid for the gas detector sensor from Cater Marine.

@PSARN<https://github.com/PSARN> will be interested in the addtion of a new spare part to inventory.

@mgrybaitis<https://github.com/mgrybaitis> will return the spare I have to Namadgi next week. Please return the faulty uint to me and I'll solder in a replacement sensor module -- I have two spares at home.

**Comment by pjwain** [comment]
Hi Peter, this is the sensor I picked up, not sure whether it is what you
want. It was  NZD 117.54, gst free. Regards,  Peter W.

**Comment by pcbaston** [comment]
I asked Allister Polkinhorne to swap the sensors on the BEP detector as fault finding. He did and found that the Sensor 2 LED remains lit, which tells me the sensor is working and that the BEP detector unit is either faulty or LED for Sensor 1 is U/S. 
Perhaps it is time to renew our gas detector/controller to current [Gas Detectors](https://www.bepmarine.com/en/Products/Monitoring/Gas-Detectors)

**Comment by smr547** [comment]
Confirmed gas sensor 1 (under stove) is inop due to water ingress. I’ll source a spare. 
![B4336F26-F430-47A4-A2C1-0B9C96218823](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/23d1ae2c-582d-4b67-80ef-0e8d065aba60)

**Comment by pcbaston** [comment]
Gas sensor 1 replaced previously using connector to existing lead to BEP unit. Was innopperatve when joining 9 SEP. 
Replaced soldered connector with automotive scree terminal block (behind middle drawer) to facilitate easy replacements in future.
DO NOT CUT replacement sensor cable as the supplied bit has soldered ends exposed that can go directly into terminal block.
System reset (by stepping thru test stages) and operational.
See photos for reference.
Spare (new) sensor in electrical parts box in under floor storage 19.
![IMG_20230922_081850707](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/09d13a7a-4c78-406c-a1fe-fe5f8e719622)
![IMG_20230922_081831540](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/71b6684d-b2b5-4780-9834-1e7fe6f485bb)
Issue CLOSED.
