### ISSUE TITLE
Bow Thruster - Low Thrust

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#686]
In his report of 22/2/23 @pjwain reported 

>Unfortunately the bow thruster had no thrust and we were forced into a 12 point turn to get out of the berth safely. Luckily there was no current and it was nearly calm. We discovered later that there was a little thrust on one side but almost none on the other. We will investigate further. 

@pcbaston @mgrybaitis @mrmrmartin @peterottesen @Bill-Russo @delcosta

**Comment by smr547** [comment]
Further report from @pjwain on 24/2

>Hi Steve, The bow thruster didn't seem to be working a couple of days ago, so I had a look up the tube this morning and the blades are intact and no obstructions were visible (pictures attached). Water is coming out of the tube when switched on, but maybe not enough.  I'm wondering how old the battery is, and whether it might be on the way out.  I did notice the orange light on the thruster panel was flashing when the red or green buttons are pressed.  Is that normal? Regards, Peter.

With some photos

![P2242147](https://user-images.githubusercontent.com/4327895/221261165-ba0e7757-fac5-4cda-ba0a-f38f6f364712.JPG)
![P2242148](https://user-images.githubusercontent.com/4327895/221261186-8ce711e7-baf5-49f9-8ab8-4a453280173f.JPG)

**Comment by smr547** [comment]
Hi Peter,

Nice photos and nice work checking out the blades despite the threat of sharkes!!

I'll look up the status codes you noted from the system.

The bowthruster battery and motor (including brushes) were inspected by an Electrical Engineern (Damien Hadzic) in Batemans in January. The battery was in "excellent condition" and the brushes had plenty of life left. 

Please update us as you use the the thruster in the future. Hopefully is was simply some debris from the cyclone.

@pcbaston @pjwain @peterottesen @delcosta @DimitD

**Comment by pcbaston** [comment]
I've downloaded the manual. Attached is the single page troubleshooting guide. No mention of light flashing on controller (codes?).  Wiring diagram of how battery is charged - most likely an in-line fuse/circuit breaker??
[Troubleshooting Bow Thruster.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/10846367/Troubleshooting.Bow.Thruster.pdf)

**Comment by smr547** [comment]
@pjwain reports:

>I tested the bow thruster battery under instruction from Marine Electrics Opua, who loaned me a tester and gave me some instruction on how to use it.  The battery has a load capacity of 850 amps, but could only manage 160, so it is nearly dead.  I have ordered and paid for a new agm battery with a load capacity of 950 amps. It is a Fullriver HC100, AGM 950CCA Start Battery and will arrive  about Tuesday next week. They are very busy and said they could only install it with a couple of weeks notice, so we may have to do it ourselves.  I have discussed this with Mark Miller, who will be on the yacht next week. 

Nice work with the tester Peter! ... and thanks for organising the replacement battery.

**Comment by pcbaston** [comment]
Peter Wain stated in his 4Mar23 Skipper's Report "Tie down strap supplied by Marine Electrics is probably not strong enough for a sea passage. I suggest a metal bracket or strap with larger screws should be fitted [before the yacht goes to Fiji]".

Will get information from Mark Miller when he fits the new battery.

**Comment by smr547** [comment]
Hi @pjwain,

Did we check that the charging system for the Bow Thruster battery is working? I don't recall if it has an independent charge circuit or simple parallels off the house batteries.

regards
Steven

**Comment by pjwain** [comment]
I didn't check the charging system itself, and I'm pretty dumb when it
comes to electricity. However when I did the test the voltage was showing
around 13, so I assume it must be charging OK. Regards, Peter.

**Comment by smr547** [comment]
Peter, I thinks that's a fair assumption!!
Many thanks.

**Comment by pcbaston** [comment]
A new 950CAH Battery was supplied by Marine Electrics in OPUA, NZ (NZ$671 gust exempt) and fitted. Invoice paid. Bow thruster returned to service.
