### ISSUE TITLE
BBQ drip tray - lost at sea

### ISSUE THREAD

**Issue by mgrybaitis** [CanberraOceanRacingClub/namadgi3#693]
The BBQ drip tray fell out and flew overboard in 1-2 metre sees during an urgent head dumping. Have made contact with Cater Marine in Opua to see if I can get a replacement.
Will be of interest to @smr547 @pcbaston

**Comment by mgrybaitis** [comment]
Galleymate 1100 is brand of BBQ

**Comment by mgrybaitis** [comment]
These are the dimensions for the Galleymate 1100
Product dimensions – Height: 360mm (14.5 in), Width: 540mm (21.5 in), Depth: 340mm (13.5in)
Cooking surface measures – Width: 440mm (17.5 in), Depth: 250mm (10 in)
@pcbaston @smr547

**Comment by pcbaston** [comment]
Galleymate spares available from marinebarbeques.com.au in NSW. Drip tray is $95 plus postage. Will try to get delivery to NZ before ordering.

**Comment by pcbaston** [comment]
> These are the dimensions for the Galleymate 1100 Product dimensions – Height: 360mm (14.5 in), Width: 540mm (21.5 in), Depth: 340mm (13.5in) Cooking surface measures – Width: 440mm (17.5 in), Depth: 250mm (10 in) @pcbaston @smr547

Where did these dimensions come from?

**Comment by mgrybaitis** [comment]
I got the dimensions from the specifications on the Galleymate 1100 - link:  https://www.mydeal.com.au/galleymate-1100-316-marine-grade-stainless-steel-bbq-5888784

**Comment by mgrybaitis** [comment]
Maybe Alistair could bring the replacement when he comes?

**Comment by pcbaston** [comment]
Drip tray ordered and enroute to OPUA Marina Office. AustPost tracking https://auspost.com.au/mypost/track/#/details/EJ306378575AU.

**Comment by pcbaston** [comment]
Replacement arrived in Auckland and cleared customs 28 Mar. Out for delivery to OPUA Marina office FOD.

**Comment by pcbaston** [comment]
Package was delivered according to AustPost 29Mar23, but has failed to be located.
Caravan & Marine Supplies has been contacted to assist:
"
Hi there Stacey,
I tried to call but my phone hangs up immediately, hence I have resorted to email.
WRT the attached Invoice, which I paid and you arranged freight to NZ for me, I was wondering if you can recall how the package looked.
We have looked at the delivery address and cannot locate the package. The tracking says it took two hours to deliver from assignment, which seems a bit quick to get from Auckland to Opua, even by plane and road.

I would appreciate any advice/help you can provide for us to track down our BBQ tray.
Failing that, can you commence proceedings with AustPost to tyrack the item down, or get a warranty claim going."
