### ISSUE TITLE
Centre Cockpit Locker - Broken Hinge to teak lid

### ISSUE THREAD

**Issue by pcbaston** [CanberraOceanRacingClub/namadgi3#698]
Allister Polkinghorne sent a message advising that the centre cockpit locker had a broken hinge.  See photo.

![IMG_20230511_150841](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/fc857e69-c395-411d-8da0-00fa5dec47f4)

Not urgent yet, but a replacement should be sourced.

**Comment by pcbaston** [comment]
An OEM replacement may be found at SVB website- page https://www.svb24.com/en/category/hinges-fittings-for-boats and need crew to confirm which one by dimensions. Belive it may be the ROCA Stainless Steel Hinge / 24 x 24 x 30 mm.   Once confirmed, a local alternative may be found.

**Comment by smr547** [comment]
Hi Paul,

I think you are right [these are the correct replacement hinges](https://www.svb24.com/en/roca-stainless-steel-hinge-24-x-24-x-30-mm.html). The screw spacings closer to the pivot are a litle wider in the new units but a simple hardwood plug glued in the old holes will fix the problem.

[drawing_2020-06-15_13-00-26_ae28e44473224841eb2da9cec977d1d0.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/11580218/drawing_2020-06-15_13-00-26_ae28e44473224841eb2da9cec977d1d0.pdf)

**Comment by pcbaston** [comment]
OK, I'll order 2.
Is there a local agent or is it best/quicker to get direct from SVB?

Paul Baston

**Comment by pcbaston** [comment]
PS. I'm still in Vietnam and working remotely, sporadically.

Paul Baston

**Comment by pcbaston** [comment]
Paul
FYI Hafele also make these hinges. See link below
If ay are available in Italy, I am at Viareggio (Boat building place) and can try pick up.
In the meantime I will use the ROCA drawing as a guide and see if I come across any.
I will be on the boat in a couple weeks.
I will let you know how I go. (Via Whatsapp)

https://www.ebay.it/itm/125740101255?_trkparms=amclksrc%3DITM%26aid%3D1110006%26algo%3DHOMESPLICE.SIM%26ao%3D1%26asc%3D20200818143230%26meid%3D0c9df28712254a56867e46a3de22048e%26pid%3D101224%26rk%3D2%26rkt%3D5%26sd%3D234670440361%26itm%3D125740101255%26pmt%3D1%26noa%3D1%26pg%3D2047675%26algv%3DDefaultOrganicWebV9BertRefreshRanker%26brand%3D-+Senza+marca%2FGenerico+-&_trksid=p2047675.c101224.m-1

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603
______________________________________________________________________________________
IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail

**Comment by pcbaston** [comment]
Sam,
I don't think these hinges are what we need. They would need some
modifications to the cockpit hatch to fit as they are longer. The ROCA ones
referenced are small and, although no none has confirmed size matches
current hinge, they look the most likely candidate.
I'll order two from SVB and speak to skipper once they arrive.

I thought you'd be back by now, so thanks for the offer to source in Italy.

**Comment by pcbaston** [comment]
OK. I tried to order online from SVB24.com but when I attempt to pay, there is no shipping included. A bit wary of the additional cost later.. So I used PayPal and, including shipping, the cost was 1700 Euros - so, obviously, I'm not paying that stupid price to ship two hinges.  
I sent a query to SVB24.com via email and have not received a response for 2 days, so this may be a futile effort.
Watch this space......

**Comment by pcbaston** [comment]
I cancelled the SVB24.com order due to excessive postage costs.
The nearest replacement hinge found at whitworths is [this 72x40mm](https://www.whitworths.com.au/stainless-steel-flat-hinge-72mm-x-40mm) @ 10.95 ea. 
Peter Ottesen advised me that he repaired the hatch cover wusing plastic, which appears to be providing a good temporary solution.
Added to maintenance period in Fiji, New Caledonia or Southport.

**Comment by DimitD** [comment]
I have sourced hinges from EBay, and will fit next time boat is at berth in Sydney

**Comment by pcbaston** [comment]
Are the hinges available other than SVB24?  No one seems to want to modify the teak for an alternative, so we seem stuck to OEM.  Any thoughts. Should we purchase from SVB24? Are there other items to ameliorate postage charges (they send everything DHL Priority Express).

**Comment by DimitD** [comment]
![image](https://github.com/CanberraOceanRacingClub/namadgi3/assets/114486705/d12f95e1-9879-403a-84da-e9935a6724b0)


I ordered these 2 months ago and they just came in. Happy to install next time I'm in Sydney and the boat is at berth. We have two spare's now as well

**Comment by DimitD** [comment]
Paul

Not sure if you saw the note on Github, I have hinges in hand now and will
install next available.

Thanks

*Dimitri Dermatis*
Director
Living Design Projects
10/1 Pirie Street, FYSHWICK ACT 2609
m 0417 687 264
e  ***@***.***

**Comment by smr547** [comment]
Well done Dimitri -- the hinges look good.

**Comment by pcbaston** [comment]
Dimitri,
Yes, I saw the note. Glad you advised me because I was going to order them
too. I tried a year ago, but the DHL Express postage was stupidly high.
Well done.
Please be aware you may need to add something to the screw holes in order
to strengthen. Your a builder, so I guess you'll have a solution handy. I
trust the hinges come with screes as I don't know where the screws are. I
may have taken them home by mistake - I'll search the packets of rubbish I
was clearing out of the bilges wet.
Let you know when I'm home

I also need to do some Maintenance on the boat,so if you have a day
available (the boat that is), let me know and I'll try to come down to do
electrical stuff.

Paul Baston

**Comment by DimitD** [comment]
Repaired

![image](https://github.com/CanberraOceanRacingClub/namadgi3/assets/114486705/8fd0190e-0eb0-424d-84b2-57adef9f8114)
