### ISSUE TITLE
Engine Room - Fan noisy at start

### ISSUE THREAD

**Issue by pcbaston** [CanberraOceanRacingClub/namadgi3#699]
Skippers have reported a noisy engine room fan at engine start. The noise goes away after starting - possibly because the fan stops.  The latest skipper, Michael Martin, reported that the noise is increasing - most probably bearings failing due to no maintenance. 
The exact fan cannot be identified without further advice (photos) of installed unit, however, several are available from SVB24.com (the Bavaria spare parts shop in Germany) for approx EURO 50-100 + shipping.  I expect any blower fan will suffice as long as the voltage, diameter and capacity (volume of air) are compatible.

Need someone to either engage a local agent in Fiji or identify the suspect noise maker.
@smr547 @peterottesen @pjwain @mrmrmartin

**Comment by pcbaston** [comment]
Fan no longer making noise. Fully operational.
Issue CLOSED

**Comment by pcbaston** [comment]
Fan noise heard by other skippers. Issue reopened.

**Comment by pcbaston** [comment]
Fan not available or identifiable at SVB24.com.
Identified as a 178mm diameter fan

Web search found one suitable replacement:
Vetus 17812 engine room fan. 

Available at a few Australian boating suppliers.
Cheapest found $230.

Fan connected via two wires behind ducting in locker between adt cabins, connected via automotive spade connectors and taped up.

![IMG_20230922_181714549](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/56319350-8440-43af-b806-a62a358a1677)
![IMG_20230922_174012191](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/db64adb7-9429-4b5d-bbde-620f057d2a33)

**Comment by smr547** [comment]
@mrmrmartin @pcbaston  -- have we sourced a replacement fan? We can have it installed at Boatworks?

Please comment on GitHub or by return email

**Comment by smr547** [comment]
@mrmrmartin has advised by phone:

> Just to let you know I have purchased an engine room exhaust fan to replace the one with the stuff bearing.
> I or Greg will pick it up from the Coral Sea Marina
> Cheers

**Comment by mrmrmartin** [comment]
Yes to be picked up by Greg or I at the Coral Sea Marina

**Comment by smr547** [comment]
Fan was replace in Airlie Beach -- closing this issue
