### ISSUE TITLE
Refrigerator - Broken Door Push Lock

### ISSUE THREAD

**Issue by pcbaston** [CanberraOceanRacingClub/namadgi3#700]
Sam reported:
"While Dimitri and I were fixing the fridge, we had a look at the faulty door latch. The main spindle had a sheared pin and could not be fixed. See pic attached. I am hoping these will be readily available before I return and can replace. If you are around town maybe, ask around?"

It is not apparent what the broken part is - the knob or the latch mechanism - have asked for clarification.

![pro-HQ0pXjtA](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/7309d3bf-ef05-4fbd-bbaa-9772df8ead03)
![pro-lNblIm2M](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/484ddf30-6559-42ac-8b75-01731d208417)
![pro-VzUrTF2z](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/7737103a-7df0-401b-9ef9-5f9d5e79d5bb)

**Comment by pcbaston** [comment]
Bavaria (SVB24.com) has the black/yellow part listed as a [Midi Push Lock](https://www.svb24.com/en/bavaria-midi-push-lock.html) - Bavaria Part 312295 at EU7.52.  Postage from EU is prohibitive.  
Will seek a source in Australia if this is confirmed as the broken component.
This may be suitable - [Push Button Lock](https://www.myyacht.com.au/online-store/p/push-button-lock) available from MyYacht online in Australia.

**Comment by smr547** [comment]
Assigned for Boatworks -- would be good if we can have the spare part ready.

**Comment by smr547** [comment]
Repaired at Boatworks. Closing this issue
