### ISSUE TITLE
Autohelm - clunking noise when in high demand operation (large sea)

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#708]
The noise is nasty like metal on metal impact sound.

Problem was improved by not eliminated by tightening the steering cables. Does this adjustment impact rudder alignment?

See also #566 

@mrmrmartin @pcbaston @peterottesen

**Comment by pcbaston** [comment]
Steering cables loosened by two turns each back to original setting. Seems to be slack in cables again, but this is unrelated to 'clunk' noise during operation.

Clunk appears to be the chain pulley slipping one link (chain does not appear to jump and steering unaffected). Assume it is a 'clutch' or other safety mechanism that allows motor to slip when under high loads.  

Clunk does not occur during operation in calm conditions where demands are not high.

Need to read Garmin Autohelm manual for more info.

**Comment by pcbaston** [comment]
Believe the Autohelm motor to be provided by Jeffa Steering, as per the entire steering system. Autohelm [manual](https://jefasteering.com/product/sprocket-drive-unit-200-nm-12-volts-30-to-50/) does not show a friction clutch, but has two pins that are electronically controlled to connect the planetary gearbox to the output shaft (and hence steering chain). When Autohelm is off, these two pins disengage to allow manual helming.

**Comment by smr547** [comment]
@mrmrmartin reports that steering was inspected and adjusted in Airlie Beach. See attached invoice.  We'll close this issue for now but future skippers will need to keep an eye on it.

top job Michael, thank you for organising the fix

[Invoice_2451_Namadgi.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/12811069/Invoice_2451_Namadgi.pdf)
