### ISSUE TITLE
Jib sheets needs to be replaced 

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#712]
Excessive chaffing has degraded these lines

**Comment by pcbaston** [comment]
Size / diameter and length?

**Comment by CORCpete** [comment]
I suggest does not warrant Priority 1.  The sheath has worn in several places but the sheets will probably last a few more months.  Check length and diameter (existing) when on board and check whether boats now run slightly smaller diameter sheets (which means they will pass through blocks easier and will not weigh sails down as much in lighter breezes).

**Comment by CORCpete** [comment]
See these links

https://www.yachtsandyachting.com/news/248754/Whats-The-Right-Sheet-For-My-Boat

"The rule of thumb with jib sheets is 1.5 times the boat length. Jib sheet length is governed by the lazy sheet, which needs to be long enough to reach the lazy winch with slack, and have a bit to spare."  And to be able to pass over the spinnaker pole.

https://cableandchain.com.au/sheets-jib-genoa

I might check with the sailmaker, Ben.

**Comment by CORCpete** [comment]
I spoke with Ben.  His recommendations are:
-10mm, but check to see that this is okay for the self-tailing on the winches (what size are our current sheets?)
-dyneema/spectra core, or a blend of dyneema and polyester
-polyester sheath or cover, but having dyneema in the cover increases abrasion resistance
-1.5 to 2 times boat length (check existing)

**Comment by smr547** [comment]
Inspected jib sheets at Boatworks -- they are stuffed and need replacing -- will get measurements and discuss with the rigger. Perhaps we can bring the spare line from Canberra and make our own sheets prior to the delivery passage south?

@CORCpete @Christopher-w-green

**Comment by CORCpete** [comment]
We have 40m of new rope in the Fyshwick storage. 15mm. I suspect polyester core and sheath/cover. They are marked as a spinnaker halyard from N3, but never used. I am told our old sheets are each 17.4m, and are a bit short. I am thinking 2x20m is plong enough. I expect we would have to whip the ends. This will save some money. If buying new, I would have encouraged a poly/dyneema core.  Sent from my iPhoneOn 3 Nov 2023, at 12:48 pm, Steven Ring ***@***.***> wrote:﻿
Inspected jib sheets at Boatworks -- they are stuffed and need replacing -- will get measurements and discuss with the rigger. Perhaps we can bring the spare line from Canberra and make our own sheets prior to the delivery passage south?
@CORCpete @Christopher-w-green

**Comment by smr547** [comment]
New Jib sheets installed by Rope Solutions. Sadly the planets did not align to allow our spare rope to be transported to Coomera. We will keep this line and use it next time the sheets need to be replaced


![IMG-0617](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/2dc3abe0-5b8a-418c-849b-24ea508d9c57)

![IMG-0618](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/157d1501-2c0d-4899-99e6-cb5301f8c840)
