### ISSUE TITLE
Replace or repair knurled bolt from anchor winch

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#716]
The knurled head bolt is bent preventing full tightening. 

NOTE- this is to be tightened finger tight only so that the anchor guide/cover can be removed quickly if there is a jam in the anchor chain exit point.

**Comment by pcbaston** [comment]
Several alternatives have been identified on eBay and Alibaba. A direct replacement/spare could not be identified through a web search. Contact with a sales agent for Muir winches may assist.

Recommend the original bolt be straightened in a vice first. Bolt is held onboard at the companionway shelf (winch handles stored below).

**Comment by smr547** [comment]
Both damaged bolts have been replaced by new, hex head, M8 stainless steel bolts

Closing this issue
