### ISSUE TITLE
Forward hatch port cabin leaking

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#719]
Pressure adjustment required?
Clean and lubricate seal done but not successful

@mrmrmartin @pcbaston -- from skippers report

**Comment by pcbaston** [comment]
Hatch closure pins? adjusted with allen key to provide correct seal. Hatch seal now operative.
Issue CLOSED.

**Comment by smr547** [comment]
Hi Paul,

@mrmrmartin reports 

> The forward hatch latch bolt has been bent which means the hatch will lock but not seal the hatch
> The part name is Southco and the number is 2
> I don't have good internet here so can someone check is the part is available in Airlie and get back to me please

do we need to reopen this issue? I'll open it just in case.

**Comment by smr547** [comment]
On inspection at Boatworks the seal has parted from it's housing. SeaSpray to fix.

**Comment by smr547** [comment]
Re-seated by Chris from Sea Spray Marine. 

Chris pointed out the correct way of closing the hatch -- it required the hatch arm tightening mechanism to be in the loose position before closure. If it is "tight" or locked, under pressure is place on the hinges and leaks and breakages will ensue. I'll write a Notice To Skippers entry.
