### ISSUE TITLE
Replace genoa (headsail) -- failed on passage

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#720]
Sail has delaminated with large holes opening up during the passage from Noumea to Townsville.

@peterottesen has asked for a quote from Hoods Sails. !Budget=$12000

@mrmrmartin

**Comment by CORCpete** [comment]
Ordered new sail from Hood, confirmed in writing 5 October, to be delivered 4 December.

**Comment by smr547** [comment]
Thanks Pete, I note that you have booked the sailmaker for 4/12/23 to fit the new sail and make any adjustments. You also plan to discuss tuning of both headsail and main. Thanks for the great planning on this.

@delcosta -- Sam, please note 4/12/23 as a maintenance day in the schedule 
@pcbaston @mgrybaitis for info

**Comment by pcbaston** [comment]
Where is the Sail. It's the end of January and it's not onboard. Status update please!

**Comment by CORCpete** [comment]
Hood failed to finish the sail and deliver in December as promised. I spent 4 days in Sydney in early December before giving up and Ben admitting that he could not promise a date before Christmas. I interpreted this as getting bumped by last minute work for SHYR race crews. I spoke to him last week - he was on holidays - and he will deliver and we will test it, and check the mainsail, during my booking in February. Sent from my iPhoneOn 22 Jan 2024, at 10:23 pm, Steven Ring ***@***.***> wrote:﻿
@CORCpete has been dealing with Ben at Hoods sails. Peter, can you give us an update please?

**Comment by pcbaston** [comment]
Thanks All for the update. We thought as much (re SHYR). Looking forward to
a bigger job for SPS24 Regatta.

Paul Baston

**Comment by smr547** [comment]
New headsail has been installed. @CORCpete will write up handling instructions as recommended by Ben from Hoods sails

We need to dispose of the old torn sail -- possibly in a dumpster at Batemans Bay
Closing this issue

**Comment by pcbaston** [comment]
No. Give it to someone to make sail bags, etc. Recycle.
I'll try to find someone if you can't,but I'm on the road for three weeks.

Paul Baston

**Comment by pcbaston** [comment]
Steve, Peter,

What is the status of the old jib? I have someone who will take it off our
hands and turn it into sail bags, etc.

Cheers,
Paul Baston

**Comment by smr547** [comment]
Hi Paul,

It's still on board and due to be removed at the Bateman's Bay working bee. I wonder if we have other other old sails that the person may be interested in. @CORCpete and @delcosta  may care to comment.

Where is your contact located and how would we organise transport?

regards
Steven

**Comment by pcbaston** [comment]
He's able to pick up in Sydney. Just need to make a connection. Lives in
Emina, Central coast?

I've msg tonight.need to contact Dimitri tomorrow.

Paul Baston

**Comment by pcbaston** [comment]
See associated issue #792
