### ISSUE TITLE
Sandblast hull as part of antifoul application

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#722]
There is evidence of paint peeling from previous poor applications.

**Comment by smr547** [comment]
[Video of hull November 2023](https://drive.google.com/file/d/1gEkMYStFON-yNBKJPFD9GLDh6VPn-2Fw/view?usp=sharing)

**Comment by smr547** [comment]
Peter Pope, our surveyor, has advised that the antifoul on the hull has failed and it, together with the older layers are no longer binding satisfactorily. He strongly advises us to incorporate a "light sandblast to the gelcoat" as part of the current maintenance work. This will add about $10,000 to the cost of the antifoul application and take an extra week to 10 days to complete. Two quotes have been received -- $14,000 and $15,000

An alternative is to have the hull sanded and antifouled in expectation that the coating will degrade quickly. It is likely that the sandblasting and recoating will be necessary within 6 months. Given the additional sanding required I'd expect this approach will cost around $5-6k

This second option is attractive from a scheduling perspective but is both costly and potentially disruptive.

I recommend that we bite the bullet and have the sandblasting done now.  I guess the treasurer will need to look at the finances and Sam and I will have some delicate negotiations with the next delivery crew.

**Comment by Christopher-w-green** [comment]
Looks much worse than it was last year.

**Comment by smr547** [comment]
Sandblasting and antifoul work done by Affordable Antifoul at the Boatworks

![IMG_7830](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/d0793e16-a0c1-4665-b743-35b1de7d15b9)
![IMG_7900](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/6ba47014-5566-40fc-8332-23fa1454582c)
![IMG_7829](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/20a34bae-e5d7-4800-ad26-760eff5b842d)
![IMG_7844](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/f198cc81-5865-4ae8-9a66-460dddc57bdf)
![IMG_7873](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/5122129a-4a10-4f49-a04a-996d448b9058)
![IMG_7880](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/3a71ea61-36fa-4667-8744-497e2e4d63e8)


#budget=$15000
