### ISSUE TITLE
Door seals need replacing— all heads and shower

### ISSUE THREAD

**Issue by mgrybaitis** [CanberraOceanRacingClub/namadgi3#723]
Door seals are failing and need replacing

**Comment by mgrybaitis** [comment]
Seals on forward shower door have deteriorated. Replace

**Comment by smr547** [comment]
4.6m of door seal required— per door. Four doors so  18.4m total. 10mm base  — see photo for suggested profile. Great job for working bee.

![IMG_1076](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/ca48944d-6c3a-437e-94fd-f2c8f1f6be08)

**Comment by smr547** [comment]
New door seal material has been purchased and is on board
