### ISSUE TITLE
BBQ control knobs are faulty / seized

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#727]
Allister has tried to lubricate the fitting with some success. Servicing required and new knobs need to be fitted

**Comment by smr547** [comment]
This issue was not addressed at the BoatWorks and the BBQ is now inoperable. 

I think the two control valves and knobs need to be replaced ASAP. I'll try the suppliers mentioned by @pcbaston in comments on issue #693 -- perhaps @DimitD and his excellent crew can do the repair once the parts arrive??

@DimitD @delcosta @mgrybaitis @mrmrmartin @pjwain

**Comment by smr547** [comment]
Message left on website https://www.marinebarbecues.com.au/

```
The control nobs on our Galley Mate BBQ have  worn out and the two gas control valves appear to be seized. The BBQ is otherwise in excellent condition

Can you please supply spare parts to replace these valves and nobs and ship them to an address in Sydney?

Is there a protective cover available for the BBQ as an accessory? A cover would keep the weather out of the valves and extend their life

kind regards
Steven
Maintenance Manager
Canberra Ocean Racing Club
```

**Comment by smr547** [comment]
Our BBQ is a GalleyMate 1100 purchased in December 2021

See the manufacturers [spare parts webpage](https://www.marinebarbecues.com.au/barbecue-parts/#gas_valves). 
A [cover is also available](https://www.marinebarbecues.com.au/product/galleymate-1100-cover/).

**Comment by smr547** [comment]
![Photo of rear of BBQ](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/ee1c01e4-1feb-4156-ae72-85b3dcb3b2a8)

**Comment by smr547** [comment]
I've asked the supplier to provide two replacement gas valves and matching knobs for delivery to Birkenhead Point Marine. Just waiting for a proforma invoice.

@DimitD  and @CORCpete will be interested

**Comment by DimitD** [comment]
OkThanks Dimitri Dermatis 0417 687 264On 6 Dec 2023, at 11:00 am, Steven Ring ***@***.***> wrote:﻿
I've asked the supplier to provide two replacement gas valves and matching knobs for delivery to Birkenhead Point Marine. Just waiting for a proforma invoice.
@DimitD  and @CORCpete will be interested

**Comment by allister-polkinghorne** [comment]
BBQ taps and knobs replaced. BBQ working satisfactorily. Remember to press in the  knob before turning the knob to start. Also, remove the back bimini stay before lighting the BBQ.
