### ISSUE TITLE
Anchor - Windlass control has broken plug fitting 

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#733]
Screw has been over-tightened -- plug keeps falling out

**Comment by pcbaston** [comment]
Where is the plug fitting? The plug fitted in the fwd ropes locker, or the socket connected to the hand control? By "screw has been overtightened", do you mean its been damaged because its been removed and refitted? Photos/part numbers please.

**Comment by smr547** [comment]
Denis Whitford reinforced the plastic screw fitting with tape. This should prove to be adequate. Closing this issue.
