### ISSUE TITLE
Carbon monoxide gas detector - INOP

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#749]
The unit will not power up.

**Comment by smr547** [comment]
![E7526C8E-7DBD-4003-A967-4817DDFF326A](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/f48a47d1-e073-4095-9cab-360719cf3561)

**Comment by pcbaston** [comment]
Check wiring. I suspect a loose/broken connection or blown fuse is the cause.

**Comment by smr547** [comment]
Electrician

#budget=$200

**Comment by smr547** [comment]
Tested the unit today. It powers up and tests ok.

The only remaining issue is that the unit does not automatically power up with the boat in the same way the LPG gas alarm does. The "Opening of the Boat" SOP should contain a dot point to remind skippers to power this unit up.

@pcbaston  will be interested.

Closing this issue
