### ISSUE TITLE
Fit storm tri-sail track to mast

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#75]
Mark Eady rigger
who: Extra cost over contract
timing: Sep-Oct
estimate: $1,500

**Comment by DeeTaylor87** [comment]
@smr547  - Is there any chance the storm sail ended up with Mark Eady???????

**Comment by smr547** [comment]
Sorry Dee. I don't know who Mark Eady is?

**Comment by DeeTaylor87** [comment]
Marc Eady from On Deck Rigging is the Rigging company that Q services got to quote for the jackstay installation. @smr547  @DaveHolt  is there any chance that someone organised the Storm sails to be fitted through Q Services at some point?

**Comment by DaveHolt** [comment]
Not that I'm aware of. I thought the storm sails had been located with Simon?

**Comment by DeeTaylor87** [comment]
No. I messaged him. He said negative. He had been asked a number of times
before. Still trying to solve the mystery

**Comment by DeeTaylor87** [comment]
@jphayden Did we get an estimate of cost from Qservices or Marc Eady from On Deck Rigging?  I'm wondering if the Storm Sail ended up with them?

**Comment by jphayden** [comment]
Mark Eddie was the guy the Quays used to do the rigging for the commissioning 
 He only worked on the new boat and the try sail  and storm job were never  on the boat

**Comment by jphayden** [comment]
Should have added that the tri sail track  was put onto the mast by Marc Eadie  during commissioning
