### ISSUE TITLE
Bow thruster control button is failing 

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#750]
The bow thruster operation is often delayed after the button is pressed, especially when thrusting to port. This suggests the push button control may be failing

![451F8D4A-EE3D-403C-A093-91953A5B5F28](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/b10b8673-b8ce-42c6-8a91-cd90d8e38b30)

**Comment by smr547** [comment]
@DimitD reports that the bow thruster is now randomly activating. A very dangerous situation. Dimitri will disable the bow thruster by removing the fuse. We will have to chase up a replacement cockpit control panel.

**Comment by smr547** [comment]
Request for quote raised at https://www.amisales.com.au/catalogsearch/result/?q=control&cat=29

**Comment by smr547** [comment]
Local dealer is 

Ship N Shore Electrical
Leisure, Installation Center, Offsite Service

Parsons St Unit 2 / 5, 2039 Rozelle Nsw

Phone: [+02 9818 0500](tel:+02 9818 0500)

I've sent them an email and will call tomorrow

**Comment by smr547** [comment]
Hi Dimitri and Peter,

Here is a supplier who has a new control panel in stock. I strongly
recommend getting a new replacement part. We cannot afford a repeat of this
fault while underway.

kind regards
Steven

---------- Forwarded message ---------
From: Peter Irvin ***@***.***>
Date: Mon, 4 Dec 2023 at 12:01
Subject: SLEIPNER TOUCH PANEL
To: ***@***.*** ***@***.***>
Cc: Sales NSW ***@***.***>


Hi Steve



The ROUND TOUCH PANEL 12/24V is 0510250 and in stock



List Price $293.82 ex GST



Freight – allow 15 ex GST



Thanks for your enquiry.



*Kind Regards*

*Peter Irvin*
Sales Representative NSW

[image: ***@***.***



*AMI Sales* | Compass Business Park, Unit 202, 27 Mars Road, Lane Cove
West, NSW 2066
*t:* (02) 9816 7100 | *m: *0407 787 099 | *e:* ***@***.***
***@***.***>*
*w:* *www.amisales.com.au <http://www.amisales.com.au/>*  |



[image: ***@***.***

*AMI is a member of the AMI Group of companies*
www.amigroup.co
<https://clicktime.symantec.com/36p7AvKRRN5Pq2eJ8fYP2VK7Vc?u=http%3A%2F%2Fwww.amigroup.co>

*Connect with us:*

<https://au.linkedin.com/company/ami-sales>

[image: image004] <https://www.facebook.com/AMISalesAustralia/>

[image: image005] <https://www.instagram.com/the_ami_group/>

[image: image006] <https://www.youtube.com/user/AMIMarineSales/featured>


[image: ***@***.***

*This document (including attachments) is only intended for its addressee/s
and may contain privileged or confidential information. Unauthorised use or
distribution of this document or any part of its contents, is prohibited.
If you have received this email in error please notify the sender and
delete the email immediately*



[image: ***@***.****Tell us what you think. **To
provide feedback **please click here*
<https://clicktime.symantec.com/3SdUHc8zaY3vpq4uFvBzQBQ7Vc?u=http%3A%2F%2Fwww.amigroup.co%2Findex.php%2Fsurvey>
*.*






-- 
Steven Ring
Maintenance Officer
Canberra Ocean Racing Club
m: 0417 495 268

**Comment by smr547** [comment]
Hi @DimitD 

Thank you from removing the Bow Thruster switch and setting it to dry out. You mentioned that it was looking a little ratty so I think we should take this opportunity to replace it. A new part has been ordered from AMI and should arrive on Wednesday -- [see invoice](https://github.com/CanberraOceanRacingClub/namadgi3/files/13542325/Proforma.Invoice.209136.pdf)
.

AMI are the Sleipner distributor in Australia. The have recommened some local dealers who can help with the Bow Thruster if the switch change doesn't fix the issue:

- Ship N Shore Electrical (see comment above)
- [Katons Electrical Services](https://www.katonselectrical.com/contact/) at the Spit
- [Superior Marine](https://www.superiormarineservices.com.au/) conveniently located at Birkenhead Point -- Talk to Hamish or Richard and say that Peter Irvin from AMI recommended them

I'll leave it to you to contact these service providers if the part replacement doesn't solve the problem.

@CORCpete @pcbaston @mgrybaitis will be interested

**Comment by allister-polkinghorne** [comment]
Bow thruster controller replaced and is working satisfactorily.
