### ISSUE TITLE
Leech tensioning cord torn away at head of mainsail

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#751]
It looks like someone has given this cord a solid yank

@CORCpete @DimitD will be interested

![5E2D08D9-189C-41FE-888C-63AA0A45D5E4](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/a23b4042-4ea0-4f0a-99b8-c350a5611c9b)

**Comment by allister-polkinghorne** [comment]
Block has been lashed back on the headboard and should work satisfactorily.
