### ISSUE TITLE
Neutral button on motor throttle has disintegrated 

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#753]
A new rubber cup is required. 

@DimitD could you please attempt a repair with sikkaflex?

![0578276E-2EA3-4971-835C-E4569BE73E0D](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/400af6d7-c4ae-4576-bb08-bed45caff600)

**Comment by allister-polkinghorne** [comment]
Require new rubber cover. The rubber and neutral button have been reinstalled and are working adequately. Suggest we source a new rubber for a spare/replacement.
