### ISSUE TITLE
Hole in dingy rear startboard chamber 

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#754]
Transverse scrape on the bottom of the pontoon has caused a leak

reported by @allister-polkinghorne

**Comment by smr547** [comment]
see #547 and #549 for contact details of supplier

**Comment by smr547** [comment]
Is our dinghy PVC or Hyperlon?  [See this FAQ](https://www.zodiaconlineshop.nl/en/service/faqs/#:~:text=An%20inflatable%20boat%20or%20RIB,quality%20fabrics%20for%20its%20production.)

[This article](https://www.polymarine.com/advice/pvc-or-hypalon/#:~:text=There%20are%20several%20tests%20to,same%20colour%20on%20both%20sides.) describes how to tell the difference

Each material requires a specialised repair kit.  I'll call the supplier first thing in the morning.

@allister-polkinghorne and @CORCpete will be interested

**Comment by allister-polkinghorne** [comment]
Repaired.

**Comment by smr547** [comment]
Closing this issue
