### ISSUE TITLE
Automatic bilge pump is inoperable

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#758]
The bilge pump is operating continuously (with an associated alarm sounding) despite there being no water in the bilge area. The float switch and pump were recently replaced (#310). I can only conclude that the circuit board controlling the bilge pump has failed and needs to be repaired or replaced.

Until that time, it has been necessary to switch the bilge pump off (via the master panel). As a result we have no automatically activated bilge pump on board.

@CORCpete @DimitD @delcosta @mrmrmartin @pjwain @mgrybaitis @allister-polkinghorne @pcbaston will be interested

PS -- I suspect that this board has failed in the past and caused the bilge pump to operate continuously while dry, resulting in it burning out and requiring replacement at the last bilge check in The Boat Works

**Comment by smr547** [comment]
The circuit board in question is located at the rear of the switch cupboard above the nav station -- alongside the "Land - O - Inverter" switch

**Comment by smr547** [comment]
Placing this on [Notice to Skippers](http://7.southsky.com.au/notice2skippers.pdf)

**Comment by smr547** [comment]
Electrician required -- I suspect the alarm board needs to be replaced
#budget=$500

**Comment by smr547** [comment]
I tested the bilge pump and found it to be operating normally -- Closing this issue -- A reminder will be put on [Notice to Skippers](http://7.southsky.com.au/notice2skippers.pdf) for a few weeks.

## AUTO switch position
The bilge pump should be kept permanently in the ``AUTO`` position where both ``POWER`` and ``AUTO`` lights will be illuminated.

![bilge_pump_control](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/69bbda06-b280-4165-8e09-f7780b406a23)

In AUTO mode the bilge pump is armed and will automatically activate if water lifts the float switch in the bilge.

## Manual Override

The bilge pump can be turned on at any time by

- Moving the control panel switch to the ``MANUAL`` position
- Pressing the manual pump out button on the main control panel -- see photo below

![bilge_manual_override](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/a36ea80a-4554-4daa-a8c3-9f01533abec0)


## Audible alarm

The bilge pump alarm (a high pitched scream) will sound whenever the bilge pump is operating for any reason (auto activation or manual override)

## Fuse

DO NOT REMOVE the fuse in the control panel under any circumstances.


@CORCpete @DimitD @delcosta @mrmrmartin @pjwain @mgrybaitis @allister-polkinghorne @pcbaston will be interested

**Comment by pcbaston** [comment]
Steve,
Is the bilge pump alarm fixed? Or was it not faulty?
Understand instructions. Will incorporate into a SOP.

Paul Baston
