### ISSUE TITLE
Transom Lifelines - Pelican Clip needs repair/replacement

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#760]
The split ring parted from the clip and allowed the bolt and spring to come loose. The spring went overboard but fortunately the bolt did not. 

A new stainless steel spring is required -- I'll provide a photo to give dimensions.

Meanwhile the clip can be held in place by moving the tape the clip lever.

**Comment by pcbaston** [comment]
What size is the hook? That will give you access to the correct spring at marine chandlery. Else you are in the hardware world with possibly different stainless steel/spring steel.

**Comment by pcbaston** [comment]
Here's what a lifeline pelican hook used on a lifeline should be:
![image](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/79f497a7-0fb9-4bbe-9a47-ab3cb954719c)
No circlips, no springs, nothing to routinely break.

**Comment by smr547** [comment]
Brilliant!! Couldn't agree more. I'll make this a shopping list issue and get the new clips ASAP.

**Comment by pcbaston** [comment]
I can go to whitworths Drummoyne on Monday. Look for spring first as
replacements are $55 ea or so!!!

Paul Baston

**Comment by pcbaston** [comment]
Issue CLOSED. Duplicate issue 772 closed 11 Apr 24.
