### ISSUE TITLE
Swim Platform Roller Shear Pin 

### ISSUE THREAD

**Issue by delcosta** [CanberraOceanRacingClub/namadgi3#761]
The swim platform winch roller shear pin has sheared.
We think this was a s a result of the platform being hit with a wave in the fully open position, flipping it up and dropping heavily straining the roller. 
The situation was probably exacerbated due to the stays stays being too long virtually sitting the platform on the surface of the water when fully down.
![20240101_090215](https://github.com/CanberraOceanRacingClub/namadgi3/assets/30795874/2be4620d-5368-434d-8557-8e5e53c8bc97)
![20240101_090145](https://github.com/CanberraOceanRacingClub/namadgi3/assets/30795874/69424fdc-1743-4774-808c-f52b9aa40211)

**Comment by smr547** [comment]
Sam McDonald has put some spare shear pins in the stainless box. We need to buy a 3mm pin punch (see #763)

Also need to shorten the strops holding the swim platform up

Notice to Skippers regarding the correct deployment of the swim platform

**Comment by smr547** [comment]
This issue can now be closed

* Sam McDonald has repaired the broken pin and has also provided spare roll pins. 
* A pin punch has been put on the shopping list (#763)
* An issue has been raised to shorten the dyneema strops (#764)
* A note has been published in [Notice to Skippers](http://7.southsky.com.au/notice2skippers.pdf) outlining care to be taken with the Swim Platform (#765)

Thanks again @delcosta for raising this issue (complete with photo!!)
