### ISSUE TITLE
Do not use Oven -- Gas Line is leaking and dangerous

### ISSUE THREAD

**Issue by delcosta** [CanberraOceanRacingClub/namadgi3#762]
The gas link between the oven control knob and the oven is leaking and Dangerous. DO NOT USE Oven.
Witnesses a small flame burring behind the stove near where it joins the oven. Will need Replacement

**Comment by smr547** [comment]
Hi Sam, thanks for putting this important issue into GitHUB. I've added two labels: ``Priority_1`` and ``Notice`` to ensure the issue appears in [Notice to Skippers](http://7.southsky.com.au/notice2skippers.pdf)

Sam McDonald has found a website that can supply parts for our stove. I've noticed that the burners are not working properly and their is rust developing at the bottom of the stove -- Perhaps we should consider replacing the whole unit.

In the first instance we need to find a Gasfitter in Sydney -- Does anyone have a contact? @CORCpete @pjwain @DimitD @pcbaston @mgrybaitis @mrmrmartin @allister-polkinghorne

**Comment by smr547** [comment]
[Chris the Gasfitter](https://contacts.google.com/person/c7084467831017252730) from [Ezyflow Plumbing](https://www.eze-flowplumbing.com.au/)  will come to the boat next week -- preferred location is The Spit marina or nearby.  

I'll message Jeff Butler to let him know and will also coordinate with Chris.

**Comment by SamMcDonald2538** [comment]
Steve, if we are getting the gas fitter to undertake repairs to the oven, it may be a good opportunity to replace the cooktop burners.

**Comment by allister-polkinghorne** [comment]
Or replace the whole stove?

**Comment by smr547** [comment]
I consider the stove due for replacement. The burners are corroded and not throwing the flame correctly and there is rust in the base. My recommendation would be an ENO brand stove which we have on Trilogy. An excellent Stove with plenty of spare parts available.  

@pjwain @mgrybaitis @mrmrmartin @SamMcDonald2538 @DimitD @pcbaston @CORCpete 

#budget=$3000

**Comment by smr547** [comment]
[Here is a potential replacement stove](https://www.boatgearaustralia.com.au/eno-1813-2-burner-stove-with-oven-grill-gascogne-s). The gasfitter will be on the boat tomorrow so we will get his advice.


@pjwain @mgrybaitis @mrmrmartin @SamMcDonald2538 @DimitD @pcbaston @CORCpete

**Comment by delcosta** [comment]
Thank you, Steve, for the gas stove and gas works details.
I am very much in favour of replacing the stove which does get extraordinary use. It is a significant expense and we need an urgent repair.
If we can repair the leaking oven line, the existing is immediately useable,
However, I would recommend to committee that the Evo replacement would be appropriate immediately if the model is available.

Regards,
Sam DeLorenzo
Mobile & WhatsApp: +61 411 165 835
PO Box 3553, Manuka ACT  AUSTRALIA 2603
______________________________________________________________________________________
IMPORTANT
This e-mail and any accompanying attachments are intended for the sole use of the addressee(s) and may contain confidential information. If you are not the intended recipient (or authorised designee), please disregard the contents of this e-mail, notify the sender immediately and destroy all copies of this e-mail

**Comment by smr547** [comment]
Let's budget for a replacement stove
#budget=$3500

**Comment by smr547** [comment]
Thanks Sam ( @delcosta ) -- just saw your comment

**Comment by pcbaston** [comment]
All,  aside from the lovely discussion, what is the actual status of the repair.  Peter Wain (current skipper) just advised me the oven is still suffering from a gas leak and flame (Extremely DANGEROUS on a yacht). So I can only assume that the gas fitter either didn't attend or the repair has failed. Either way, I don't know from the discussion above.  
A reminder to keep your edits to facts and not a general discussion that can occur either by phone, in person or separate email.
Is there a replacement coming?
Is the gas fitter due a visit?
@delcosta @smr547 @SamMcDonald2538 @allister-polkinghorne @mgrybaitis @mrmrmartin @CORCpete should be interested.

**Comment by smr547** [comment]
Sorry Paul, you make an excellent point --  I've not kept GitHUB up to date on this important issue. There have been emails and discussions on this important issue. To update:

On 12 Jan I asked [Chris Smith](https://contacts.google.com/person/c7084467831017252730) (the Gas Fitter) specifically if he had investigated and fixed the leak at the back of the oven -- his reply was:

> As for the leak , once the old supply hose was changed. I had the stove and oven lit multiple times. I checked thoroughly  using my gas sniffer tool and gas bubble spray on all accessible pipes  / openings on the appliance. I could not replicate the flame you mentioned. The appliance is certainly old and the metal pipes that run into the back of the unit are rusted. I would suggest to replace the stove in the near future but as I instructed Jeff the skipper. I could not find any fault whilst operating it myself. But to be mindful and keep a watchful eye on it whilst in use . 

Around that time, in discussion with @pjwain, he said he could not find a fault. 

Yesterday, @pjwain reported that the there was a flame at the back of the stove resulting from a leak in the valve to oven burner supply line. 

My response is:

> I think we should get him (the Gasfitter) back to either fix the stove (which may require additional parts) -- or to fit a replacement stove. I'd prefer the latter. Peter, you are in the best position to advise the way forward.

Issue remains priority 1 -- Urgent fix required.

**Comment by smr547** [comment]
I just spoke with the plumber/gas fitter -- Chris Smith tel:+61439025458

```
Important new information: While Chris did check the stove for leaks he informed me that 
Gasfitters are only authorised to repair plumbing and fittings up to the appliance. 
They (including him) are NOT authorised to work on the appliance itself -- 
that is the responsibility of the Appliance Manufacture and their accredited gas fitter. 
```
That would suggest that we would be better off buying a new stove and having Chris install it. These stoves come with a lengthy warranty -- it might be a good policy to replace future stoves when the warranty runs out -- just a thought.

Chris is booked solid next week but could do the installation after Australia Day.

@mgrybaitis @mrmrmartin @pjwain @CORCpete (unsubscribed at this stage)

**Comment by smr547** [comment]
Photos of stove

![IMG_0379](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/f46a1100-6528-45f9-a4b0-2f5bb395f7e8)
![IMG_0380](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/3728c3b7-a002-44f0-9735-42252ea8764a)

**Comment by smr547** [comment]
Our stove does NOT get rave reviews in [this blog](https://www.myhanse.com/techimpex-cooker_topic13778.html)

The blog refers to "one distributor that supplies all yacht gas cookers in Australia" lamenting that this gives them a monoply and that prices are, as a result, quite high. (Welcome to yachting!!)

That distributor appears to be [Ocean Solutions International](https://oceansolutions.com.au/eno).

I've messaged the company asking a raft of questions about warranty and repair.

**Comment by smr547** [comment]
From [this blog](https://www.cruisersforum.com/forums/f124/advice-for-new-gas-oven-220380.html), there appears to be a minefield of regulations surrounding gas stoves and gas installations in general.

**Comment by pcbaston** [comment]
I looked online and there are essentially three manufacturers available
here. Prices seem to equate to UK and Euro prices, nothing exchange rates.
Look at SVB24 and boatgear Australia, Arnold's,etc

Paul Baston

**Comment by smr547** [comment]
[This 2 burner ENO stove](https://www.boatgearaustralia.com.au/eno-1413-2-burner-stove-with-oven-grill-open-sea-g) seems to best match our requirements. I spoke with Brett from Ocean Solutions in Queensland. All of the retail sails of these stoves are delivered from his warehouse. At present he has a one unit in stock. I've asked our gasfitter in Sydney to act as a retailer and to source the stove from Ocean Solutions for installation on Namadgi within the next couple of weeks. Chris will provide a quote for the supply and installation.

**Comment by smr547** [comment]
[Invoice received](https://github.com/CanberraOceanRacingClub/namadgi3/files/14117368/EZE-FLOW.Plumbing.Invoice.204534.for.3.239.50.pdf). Installation scheduled for Thursday next week.

**Comment by smr547** [comment]
Great, thank you!

Stove installation booked for 12.30pm Thursday 8th Feb at Birkenhead Point
Marina.

Contact details on the day will be

   - Peter Ottesen (Skipper): 0419 732 043
   - Chris Smith (Gasfitter) : tel:+61439025458

kind regards
Steven



On Wed, 31 Jan 2024 at 13:31, Chris Smith ***@***.***>
wrote:

> Morning Steve,
> As long as the stove has been delivered, yes that should be fine. I’ll
> book it for 12.30pm Thursday 8th Feb.
>
> Kind Regards,
>
> <https://linktr.ee/ezeflow_plumbing>
>
>
> On Thu, 1 Feb 2024 at 8:25 am, Steven Ring <
> ***@***.***> wrote:
>
>> Hi Chris,
>>
>> Would you be available Thursday afternoon next week for the installation
>> at Birkenhead point?
>>
>> kind regards
>> Steven
>>
>> --
>> Steven Ring
>> Maintenance Officer
>> Canberra Ocean Racing Club
>> m: 0417 495 268
>>
>

-- 
Steven Ring
Maintenance Officer
Canberra Ocean Racing Club
m: 0417 495 268

**Comment by smr547** [comment]
New oven installed -- closing this issue
