### ISSUE TITLE
Shorten swim platform dyneema strops by 3cm

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#764]
The current strops are too long and allow the swim platform to sit too low. In this position the platform can be hit by waves possible causing injury to people and/or damage to the winch drive mechanism. 

Notice to Skippers will be issued regarding due care

We need to have a rigger shorten these strops (by 3cm) as a matter of urgency.

@CORCpete will be interested

**Comment by pcbaston** [comment]
Peter Wain advised he shortened the strops by tying a figure 8 knot in dyneema strop. Platform is above flat now. Knots cannot be undone. Stuck with new height above horizontal.
Issue should be Closed.

**Comment by smr547** [comment]
The knots will lower the breaking strain of the lines by about 40%. If we are happy with this I'll close the issue. Otherwise, it's a job for a rigger (or talented CORC member) to splice new lines.

Closing for now.
