### ISSUE TITLE
Drain in Gas locker broken away

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#769]
Reported by @SamMcDonald2538 — Very dangerous and urgent fix required

![IMG_5582](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/fb7c404a-0156-4a6a-a791-319fe505fd40)

![IMG_5581](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/803a54b9-6932-485a-b7e8-c489d6440cd1)

**Comment by smr547** [comment]
#budget=$500

**Comment by pcbaston** [comment]
It's been fixed. Close the issue.

**Comment by smr547** [comment]
Closing this issue but noting that the gas fitter has recommended the entire gas locker liner be replaced. See #733
