### ISSUE TITLE
Safety - Transom lifelines need repair

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#772]
Refer issue #760 

@pcbaston has recommended a design with very few parts that can be lost!

![image](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/79f497a7-0fb9-4bbe-9a47-ab3cb954719c)

**Comment by SamMcDonald2538** [comment]
Probably need to confirm this type is Cat-1 compliant.

**Comment by smr547** [comment]
Good point Sam. 

Dear @pauljones17, do these Pelican Clips meet Cat 1 standards. They are appealing because of the lack of moving parts (that can be lost). You opinion would be most welcome.


![image](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/79f497a7-0fb9-4bbe-9a47-ab3cb954719c)

**Comment by pauljones17** [comment]
The only rule I have located thus far is 3.12.6(e) (which states "All wire, fittings, anchorage points, fixtures and lanyards shall comprise a lifeline enclosure system which has at all points at least the breaking strength of the required lifeline wire." [which for Namadgi is 5mm of 316 stainless wire {Rules 3.12.6(c) and 3.12.6(f)}].
However, I do not recall seeing them used in a lifeline system - perhaps because of the ease of undoing them.  Suggest contact CYCA (Andy Coyle, who is Chief Safety Assessor), for a definitive answer.  It may be that for assessment a couple of turns of amalgamating/electrical tape around the slide might be considered sufficient to counter the ease of undoing them - or not.

**Comment by pcbaston** [comment]
If we need to put anything on them to stop them coming undone, it's a no
brainer.

I've measured the existing Pelican hook spring and can buy 10 for under $10
on eBay.

Paul Baston

**Comment by pcbaston** [comment]
I've moved the spring from lower clip to upper clip where it's needed more for safety.

**Comment by pcbaston** [comment]
Springs were measured at 30mm long x 6mm diameter. I am guessing (no micrometer to measure) the wire size to be 0.6-0.8mm.
 
![IMG_20240122_092709241
![IMG_20240122_092752691](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/e5c6ec2a-b34e-4f8f-a4b1-52db9e4db4b1)
](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/a3c90217-fd3e-4b1b-9848-86af2d2b3c2f)
![Uploading IMG_20240122_092726130.jpg…]()
![IMG_20240122_092806899](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/e202af5f-d079-4e32-bb4e-7dee321adde4)

I have ordered these: https://www.ebay.com.au/itm/386681234206?var=653978230062&hash=item5a07ff631e:g:HDIAAOSwjpBlrNLQ&amdata=enc%3AAQAIAAAA8JmrhCmLHO8XeMpvWwglQhbv5cpA36xp17Hpth1cOxgO8%2FJmNg%2Bun1qfsRAwmV%2Fi%2FKw1EeNE275YH0vCR%2FjJove3VZgRJOlUoa0GCqIy7uPDj8J9KS%2FGLbo0%2BzE%2Fjw9pnIDPsI%2Br0AobrIS846LQq1kxhbSorPzcoltKOaaoH%2BlX82urAyXlxlEtLAMnSJo4w1lneLTLZqbad%2BmBWBnnyTqOhLJCRSgKxuvklOSPHrP0fDMsOsNqADUUFMYpDyXJFo4ppj7i%2BwZY8gYa88WyQ6x1cBjRGt2dTuoTE9fNN3fNb3e8ZkTEVRO%2BV%2FB81I9Hdg%3D%3D%7Ctkp%3ABk9SR_DKmP2nYw

**Comment by pcbaston** [comment]
In addition, the pool noodle inside the transom safety lines requires replacement and tensioning. It is far too slack at present, more set for leaning against than actually a safety line.  Simply need to tighten the pelican hook on the swaged screw post.

**Comment by smr547** [comment]
Pelican clip is marked No 4 and has an M8  screw thread. Total length of body of pelican clip is 100mm. Two pelican clips have been ordered from Boat Warehouse and should arrive tomorrow or Friday.  We'll get the repair job done of the weekend.

**Comment by pcbaston** [comment]
Pelican Clips have been replaced, foam inserts replaced by C. Green and life lines tensioned adequately. Passed Safety Audit 11 Apr 24.  
Issue CLOSED.
