### ISSUE TITLE
Water Leak - Hot Water System

### ISSUE THREAD

**Issue by pcbaston** [CanberraOceanRacingClub/namadgi3#775]
Peter Wain reported the water pump was continually operating. He isolated and located source of leak prior to handover, but was unable to repair.  Leak was found as a split in the 'now very short' drain line attached to the water heater fill tee-connector.  See photo:
![IMG_20240121_173639934_HDR](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/8b8d2e10-4781-4a62-9875-37eb5a429d99)
The Drain Line is the short one blue line attached to the tee-connector

Although attached to the cold water inlet, the line and tee-connector gets very hot as hot water is circulated back into the heater, possibly to enable water to heat faster or pressure relief?? This excessive heating may be the cause of the leak - the hose split for about 15mm along its length.

**Comment by pcbaston** [comment]
After removing the split hose (by compressing the John Guest connector seal with a screwdriver), the hose was replaced with a longer section (about 60cm long) fitted with compression fittings (in the spare hose bag!) designed for hot water pipe. The tee-connector required several attempts to get a good water-tight seal. 

The new hose has rectified the leaking water and the water pump did not come on at anytime when water was not being demanded out of a tap.

Over the four days of my booking, approx 5 full buckets of water was removed from the bilges and under-deck lockers.

Issue CLOSED.

**Comment by smr547** [comment]
Re-opening this issue

Unfortunately we have another leak in the hot water tank plumbing. This leak is a slow but continuous and is coming from a complex arrangement of pipes associated with the water inlet on the lower side of the tank.

Question for @pcbaston -- Do you think we should have a plumber simplify the plumbing of the hot water tank and, at the same time, replace the "John Guest" (fittings and plastic pipes" with flexible metal hoses and copper fittings? The present arrangement seems overly complex and the plastic pipes/fitting seem prone to leaks.

**Comment by smr547** [comment]
I went hunting for the leak after noticing 

* constant build up of water in the engine bilge
* water in under floor compartments on the starboard side amidships
* fresh water pressure pump activating every hour or two despite no use of fresh water

**Comment by pcbaston** [comment]
I would suggest, that as no other connectors seem to leak, we only need to
address the water heater pipes. John guest make adapter's so that screw on
fittings can be used. It appears to me that we are only ever concerned with
the hot water pipes near the tank. Possibly due to: bending near the
connector, heating effects on pipes, damaged seal due to previous repairs.

Paul Baston

**Comment by smr547** [comment]
Power and Sail Bateman's Bay can source these -- thank you Bob Richards for the research

One Tee and one elbow ordered via Power Sail

**Comment by smr547** [comment]
Water leak fixed -- leak was coming from the pressure valve water return pipe

1. Remove drain hose and associated T fitting -- is superfluous -- the cold water inlet has a non return valve which prevents flooding into the bilge
2. Re-aligned brass cold water inlet fitting to allow pressure relief return to pass over the top of the main water inlet -- this relieved stress from the associated elbow (which was leaking)
3. Re-aligned hot water tempering valve to relieve stress on flexible hose
4. Pressure tested with hot water power on. No leaks observed -- closing this issue.

Spare "John Guest" fittings have been ordered from power and sail.

![IMG-0088](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/29d736af-ece6-4d9e-9949-7f213e7dfa4d)
![IMG-0089](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/c1b7efb1-23f1-4edd-9908-b9c2dc5d8a32)
![IMG-0091](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/a30306ca-c800-484f-bf49-3f0181bbe739)

@mrmrmartin @delcosta @Christopher-w-green @mgrybaitis @allister-polkinghorne will be interested
