### ISSUE TITLE
Bilge Pump Operations

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#777]
Skippers are reminded of the proper operation of the bilge pump.

## AUTO switch position
The bilge pump should be kept permanently in the ``AUTO`` position where both ``POWER`` and ``AUTO`` lights will be illuminated.

![bilge_pump_control](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/69bbda06-b280-4165-8e09-f7780b406a23)

In this mode the bilge pump is armed and will automatically activate if water lifts the float switch in the bilge.

## Manual Override

The bilge pump can be turned on at any time by

- Moving the control panel switch to the ``MANUAL`` position
- Pressing the manual pump out button on the main control panel -- see photo below

![bilge_manual_override](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/a36ea80a-4554-4daa-a8c3-9f01533abec0)

## Audible alarm

The bilge pump alarm (a high pitched scream) will sound whenever the bilge pump is operating for any reason (auto activation or manual override)

## Fuse

DO NOT REMOVE the fuse in the control panel under any circumstances.

**Comment by pcbaston** [comment]
For note. I tested the Bilge Pump operation (Correct) and traced the wiring.  Interestingly, we have a Rule LP9000S Automatic bilge Pump which is connected to a separate Float Switch. The bilge pump can be set to Automatically operate at 33mm (LOW) or 50mm )HIGH) depth of water, so I do not understand the extra complicated wiring for the Float Switch. In addition, there are two +12V power runs from the Bilge 10A Fuse.

See photos:
Bilge Pump
![IMG_20240419_152720429](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/581defc1-60d7-4a1c-a92d-972a6116988c)

Float Switch
![IMG_20240419_155309057](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/d858ad26-2081-483b-96fe-b45281d53335)

Birds nest wiring
![IMG_20240419_152642738_HDR](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/2f2ff62b-621b-4363-a8da-d69f2ee82304)

Brown and extra Red wire carrying +12VDC to the Pump and Float Switch
![IMG_20240419_153557255_HDR](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/08c7b502-f2fb-4f9d-8272-c4c21a210890)

**Comment by smr547** [comment]
My head hurts! All I can  offer is that the Rule LP9000S has three wires -- Neg, +12V auto (from float switch) and +12V manual override. There are two sources of manual override 

1. Main Bavaria push-button panel
2. [3 way switch panel with alarm](https://www.whitworths.com.au/12v-bilge-pump-3-way-switch-panel) in upper cabinet above Nav station

I can't explain where there are two +12V feeds from the main Bavaria push-button panels

I'm wondering if the "OFF" position on the upper panel really does disable the bilge pump. I'd hope not.

The online circuit diagrams are not helpful being of the "amateur auto electrician" variety designed to burn the house down.
