### ISSUE TITLE
VHF handheld radio(s)

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#78]
Buy new one(s) GME donation maybe?
estimate: $650

**Comment by DeeTaylor87** [comment]
Note Cat One requirement

3.25.1 | The following waterproof or   marine standard communication equipment shall be provided:
3.25.2 | A waterproof handheld VHF   transceiver.
3.25.5 | The following emergency antenna   shall be provided: (a) An emergency antenna for each required radio.
3.25.6 | Handheld VHF transceivers   shall:  (a) Have a maximum rated output   power of not less than 5W. (b) Be tested in accordance with the notice of   race.

**Comment by DeeTaylor87** [comment]
RT Marine have the following:
https://www.roadtechmarine.com.au/5w-vhf-marine-radio-transceiver/p/MDC210

https://www.roadtechmarine.com.au/uniden-5w-waterproof-floating-vhf-marine-radio-mhs127/p/MDC232


https://www.roadtechmarine.com.au/uniden-5w-hand-held-uhf-transceiver-uh850s/p/TDC086

https://www.roadtechmarine.com.au/gme-5w-uhf-transceiver-tx6155/p/TDC102
