### ISSUE TITLE
Sails - Lazy jack lines worn - replace

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#789]
Need to be replaced

![IMG_1126](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/6fdc6ae6-feef-47a1-8ca4-42669aa3de95)

**Comment by pcbaston** [comment]
I can repair/replace in Port Stephens if not done beforehand at the Working Bee. I have plenty of Dyneema line (4mm) and would recommend [Ronstan Low Friction Shocks](https://www.ronstan.com/au/shock-blue-suits-5mm-3-16-line-10pack.html) for ends vice rope knots currently used. I can splice Dyneema line easily.

**Comment by pcbaston** [comment]
Replaced 2 rear jack lines. Have some thimbles on order to fit to remaining lines to reduce wear. Thimbles cheaper than shocks.
