### ISSUE TITLE
VHF radio cockpit handpiece

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#79]
Buy one
estimate: $500

**Comment by DeeTaylor87** [comment]
Note Cat One requirements
3.25.1 | The following waterproof or   marine standard communication equipment shall be provided:
(b) | (i) Permanently installed VHF   transceiver (iii) All new permanently installed VHF transceivers shall be DSC   capable.
( c ) | Where permanently installed, DSC   HF/VHF transceivers shall be programmed with an assigned MMSI (unique to the   boat), and where there is permanently installed GPS, be connected to a GPS   receiver, and be capable of making distress alert calls as well as sending   and receiving a DSC position report with another DSC equipped station.   Periodically a test call should be made to AMSA which should be automatically   acknowledged.
3.25.4 | Permanently installed VHF   transceivers shall:
(a) | Have a maximum rated output   power of not less than 25W.
(b) | Have a mast head antenna.

**Comment by DeeTaylor87** [comment]
http://www.raymarine.com.au/display/?id=221

https://www.whitworths.com.au/main_itemdetail.asp?cat=114&item=69741&intAbsolutePage=

https://buy.garmin.com/en-AU/AU/p/28719
