### ISSUE TITLE
Marina Access Batemans Bay

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#799]
The FOB key is stored in the lock box on the south wall of the Marina Amenities Building — see photos

lock box combination is 9853

only one FOB and key has been issued

![IMG_1218](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/c52484c6-0bcb-4a0e-9859-7fdd7102ad00)
![IMG_1217](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/9504c053-5e43-4bfd-a5e9-16b4610b7482)

@mrmrmartin @mgrybaitis

**Comment by mrmrmartin** [comment]
thanks Steven, I have picked up the key from that location before
________________________________

**Comment by mrmrmartin** [comment]
Hi Steven thanks for the info on the lock box.

How was the bar crossing did you have much clearance.

cheers
________________________________

**Comment by mrmrmartin** [comment]
Hi Steven just thought of a couple of questions

Is Namadgi on the south or north side of the basin and did you leave the fridges running?

cheers


________________________________
