### ISSUE TITLE
Spinnaker pole lifting mechanism jammed on mast

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#800]
Line caught in lifting block

![IMG_1241](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/fb5b5383-b63d-4727-b604-92bf91243610)
![IMG_1219](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/6014c38d-23b2-4afc-8048-4403bb9407f4)

@mrmrmartin and @CORCpete will be interested

**Comment by CORCpete** [comment]
That’s nasty.  Do we have a spare block in the spares bag? 

On 26 Feb 2024, at 3:12 pm, Steven Ring ***@***.***> wrote:


Line caught in lifting block

IMG_1241.jpeg (view on web) <https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/fb5b5383-b63d-4727-b604-92bf91243610>
IMG_1219.jpeg (view on web) <https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/6014c38d-23b2-4afc-8048-4403bb9407f4>
@mrmrmartin <https://github.com/mrmrmartin> and @CORCpete <https://github.com/CORCpete> will be interested

**Comment by smr547** [comment]
@CORCpete please test current 1:1 arrangement during the working bee

**Comment by smr547** [comment]
Tested. The movement of the pole is much more direct and a higher effort is required. @CORCpete tested the system and said that it is satisfactory but cautioned that the loads on the line are much higher.

Closing this issue.

**Comment by smr547** [comment]
Two days ago @pcbaston emailed me as follows

> Steve,
> Chris reports the spin pole topping lift is not functioning. Apparet, a crew found the block broken (on traveller car?) and rerouted the topper lift so now it's a 1:1 purchase re 2:1. Any ideas about what's broken so I can look for a replacement block? Chris is in Sydney and I expect that will be our last opportunity to source a replacement for the SPS Regatta in a week's time. Photos would be appreciated.
> Spoke also to Sam D and Michael M who knows of the issue but not specifics. Can't find any GitHub discussion.
> Happy if you can point me in the right direction.
> Paul

The problem was "fixed" at the working bee by removing the jammed block and converting to a 1:1 mechanism -- see details above including photo. @Christopher-w-green reports that the increased weight on the line and untrimmed line length is causing the mechanism to unlock resulting in dangerous release of the pole. He recommends returning to a 2:1 system

I advised that that a new block is required for the top of the traveler and a new 10mm (?) line. The line will need to be tied to the eye above the traveler track requiring a man up the mast. Chris was going to source the block and line in Sydney for repairs later in the trip north.

Reopening this issue

**Comment by pcbaston** [comment]
Quick glance at Internet reveals the block to be SELDEN PBB 50 PLAIN BEARING BLOCK SINGLE, first search source [here](https://www.dyscmarine.com.au/products/selden-pbb-50-plain-bearing-block-single-405-001-1?variant=43896032362662&currency=AUD&utm_source=google&utm_medium=cpc&utm_campaign=google+shopping&gad_source=1&gclid=Cj0KCQjwiMmwBhDmARIsABeQ7xTpqodEfmGqSOSL9idptlZqfGiehNGEE0YxKwjDuLrRmZIuw5mRykkaAjpZEALw_wcB).
It appears Ronstan blocks are of equivalent quality and price, so I've sourced the Selden block as a replacement for $57 incl postage from the supplier linked above.

**Comment by Christopher-w-green** [comment]
Indeed, I bought some line and a block before I left Sydney.
Chris

**Comment by Christopher-w-green** [comment]
The new block I got was cheap. And we'll need the new line. So all good.

**Comment by pcbaston** [comment]
And here's a selection of Selden blocks in the spares bag! New blocks were not required!
![Uploading IMG_20240410_133644497_HDR.jpg…]()

**Comment by pcbaston** [comment]
New block arrived and fitted using new black line procured by Chris Green in Sydney. System returned to original 2:1 endless system. Working fine! Case CLOSED.

**Comment by smr547** [comment]
Thanks for doing this work Chris and Paul!
