### ISSUE TITLE
Antifoul appears to be failing

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#803]
There is a widespread build up of marine growth on Namadgi's hull despite having  been freshly sandblasted and antifouled in Nov 23 -- see #722 

The buildup is hard to removed and has the texture of solid calcium rice grains.

I've raise the issue with our marine surveyor in Southport and will report the matter to Australasian Antifoul

**Comment by smr547** [comment]
I'm getting a price to clean the bottom 

- Daniel from the King Bros shipyard -- lift, power blast, relaunch 
- Daz -- local diver who will scrape the bottom with a plastic scraper -- he will quote. Strictly cash only

Daniel has advised that N3 is right on the limit of their lift capacity -- April 8 is the best window. Out around 9am, back in the water 9am on April 9 -- 24 hrs downtime --- BUT wait, that doesn't work because Chris is out of here  on 3 April.

I'll let you know what Daz says.

I've tried scraping the growth, it comes away easily but leaves a calcium residue. See photo 

![IMG-0061](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/667dcfb8-891b-4d4e-9674-28f126489a8f)


@mrmrmartin @delcosta @mgrybaitis @pcbaston @Christopher-w-green @CORCpete @allister-polkinghorne will be interested

**Comment by smr547** [comment]
I've emailed Joel from Affordable Antifoul and Alexis our project manager. See copy below

Dear Alexis and Joel,

We need your advice  please. 

Namadgi 3 was sandblasted and antifouled by Affordable in November 2023. Unfortunately she is developing a heavy marine growth that is widespread and pervasive. I've tried scraping a small area on the rudder and the growth comes away relatively easily but leaves a calcium spot on the hull (see photo below). I suspect that this will attract further growth. 

We are concerned that we are getting heavy marine growth so soon after the antifoul and are worried about the quality of the  antifoul used. Your comments will be appreciated.

If remedial action is required please note that Namadgi 3 is booked to be at The Boatworks 6-10 May 2024

I look forward to hearing from you

kind regards
Steven

cc Peter Pope, Marine Surveyor

**Comment by Christopher-w-green** [comment]
Steven,

Spoke with Mid-Coast Marine, the yard at the marina in Newcastle. If we
just want to lift, pressure wash and drop back in, then they would be able
to do that in the window 10-12 April. It would cost about $1000.

Chatting about marine growth, the chap said that with the high water temps
these days it was pretty unavoidable. He thought that pressure washing
would not be enough to remove shells, and they would need to be scraped off
or even sand blasted, needing much more time ($). He said that putting a
diver down every month for a couple of hundred bucks was starting to look
economical.

If we want to book in, he wants us to fill in the booking form on their
website.

Chris

**Comment by smr547** [comment]
Steven's message to the committee

```
Colleagues,

The Committee's attention is drawn to the condition of the N3's bottom. There is a heavy growth of alge together with more advanced creatures with hard outer shells.  This became evident at Birkenhead Point but has accelerated at an alarming rate. The shells are now big. 

I'm forwarding the GitHub conversations related to this matter. The GitHub issue can be [viewed here](https://github.com/CanberraOceanRacingClub/namadgi3/issues/803) and it's worth a read.

I'm beginning to think that N3 is a victim of climate change and we may need to adopt a more aggressive policy towards cleaning her bottom.

She may not be a racing boat, but we may need to start treating her like one -- i.e. regularly hull scrubs using marina divers (or club volunteers). Obviously, another line item for our treasurer in the club's budget!

Hopefully the damage done will not require another sand blast.

kind regards
Steven
```

**Comment by smr547** [comment]
Daz the Diver from Batemans has pulled out of the job. I'll talk to Australiasian Antifoul and see what they recommend we do.  

@allister-polkinghorne

**Comment by smr547** [comment]
I've just called Joel from Affordable Antifouling and Alexis Baibas from SeaSpray to seek advice on the condition of the antifoul. Neither took my call but I left voice messages with them. Also provided a  followup email.

**Comment by smr547** [comment]
Colleagues,

Namadgi 3 is due at the Boatworks on 5/5.

I've booked a lift out for Namadgi 3 on Thursday 9/5 with a return to the
water the following day.  This was the earliest available time. The boat
will be inspected by Peter Pope (our surveyor) and Joel from Affordable
Antifoul to determine the cause of our fouling problem and work out a
remediation plan.

Rob, Please note that the remediation work may keep Namadgi 3 on the
hardstand into the following week, depending on the work required. I expect
she will be in the water again by Wednesday 15/5

The maintenance sub-committee will provide an update with a complete
worklist in the next few days.

kind regards
Steven

PS The planned haulout in Port Stephens will provide critical information
to inform the team at Boatworks -- perhaps the second haulout will prove
unnecessary -- fingers crossed.



-- 
Steven Ring
Maintenance Officer
Canberra Ocean Racing Club
m: 0417 495 268

**Comment by smr547** [comment]
Hi Joel,

Namadgi 3 will be hauled out at Port Stevens later this week for a water
blast prior to sailing in the regatta there. This may give us the
opportunity to get information on the state of the hull and the reason for
the fouling. We will get photos and the opinion of the local specialists.
Could you please let me know if there is any specific information you need.

Also, I have booked a haulout for Namadgi 3 at the Boatwork on Thursday 9th
May at 8am -- this will allow you to inspect the hull and determine what
action is required. Peter Pope will also attend.

This was the earliest time available -- could you please accommodate us in
your schedule and confirm the timing?

kind regards
Steven



On Tue, 26 Mar 2024 at 14:58, Steven Ring ***@***.***>
wrote:

> Hi Joel,
>
> Thank you for the reply.
>
> I'll let you know what the diver finds. Thank you for your guidance and
> support.
>
> kind regards
> Steven
>
> On Tue, 26 Mar 2024 at 14:37, Affordable Antifoul Solutions <
> ***@***.***> wrote:
>
>> hi steven
>> thanks for your email. i am looking into the issue of the growth on
>> Namadgi. we apply this paint to over 1000 boats a year and never have any
>> issues with it.
>> in the mean time please proceed with a diver to clean the bottom if you
>> feel is necessary. we will be on hand as soon as she comes out in may to
>> see what is happening and to rectify any problems we can see.
>> if you need to contact me, please don't hesitate 0437798598 is my
>> personal number.
>>
>>
>>
>> kind regards
>>
>> joel griffin
>>
>>
>> ------------------------------
>> *From:* Steven Ring ***@***.***>
>> *Sent:* Tuesday, March 26, 2024 1:08 PM
>> *To:* Alexis Bisbas ***@***.***>; Affordable Antifoul
>> Solutions ***@***.***>
>> *Cc:* CORC Committee ***@***.***>; Peter Pope <
>> ***@***.***>
>> *Subject:* Re: Namadgi 3
>>
>> Dear Joel,
>>
>> Could you get back to me on this matter please?
>>
>> The club needs your advice as to how we should proceed. We are
>> considering
>>
>>
>>    - Diver cleaning the hull with a plastic scraper, or
>>    - Haulout and pressure wash
>>
>>
>> The hull needs to be cleaned as the growth is impacting boat performance.
>> But we do not want to do anything that might complicate matters.
>>
>> kind regards
>> Steven
>>
>>
>> On Tue, 19 Mar 2024 at 12:21, Steven Ring <
>> ***@***.***> wrote:
>>
>> Dear Alexis and Joel,
>>
>> We need your advice  please.
>>
>> Namadgi 3 was sandblasted and antifouled by Affordable in November 2023.
>> Unfortunately she is developing a heavy marine growth that is widespread
>> and pervasive. I've tried scraping a small area on the rudder and the
>> growth comes away relatively easily but leaves a calcium spot on the hull
>> (see photo below). I suspect that this will attract further growth.
>>
>> We are concerned that we are getting heavy marine growth so soon after
>> the antifoul and are worried about the quality of the  antifoul used. Your
>> comments will be appreciated.
>>
>> If remedial action is required please note that Namadgi 3 is booked to be
>> at The Boatworks 6-10 May 2024
>>
>> I look forward to hearing from you
>>
>> kind regards
>> Steven
>>
>>
>>
>> On Mon, 6 Nov 2023 at 13:56, Steven Ring <
>> ***@***.***> wrote:
>>
>> Thank you Alexis,
>>
>> Please make the invoice out to
>>
>> Canberra Ocean Racing Club
>> C/- Steven Ring
>>
>> At this email address.  I'll organise payment either via credit card or
>> direct deposit.
>>
>> kind regards
>> Steven
>>
>> On Mon, 6 Nov 2023 at 12:04, Alexis Bisbas ***@***.***>
>> wrote:
>>
>> Hi Steven,
>> Just to confirm that we have booked the boat to be moved on Wednesday
>> afternoon at 3pm to the sand blast pad in the north yard.
>> I have discussed it with Joel from Affordable Antifoul , they will apply
>> Jotun Sea Victor 50 as the antifoul. It is the better of the Jotun paints.
>> They will start sand blasting on Thursday .
>> They request 50% deposit prior to commencing the work. I have copied
>> Affordable in on the email so that they can send the invoice directly to
>> you.
>> Best regards
>> Alexis
>>
>>
>>
>> --
>> Steven Ring
>> Maintenance Officer
>> Canberra Ocean Racing Club
>> m: 0417 495 268
>>
>>
>>
>> --
>> Steven Ring
>> Maintenance Officer
>> Canberra Ocean Racing Club
>> m: 0417 495 268
>>
>>
>>
>> --
>> Steven Ring
>> Maintenance Officer
>> Canberra Ocean Racing Club
>> m: 0417 495 268
>>
>
>
> --
> Steven Ring
> Maintenance Officer
> Canberra Ocean Racing Club
> m: 0417 495 268
>


-- 
Steven Ring
Maintenance Officer
Canberra Ocean Racing Club
m: 0417 495 268

**Comment by CORCpete** [comment]
Note, this very unusual rate of growth was first noticed (by an observant crew) in February, 3 months after application of the anti-foul.

On 8 Apr 2024, at 7:17 am, Steven Ring ***@***.***> wrote:


Hi Joel,

Namadgi 3 will be hauled out at Port Stevens later this week for a water
blast prior to sailing in the regatta there. This may give us the
opportunity to get information on the state of the hull and the reason for
the fouling. We will get photos and the opinion of the local specialists.
Could you please let me know if there is any specific information you need.

Also, I have booked a haulout for Namadgi 3 at the Boatwork on Thursday 9th
May at 8am -- this will allow you to inspect the hull and determine what
action is required. Peter Pope will also attend.

This was the earliest time available -- could you please accommodate us in
your schedule and confirm the timing?

kind regards
Steven



On Tue, 26 Mar 2024 at 14:58, Steven Ring ***@***.***>
wrote:

> Hi Joel,
>
> Thank you for the reply.
>
> I'll let you know what the diver finds. Thank you for your guidance and
> support.
>
> kind regards
> Steven
>
> On Tue, 26 Mar 2024 at 14:37, Affordable Antifoul Solutions <
> ***@***.***> wrote:
>
>> hi steven
>> thanks for your email. i am looking into the issue of the growth on
>> Namadgi. we apply this paint to over 1000 boats a year and never have any
>> issues with it.
>> in the mean time please proceed with a diver to clean the bottom if you
>> feel is necessary. we will be on hand as soon as she comes out in may to
>> see what is happening and to rectify any problems we can see.
>> if you need to contact me, please don't hesitate 0437798598 is my
>> personal number.
>>
>>
>>
>> kind regards
>>
>> joel griffin
>>
>>
>> ------------------------------
>> *From:* Steven Ring ***@***.***>
>> *Sent:* Tuesday, March 26, 2024 1:08 PM
>> *To:* Alexis Bisbas ***@***.***>; Affordable Antifoul
>> Solutions ***@***.***>
>> *Cc:* CORC Committee ***@***.***>; Peter Pope <
>> ***@***.***>
>> *Subject:* Re: Namadgi 3
>>
>> Dear Joel,
>>
>> Could you get back to me on this matter please?
>>
>> The club needs your advice as to how we should proceed. We are
>> considering
>>
>>
>> - Diver cleaning the hull with a plastic scraper, or
>> - Haulout and pressure wash
>>
>>
>> The hull needs to be cleaned as the growth is impacting boat performance.
>> But we do not want to do anything that might complicate matters.
>>
>> kind regards
>> Steven
>>
>>
>> On Tue, 19 Mar 2024 at 12:21, Steven Ring <
>> ***@***.***> wrote:
>>
>> Dear Alexis and Joel,
>>
>> We need your advice please.
>>
>> Namadgi 3 was sandblasted and antifouled by Affordable in November 2023.
>> Unfortunately she is developing a heavy marine growth that is widespread
>> and pervasive. I've tried scraping a small area on the rudder and the
>> growth comes away relatively easily but leaves a calcium spot on the hull
>> (see photo below). I suspect that this will attract further growth.
>>
>> We are concerned that we are getting heavy marine growth so soon after
>> the antifoul and are worried about the quality of the antifoul used. Your
>> comments will be appreciated.
>>
>> If remedial action is required please note that Namadgi 3 is booked to be
>> at The Boatworks 6-10 May 2024
>>
>> I look forward to hearing from you
>>
>> kind regards
>> Steven
>>
>>
>>
>> On Mon, 6 Nov 2023 at 13:56, Steven Ring <
>> ***@***.***> wrote:
>>
>> Thank you Alexis,
>>
>> Please make the invoice out to
>>
>> Canberra Ocean Racing Club
>> C/- Steven Ring
>>
>> At this email address. I'll organise payment either via credit card or
>> direct deposit.
>>
>> kind regards
>> Steven
>>
>> On Mon, 6 Nov 2023 at 12:04, Alexis Bisbas ***@***.***>
>> wrote:
>>
>> Hi Steven,
>> Just to confirm that we have booked the boat to be moved on Wednesday
>> afternoon at 3pm to the sand blast pad in the north yard.
>> I have discussed it with Joel from Affordable Antifoul , they will apply
>> Jotun Sea Victor 50 as the antifoul. It is the better of the Jotun paints.
>> They will start sand blasting on Thursday .
>> They request 50% deposit prior to commencing the work. I have copied
>> Affordable in on the email so that they can send the invoice directly to
>> you.
>> Best regards
>> Alexis
>>
>>
>>
>> --
>> Steven Ring
>> Maintenance Officer
>> Canberra Ocean Racing Club
>> m: 0417 495 268
>>
>>
>>
>> --
>> Steven Ring
>> Maintenance Officer
>> Canberra Ocean Racing Club
>> m: 0417 495 268
>>
>>
>>
>> --
>> Steven Ring
>> Maintenance Officer
>> Canberra Ocean Racing Club
>> m: 0417 495 268
>>
>
>
> --
> Steven Ring
> Maintenance Officer
> Canberra Ocean Racing Club
> m: 0417 495 268
>


-- 
Steven Ring
Maintenance Officer
Canberra Ocean Racing Club
m: 0417 495 268

**Comment by smr547** [comment]
Photos from pressure wash and manual scrape at Port Stephens 11/4/24

![IMG_20240411_102524234_HDR](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/e32c9f5a-181a-4eab-ad17-8179b567e710)
![IMG_20240411_102627326_HDR](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/61a198ec-ead7-4053-9261-2e1471715739)
![IMG_20240411_102646112_HDR](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/42a48f54-7bb1-4ac9-876c-ef0d292de487)
![IMG_20240411_102711515_HDR](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/1123d0d2-f47a-4877-b413-b7cdb350d3a7)
![IMG_20240411_115751023_HDR](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/db00ae5f-4ae5-4c5d-a45c-555cf14ea24a)
![IMG_20240411_115914745_PORTRAIT](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/60739eda-a3ac-4f11-b12d-863a3b8baef3)
![IMG_20240411_120014602_PORTRAIT](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/7527b530-236b-44a9-8930-d18990a568d5)

**Comment by smr547** [comment]
Excellent analysis from @CORCpete 

[peter_o_antifoul_comments.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/15084367/peter_o_antifoul_comments.pdf)

@pcbaston will be interested

**Comment by smr547** [comment]
I spoke with Aiden Mijet (0439 238 668) from Joton Australia (Brisbane office). He said ``Jotun Sea Victor 50``  is now known as ``SeaQuantum Spectrum``. Aiden will email specs for the product.

Their salesman Jay McCoy 0419 024 441 could be of further help.

See the [SeaQuantum Spectrum spec sheet](https://www.eltemsah-group.com/wp-content/uploads/2018/07/SeaQuantum-Spectrum.pdf) found on the internet.

@pcbaston @CORCpete will be interested

**Comment by smr547** [comment]
@Christopher-w-green -- Do you recall how the antifoul was applied? I recall you were at Boatworks at the time.  

regards
Steven

**Comment by Christopher-w-green** [comment]
No, the boat was back in the water when I arrived. I didn't see it getting
painted.

**Comment by smr547** [comment]
Thanks Chris

**Comment by smr547** [comment]
This morning I spoke with Peter Pope, our marine surveyor at Boatworks. He has reviewed the photos from Port Stephens. Peter believes that the product used was faulty. The coating seems mechanically sound as the shell mostly came away without physical damage to the coating -- this indicates proper preparation and application. The extent of the marine growth suggested to him that the active ingredients in the antifoul were not very active.

I'll prepare and email to Affordable Antifoul asking for remediation. We have contact details for Jotun Australia if they need to get involved.

@pcbaston will be interested

**Comment by smr547** [comment]
I spoke to Jade from Affordable Antifoul to confirm the appointment for 8am on Thursday May 9 at the Boatworks. He said he and Joel will be there. He was surprised the Sea Victor 50 product had failed as he described it as "the good one". Jade said a reapplication would probably be necessary and that they would work with Joton "to look after us"

@pcbaston will be interested

**Comment by smr547** [comment]
Affordable antifoul have sanded the hull back to the base coat (which appears sound) and have applied two coats of International Micron antifoul.  We must NOT use Joton products in the future.  This work was done at no cost to CORC as Affordable acknowledged that the original antifoul had failed. 

closing this issue
