### ISSUE TITLE
Revarnish water damaged drinks holder

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#804]
Holder is located at the aft end of the console table in the cockpit

![IMG-0043](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/d2c5e85e-3798-4a8e-b362-6ef1decaccb7)

**Comment by pcbaston** [comment]
![17128931068594188427401617533827](https://github.com/CanberraOceanRacingClub/namadgi3/assets/120452016/8120a3ab-637a-43b2-9d8b-b1b24bb4ca12)

Job done and remounted. 
Issue CLOSED.
