### ISSUE TITLE
Mop up bilge

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#813]
There is a significant amount of water trapped in the bilge. I suggest we use a bucket and a sponge and mop up all remaining water.

[] - floor compartments in aft starboard cabin
[] - floor compartmetns around starboard side of lower end of companion way
[] - area behind engine (assessibe via the storage cabinet separating the aft bunks -- empty the compartment and lift the floor to gain access

A big sponge and a bucket is required.

**Comment by pcbaston** [comment]
Done. Chris Green and crew mopped out the under deck stowages. 
Today Chris sucked out the oily water from the engine bilge and wiped clean with a rag. We disposed of the oil cognisant of the environment we are currently in.
The only remaining bit to do is to get behind the engine and wipe the floor down.

**Comment by smr547** [comment]
Engine bilge mopped up by @Christopher-w-green Coffs Harbour -- a substantial amount of salt water and a little dark oil.
