### ISSUE TITLE
Replacing Namadgi's diesel and saildrive

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#817]
This topic has come up because Namadgi's engine has 4300 hours of use. Some argue that it might need replacing soon. What are peoples thoughts? What are the costs of planned replacement?

Also, what would be the impact of unexpected failure of the engine or saildrive in a remote location? A new cost model altogether! What are the risks? Are there safety issues?

Please use this is a discussion thread.

**Comment by smr547** [comment]
Steven and Paul have had a preliminary conversation about this via email...

[Ring_and_Baston_conversation.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/14845818/Ring_and_Baston_conversation.pdf)

@pcbaston

**Comment by smr547** [comment]
@pcbaston has had a useful conversation with Thwaites and has obtained a quote: 

[baston_and_thwaites.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/14845836/baston_and_thwaites.pdf)
[Quote QU0883.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/14845839/Quote.QU0883.pdf)

Looks like #budget=$30,000


@Christopher-w-green will be interested in this conversation. I'll alert the Committee to this thread -- they will be interested -- particularly @allister-polkinghorne

**Comment by smr547** [comment]
Closing this issue as it is not an "open maintenance issue". Despite being closed, the issue can serve as a forum for future discussion.

**Comment by delcosta** [comment]
Steven and Paul
Thank you for opening this up. 
My thoughts are that our boats needs to be as safe as possible and a timely maintenance program is proving beneficial.
With Skipper training and engagement we can have a boat that will be very good to us.
Without meaning to be fatalistic, an engine failure in a remote place would be very stressing, especially in wild weather, where it could be catastrophic.
We take good care of our motor and sail drive, and any statistical info that we can obtain will clarify how we sit in the expected life cycle of our drive pack would help this discussion.

**Comment by smr547** [comment]
Hi Sam (@delcosta),

You've hit the nail on the head regarding the potential impact of a unexpected failure in remote places. 

Other's have noted that the engine is showing no great sign of distress (coloured smoke, strange noises, loss of power etc). This is encouraging. But we are getting annoying oil leaks so we need to keep a close eye on it -- and certainly do some planning.

I'm sure there is a wealth of information on the sailing forums regarding our diesel/saildrive combination -- it's a very common configuration. Perhaps some of us will find time to do further research and comment here.

Thanks again for the response.

**Comment by smr547** [comment]
I support Paul's advice to the Committee, which reads:

My advice to the Committee, at present, would be:

1. Note the engine is nearing end of life
2. Note the quote to replace is $30,000
3. Note the 'estimated' reduction in yacht value of $30,000 if the engine is not replaced before a sale
4. Note the engine is well maintained and is expected to survive another 1000-3000 hours
5. Be prepared to replace the engine and saildrive at short notice should a catastrophic condition occur (this would be common risk management $ contingency)

I would recommend a rebuild (or exchange rebuilt engine) as more cost effective, that way, we keep the engine delivered with the yacht. Based on this, my recommendation would be to NOT replace the engine unless absolutely necessary (last condition) and to sell the vessel with a working, well maintained engine.

My rationale is:
Installing a new engine before sale would not be cost effective financially (the cost MAY be recovered, but I doubt it)
A new owner would get the vessel cheaper, with a working engine, but know that at some stage in the future they would need to replace the engine (cost deferral) It would save CORC a considerable expense now noting the financial pressures we are facing after the last maintenance period.

**Comment by allister-polkinghorne** [comment]
From my experience with diesel engines – probably in the order of 25,000 hours of operation in heavy machinery, trucks, tractors and cars, I would conclude that the boat engine is not even at half-life. 

This is based on the following: 
*	First overhaul of a John Deere tractor engine that was worked at power capacity all of its first life at 12000 hours.
*	First overhaul of paddock used Caterpillar D6 (i.e. used at limit power and turbo charged) at 19,000 hours
*	First overhaul of a Caterpillar dozer (i.e. used at around 60% limit power for its operating life turbo charged) at 22,000 hours
*	First overhaul of a GM371 engine fitted to a truck (high reving, 2 stroke, supercharged engine and around 11,000 hours. 
*	Overhaul of early generation Fordson diesel engines at around 6,000 hours. 

I have heard, although not worked with, Gardner engines in boats that have run more than 25,000 hours before the first overhaul. My diesel car which has done about 4,000 hours over 15 years still doesn’t use oil and still performs very well. 

Based on the fact that the boat engine, starts very easily, uses a very limited amount of oil, does not smoke excessively and is used at relatively low and constant power settings leads me to the conclusion that we could expect more than another 3000 hours of relatively trouble free running. This is not a guarantee that it will be case but I believe the risk of a catastrophic failure necessitating replacement is relatively low. 

That said, I know less about sail drives but am cognisant of the requirement to keep water our at all times. I believe we are approaching the recommended inspection life of the seals etc. I believe we may be well advised to consider the maintenance arrangement for that device. 

Cheers Allister

**Comment by mgrybaitis** [comment]
I concur with Allister having just replaced the diesel engine in Horizon
which was over 40 years old.

Regards

**Comment by smr547** [comment]
Seatech Marine, Volvo dealer at Boatworks, assessed Namadgi's drive train as "uneconomical to repair" when it was submitted for service in May 2024 exhibiting several service issues. The committee, having considered their report and advice from members of the Maintenance Sub-Committee elected to replace the entire drivetrain.  The old motor had provided 4,360 hours of service.

This work was completed by Seatech Marine at a cost of around $36,000. Namadgi 3 departed Boatwork on 9 June 2024 with a new D2-75 diesel and saildrive installed.

* [Photos of old motor](https://photos.app.goo.gl/hb73A3hn1QXeLpEQA)
* [Photos of new motor and saildrive](https://photos.app.goo.gl/UxezmHgGmX4cQ1Tm8)

* [D2 OWNERS MANUAL.pdf](https://github.com/user-attachments/files/15786934/D2.OWNERS.MANUAL.pdf)
* [Volvo-D2-75-Unit-Details-20240611210123.pdf](https://github.com/user-attachments/files/15786935/Volvo-D2-75-Unit-Details-20240611210123.pdf)

Based on this experience the maintenance manager has prepared a Drivetrain - lifetime cost of ownership spreadsheet (see below) showing that the total  cost of ownership is about $A27 per engine hour used. He recommends that CORC: 

1. budget for drivetrain replacement every  5000 hours
2. include a $30 per hour engine usage charge when computing Namadgi's daily usage fees (either charged directly for hours used or factored into the basic daily rate)
3. Consider a diesel genset and solar panels as an alternate means of battery charging -- given that a significant proportion of engine hours are spent simply charging batteries at anchor -- (using a 75 hp diesel to run a 2 hp alternator is madness!!)


[Drivetrain lifetime cost analysis - Sheet1.pdf](https://github.com/user-attachments/files/15787045/Drivetrain.lifetime.cost.analysis.-.Sheet1.pdf)


Leaving this issue closed
