### ISSUE TITLE
Wind generator

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#82]
Rutland 1200 windcharger? Silent wind, etc
estimate: $2,500

**Comment by DeeTaylor87** [comment]
For those interested, links below:
Products
https://www.emarineinc.com/categories/Marine-Wind-Turbine-Index
https://www.whitworths.com.au/main_itemdetail.asp?cat=123&item=94190
https://www.whitworths.com.au/main_itemdetail.asp?cat=123&item=94191&intAbsolutePage=&LinkedItem=94190&search123=
http://smallwindgenerators.com.au/product-category/marine
http://www.stellasystems.com.au/wind-generators.php?gclid=Cj0KEQjwn6DMBRC0p7P_lKu8opgBEiQAdm0J44KBzzuooyvBJI3w1e64MyWJJQnKY9a3nDR1eDJy-5saAuxU8P8HAQ
https://www.emarineinc.com/categories/Wind-and-Solar-Hybrid-Kits
https://www.emarineinc.com/categories/Solar-and-Wind-Ctrl-Panels
Forums and articles
http://www.yachtingworld.com/gear-reviews/wind-water-and-solar-power-65797
http://www.cruisingworld.com/how/wind-and-solar-are-fine-osprey
http://www.mysailing.com.au/news/almost-as-free-as-the-wind
https://www.emarineinc.com/Wind-Generator-vs-Solar-Panels-Which-is-Better-For-Your-Boat
http://www.tor.cc/articles/energy.htm
New technology - hydrogenerator
http://www.sail-world.com/Australia/New-cruising-hydrogenerator-produces-power-at-just-2kts-of-speed/121400?source=google.au
http://www.wattandsea.com/en/products

**Comment by DeeTaylor87** [comment]
Chris the electrician from BME recommended not getting wind power - he said it only provided a trickle and only worked when the wind was really strong. He was keener on solar.

**Comment by smr547** [comment]
Closing this item -- historical
