### ISSUE TITLE
Oil leaking from saildrive

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#826]
@Christopher-w-green and @pcbaston have reported a loss of oil from the sail drive. Schedule for inspection/repair at boatworks in early May.

Meanwhile, Skippers are asked to check the saildrive oil levels regularly and top up as necessary. Please report findings in the Skippers Handover Notes.

Oil reading on dipstick is taken by removing dipstick, drying and then inserting back without screwing back in. Once oil level has been checked and topped up as necessary, the dip stick is then secured. Be careful not to force the thread in case of cross-threading. Read the 2017 Volvo Engine manual is any doubt exists.

Top up with 15W-45 VDS4 oil (from lazarette locker).

**Comment by pcbaston** [comment]
Chris and I checked the Sail Drive oil level in Port Stephens prior to SPS24 regatta.  We ended up putting 800ml of 15W-45 VDS4 oil (from lazarette locker) into the drive to get the oil dip stick to register oil. 

Note: oil reading on dipstick is taken by removing dipstick, drying and then inserting back **without** screwing back in. Once oil level has been checked and topped up as necessary, the dip stick is then secured. Be careful not to force the thread in case of cross-threading.  Read the 2017 Volvo Engine manual is any doubt exists.

This should be in Notice to Skippers.

**Comment by smr547** [comment]
Edited this issue for inclusion in [Notice to Skippers]([url](http:/7.southsky.com.au/notice2skippers.pdf))

Original post:

@Christopher-w-green and @pcbaston have reported a loss of oil from the sail drive. Schedule for inspection/repair at boatworks in early May.
![report_chris_green](https://github.com/CanberraOceanRacingClub/namadgi3/assets/4327895/a4e89cd3-b2f8-4dd4-a80a-5e86eb872f28)

**Comment by smr547** [comment]
Checked the saildrive this evening. All good. Oil full and clear. We will keep an eye on it. 

@Christopher-w-green @CORCpete

**Comment by smr547** [comment]
Saildrive and diesel have been replaced. No longer an issues -- closing
