### ISSUE TITLE
HF Antenna feed wire broken

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#829]
The feed wire has broken at the connection point at the bottom of the starboard side backstay wire.

**Comment by pcbaston** [comment]
Ah, Yes, I noticed that and was going to repair. Easy to strip some wire and reattach to backstay via the circlip clamp, but I fear the wire will have corroded inside the insulation.  May need a new wire made, with eye at bottom.  Ensure wire is marine grade tinned copper wire. Perhaps a crimped terminal at the top end may be good.

PS. Does anyone use the HF radio anymore? Perhaps we should just put this on the backburner for now.

**Comment by smr547** [comment]
Temporary repair today. HF test call to follow.

**Comment by smr547** [comment]
Wire has been replaced by Onboard Electrical. Test call was successful. 

Closing the issue
