### ISSUE TITLE
Bigger alternator Balmar AT-SF-165 including >

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#84]
ME-164 Multi-step regulator inc. temp sensor. Need to determine how much charging is needed
timing: Wait
estimate: $2,900

**Comment by DeeTaylor87** [comment]
Not sure about this issue. @smr547 Cross check with conversation re Whats App.  The new alternator is a Leece Neville. The regulator is a Balmar.

**Comment by smr547** [comment]
@jphayden checked with Bill this evening and he is very happy with the choice of alternator. Once Jack gives the OK we can close this

**Comment by DeeTaylor87** [comment]
The new alternator has been installed. There were some new cables that went with it  because the old cables were not the appropriate specs for the power being generated. Chris showed me the difference between the two cables and it was quite substantial. He seemed bemused/concerned that whoever put that cable in there was not paying attention to the load requirements.  A new bracket also had to be made for the new alternator.

**Comment by jphayden** [comment]
Thanks Dee - I will be interested to see -m have you got pictures

**Comment by DeeTaylor87** [comment]
![new alternator](https://user-images.githubusercontent.com/30706096/29955165-f6478102-8f20-11e7-8eb4-50a2c2266f45.jpg)
Sorry Jack - the cable has been installed. It is the supply from the alternator to the battery terminal. 
Also, Douglas Marine sent over a bag of spare fuel and oil filters, sea water impellor and spare engine oil. They also sent a spare alternator belt but unfortunately it was for the old alternator not the new one - they are not interchangeable.  The new alternator belt will be available at any motor shop.  It's part number is 5PK1065.  We should probably get one and keep it on board as a spare.

**Comment by jphayden** [comment]
Yes indeedy

**Comment by DeeTaylor87** [comment]
And the electrician showed me the best way to check if the alternator belt is too loose. If you run the engine for five minutes and then feel the black hub that the alternator runs around, it should feel warm but not piping hot. If it is too hot too touch, the alternator belt is too loose.
