### ISSUE TITLE
Saltwater deck wash pump

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#85]
estimate: $350

**Comment by DeeTaylor87** [comment]
RT Marine has
https://www.roadtechmarine.com.au/twin-port-aeration-live-well-for-washdown-pump/p/MJA110
https://www.roadtechmarine.com.au/johnson-wd-5-2-12-24v-washdown-kit-full/p/MPA410

**Comment by DeeTaylor87** [comment]
I haven't spoken to a plumber about it, but I imagine that the salt water feed would come from either the port or starboard aft toilet inlet through to the cockpit.  If we do this, it would be good to get a saltwater faucet for the galley at the same time to save doubling up plumbing work and ensure efficiency of lines.

**Comment by smr547** [comment]
Can you get him to give us a price?
I think I'll include a "plumbing" label so we can group all the plumbing issues together. It might become your favourite link Dee :D

**Comment by DeeTaylor87** [comment]
Quote obtained from Q Services.  Fit pump in fwd head area and plumb through to anchor locker for washdown installation of tap fitting and flexible hose in anchor locker.  Mount switch system in locker area of forward head. Mount and plumb pump to existing toilet inlet valve. Run Whale system 15 through to anchor locker.  Using Johnson wash down kit.

**Comment by smr547** [comment]
Closing this item -- historical
