### ISSUE TITLE
Cabin fans x 4

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#87]
who: CORC
timing: December
estimate: $500

**Comment by DeeTaylor87** [comment]
http://www.australiandirect.com.au/shop/12v-24v-appliances/12v-24v-dc-fans/6099
http://www.outbackmarine.com.au/caframo-ultimate-model-757-12-volt-dc-178mm-7-quot
http://www.sulekha.com/fan/cabin-fans-prices-and-specifications

**Comment by smr547** [comment]
Closing this item -- historical
