### ISSUE TITLE
Satellite Communications - IridiumGo

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#88]
timing: 2018
estimate: $2,000

**Comment by DeeTaylor87** [comment]
Cat One info
3.25 | Satcom C equipment forms part of   the Global Maritime Distress and Safety System and is carried aboard all   commercial shipping as well as by shore based rescue coordination centres.   This technology is well established and is an option available to yachts participating   internationally under the World Sailing Special Regulations. Owners and race   organisers may consider phasing in this equipment as a prelude to its   potential introduction into future versions of these Special Regulations.
(d) | A satellite phone is   recommended. The satellite phone should have coverage of the race area, and   be connected to the main power or have a spare battery.
-- | --
