### ISSUE TITLE
Water maker

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#89]
OpenOcean, RainMan, Stella
timing: 2018
estimate: $8,000

**Comment by DeeTaylor87** [comment]
Links for those interested
Products
http://www.stellasystems.com.au/watermakers.php
http://rainmandesal.gorvmarine.com.au/
http://www.wetss.com.au/products.shtml#products
http://www.nmss.com.au/gyros-watermakers
Forums and Articles
http://www.cruisersforum.com/forums/f124/anyone-using-rainman-water-maker-135331.html
https://www.tradeboats.com.au/tradeaboat-news/boat-diy/1208/know-how-watermakers
http://www.cruisingworld.com/desalination-decisions-watermakers

**Comment by smr547** [comment]
Closing this item -- historical
