### ISSUE TITLE
HF radio, backstay antenna, AT141 tuner

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#90]
No we might not need to fit an HF radio
timing: 2018
estimate: $5,000

**Comment by DeeTaylor87** [comment]
I know that there is some debate about the need (or not) to fit this. But for general info, here are the current published Cat one requirements:
3.25.1 | The following waterproof or   marine standard communication equipment shall be provided:
(a) | (i) Permanently installed HF   transceiver. (ii) All new HF transceivers shall be DSC capable.(i) It is   recommended that all HF transceivers be DSC capable. (ii) Where shore based   VHF facilities exist for the entire length of the course, the organising authority   may permit an installed VHF transceiver only and this shall be included in   the notice of race.
( c ) | Where permanently installed, DSC   HF/VHF transceivers shall be programmed with an assigned MMSI (unique to the   boat), and where there is permanently installed GPS, be connected to a GPS   receiver, and be capable of making distress alert calls as well as sending   and receiving a DSC position report with another DSC equipped station.   Periodically a test call should be made to AMSA which should be automatically   acknowledged.
3.25.3 | Permanently installed HF   transceivers shall be:
(a) | Able to transmit and receive on   the standard distress frequencies of 4125, 6215, 8291 kHz.
(b) | Tested in accordance with the   notice of race.
