### ISSUE TITLE
Grab Bag around 20L - old one damaged by oil

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#91]
choose a stowage before we buy one.
who: CORC

**Comment by DeeTaylor87** [comment]
Note Cat One Document

(a) A   yacht is recommended to have for each liferaft, a grab bag. A grab bag should   have inherent flotation, at least 0.1 m2 area of fluorescent orange colour on   the outside, should be marked with the name of the yacht, and should have a   lanyard and clip
--

**Comment by DeeTaylor87** [comment]
Whitworths have these
https://www.whitworths.com.au/main_itemdetail.asp?cat=144&item=74354&intAbsolutePage=1
Do you want me to pick one up?

**Comment by DeeTaylor87** [comment]
RT Marine have these on special
https://www.roadtechmarine.com.au/dry-bags-overboard-20l/p/MKA120

**Comment by DeeTaylor87** [comment]
BCF have these
http://www.bcf.com.au/Product/BCF-Safety-Gear-Bag/131930?menuFrom=571531
and
http://www.bcf.com.au/Product/Escape-Outdoors-Heavy-Duty-Dry-Bag-25L-Orange/381749?menuFrom=20405

**Comment by DeeTaylor87** [comment]
Purchased the Whitworths 20Litre bag today. It comes with D-clip for lanyard.  Will drop it to boat later this week and store in the bay directly in front of the port aft cabin.  Just need to decide what is going in it.  Also need to get the 0.1m orange fluoro patch to put on it to comply with Cat One.

**Comment by DeeTaylor87** [comment]
Are the contents from the previous Grab Bag still in one place???? @DaveHolt  @paulmc9999

**Comment by paulmc9999** [comment]
I would not have a clue (I have not sailed on Namadgi 2 for 2 years)

**Comment by DaveHolt** [comment]
Hi,
The grab bag had engine oil spilled into it whilst in the store. We tried to wash it all but the bag and most items had to be thrown out. We threw out the bag, ~6 flares, signaling mirror, space blanket, water bottles, cyalume sticks.

**Comment by DeeTaylor87** [comment]
![image](https://user-images.githubusercontent.com/30706096/29805762-0275624a-8ccf-11e7-8b42-424e7cfb6740.png)
This is a bailer kit for sale at RT Marine for $29:95.  It is a 2L bailing bucket containing rope, mirror, compass, whistle and torch. They also sell red flares for about $15 each, orange flares for about $18 and white flares for about $18 each.  A waterproof flare container costs $43.  If I purchased 2 flares of each kind, the bailer kit and the flare container, it would cost about $175.  We have a space blanket on board already that could go in it.  Does the committee think those items should be purchased now?  @delcosta @DaveHolt @smr547 @pjwain @peterottesen @mrmrmartin @SRDunlop?

**Comment by DaveHolt** [comment]
Hi, I think I put the flare container with an in date set of flares on board Namadgi3. The bailer kit looks Ok.

**Comment by DeeTaylor87** [comment]
I'll delay a bit more, I think. We have torches and better sounding devices on board.  Not sure how accurate the compass would be anyway. The bailing bucket and rope would probably be the most useful items there.  Good that we still have a flare container with flares.

**Comment by DaveHolt** [comment]
Reading the Survitec RFD website it looks like the new liferaft with >24 hour kit will contain all of those items and more.

**Comment by DeeTaylor87** [comment]
The large flare container is currently stored in the central cockpit locker, but the flares are out of date.  I purchased a small flare container and some red parachute, orange and white flares plus some cyalume sticks to go in the grab bag for the delivery trip. The yellow grab bag is currently stored in the underfloor bay just in front of the companionway.

**Comment by DeeTaylor87** [comment]
PS - also purchased a V-sheet because there wasn't one on board. It is in the same storage bay as the Grab bag.
