### ISSUE TITLE
Emergency thermal bag space blanket thing - damaged by oil 

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#92]
who: CORC

**Comment by DeeTaylor87** [comment]
https://www.roadtechmarine.com.au/coleman-emergency-blanket/p/TSC412

Happy to pick one up when I am there, when we are ready.

**Comment by DeeTaylor87** [comment]
The space blanket has been purchased and has been put with the first aid kit and medical supplies in the saloon seating bay on the starboard side
