### ISSUE TITLE
Towel hooks for cabins

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#95]
who: CORC

**Comment by DeeTaylor87** [comment]
The best RT Marine could offer was these: https://www.roadtechmarine.com.au/canopy-loops-eyes-hooks-loops-stainless-316-cast-2-x-no-8-c-s-screws-or-4mm/p/MBC245 although they are not particularly pretty. Perhaps we can do better

**Comment by DeeTaylor87** [comment]
http://www.harveynorman.com.au/bathroom-tiles-renovations/bathroom-accessories/robe%20hooks/1065?gclid=Cj0KCQjwwqXMBRCDARIsAD-AQ2iC_niIEp7d3dl07_QSBJRkp2k08AxtTyAvi_rscAmYaYxxzaVXdi4aAsfgEALw_wcB&gclsrc=aw.ds

Bunnings do chrome and brass versions of these
https://www.bunnings.com.au/zenith-40mm-brass-plated-single-robe-hook_p3930532
https://www.bunnings.com.au/zenith-30mm-chrome-plated-double-robe-hook_p3930537

chrome only in this https://www.bunnings.com.au/syneco-50mm-chrome-plated-double-robe-hook_p3970354
Actually there is a pretty full range with the less expensive options including:https://www.bunnings.com.au/dorf-kip-bathroom-robe-hook_p4822154  so it depends how much people want to spend.

**Comment by DaveHolt** [comment]
Bill has fitted 2 in each cabin. Could possibly do with more in bathrooms. close issue for now.
