### ISSUE TITLE
Restraining shockcord for companionway storm board

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#98]
who: CORC

**Comment by DeeTaylor87** [comment]
Note Cat One Requirement

3.07.4   (a) | A companionway   hatch shall be fitted with a strong securing arrangement (e.g. latch),   capable of securing the hatch in a closed position, which shall: (i) Be   operable from above and below including when the boat is inverted.  (ii) Function independently of any blocking   devices.
-- | --
(b) | A   companionway hatch shall have any blocking devices (e.g. washboards):  (i) Capable of being retained in position   with the hatch open or shut. (ii) Secured to the boat (e.g. by lanyard) for   the duration of the race to prevent being lost overboard.  (iii) So positioned as to permit exit in   the event of an inversion.

**Comment by smr547** [comment]
Closing this item -- historical
